### ISSUE TITLE
How to test that proper parameters have been passed

### ISSUE THREAD

**Issue by mfour-merickson** [laravel-zero/laravel-zero#103]
When creating tests which call the various commands, how do I supply 'mock' arguments or options to make sure they are valid

```
        $this->app->call((new DatabaseInfoCommand())->getName());
```

This will not contain the name argument (for obvious reasons, it is not passed)

**Comment by nunomaduro** [comment]
@mfour-merickson You wanna call your command with arguments? The method call accept the following args: 

`public function call($command, array $parameters = [], $outputBuffer = null)`

So, you are able to call your DatabaseInfoCommand on the following way:

`$this->app->call((new DatabaseInfoCommand())->getName(), ['name' => 'database-name']);`

**Comment by nunomaduro** [comment]
@mfour-merickson Got news on this?

**Comment by mikeerickson** [comment]
@nunomaduro Yes, all is good, thanks :-)
