### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by bloggervista** [laravel-zero/laravel-zero#104]
Whenever i try to install

```
➜  hello composer global require laravel-zero/installer
Changed current directory to /Users/shirshak/.composer
Using version ^1.1 for laravel-zero/installer
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install laravel-zero/installer v1.1.7
    - Conclusion: don't install laravel-zero/installer v1.1.6
    - Conclusion: don't install laravel-zero/installer v1.1.5
    - Conclusion: don't install laravel-zero/installer v1.1.4
    - Conclusion: don't install laravel-zero/installer v1.1.3
    - Conclusion: don't install laravel-zero/installer v1.1.2
    - Conclusion: don't install laravel-zero/installer v1.1.1
    - Conclusion: remove symfony/console v4.0.2
    - Installation request for laravel-zero/installer ^1.1 -> satisfiable by laravel-zero/installer[v1.1.0, v1.1.1, v1.1.2, v1.1.3, v1.1.4, v1.1.5, v1.1.6, v1.1.7].
    - Conclusion: don't install symfony/console v4.0.2
    - laravel-zero/installer v1.1.0 requires laravel-zero/framework ~3.6 -> satisfiable by laravel-zero/framework[v3.10.0, v3.6.0, v3.6.1, v3.6.10, v3.6.11, v3.6.12, v3.6.2, v3.6.3, v3.6.4, v3.6.5, v3.7.0, v3.7.1, v3.7.2, v3.8.0, v3.8.1, v3.8.2, v3.9.0, v3.9.1, v3.9.2].
    - laravel-zero/framework v3.10.0 requires illuminate/console 5.5.* -> satisfiable by illuminate/console[v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28].
    - laravel-zero/framework v3.6.0 requires illuminate/console 5.5.* -> satisfiable by illuminate/console[v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28].
    - laravel-zero/framework v3.6.1 requires illuminate/console 5.5.* -> satisfiable by illuminate/console[v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28].
    - laravel-zero/framework v3.6.10 requires illuminate/console 5.5.* -> satisfiable by illuminate/console[v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28].
    - laravel-zero/framework v3.6.11 requires illuminate/console 5.5.* -> satisfiable by illuminate/console[v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28].
    - laravel-zero/framework v3.6.12 requires illuminate/console 5.5.* -> satisfiable by illuminate/console[v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28].
    - laravel-zero/framework v3.6.2 requires illuminate/console 5.5.* -> satisfiable by illuminate/console[v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28].
    - laravel-zero/framework v3.6.3 requires illuminate/console 5.5.* -> satisfiable by illuminate/console[v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28].
    - laravel-zero/framework v3.6.4 requires illuminate/console 5.5.* -> satisfiable by illuminate/console[v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28].
    - laravel-zero/framework v3.6.5 requires illuminate/console 5.5.* -> satisfiable by illuminate/console[v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28].
    - laravel-zero/framework v3.7.0 requires illuminate/console 5.5.* -> satisfiable by illuminate/console[v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28].
    - laravel-zero/framework v3.7.1 requires illuminate/console 5.5.* -> satisfiable by illuminate/console[v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28].
    - laravel-zero/framework v3.7.2 requires illuminate/console 5.5.* -> satisfiable by illuminate/console[v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28].
    - laravel-zero/framework v3.8.0 requires illuminate/console 5.5.* -> satisfiable by illuminate/console[v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28].
    - laravel-zero/framework v3.8.1 requires illuminate/console 5.5.* -> satisfiable by illuminate/console[v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28].
    - laravel-zero/framework v3.8.2 requires illuminate/console 5.5.* -> satisfiable by illuminate/console[v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28].
    - laravel-zero/framework v3.9.0 requires illuminate/console 5.5.* -> satisfiable by illuminate/console[v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28].
    - laravel-zero/framework v3.9.1 requires illuminate/console 5.5.* -> satisfiable by illuminate/console[v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28].
    - laravel-zero/framework v3.9.2 requires illuminate/console 5.5.* -> satisfiable by illuminate/console[v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28].
    - illuminate/console v5.5.0 requires symfony/console ~3.3 -> satisfiable by symfony/console[v3.3.0, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.14, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0, v3.4.1, v3.4.2].
    - illuminate/console v5.5.16 requires symfony/console ~3.3 -> satisfiable by symfony/console[v3.3.0, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.14, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0, v3.4.1, v3.4.2].
    - illuminate/console v5.5.17 requires symfony/console ~3.3 -> satisfiable by symfony/console[v3.3.0, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.14, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0, v3.4.1, v3.4.2].
    - illuminate/console v5.5.2 requires symfony/console ~3.3 -> satisfiable by symfony/console[v3.3.0, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.14, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0, v3.4.1, v3.4.2].
    - illuminate/console v5.5.28 requires symfony/console ~3.3 -> satisfiable by symfony/console[v3.3.0, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.14, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0, v3.4.1, v3.4.2].
    - Can only install one of: symfony/console[v3.3.0, v4.0.2].
    - Can only install one of: symfony/console[v3.3.1, v4.0.2].
    - Can only install one of: symfony/console[v3.3.10, v4.0.2].
    - Can only install one of: symfony/console[v3.3.11, v4.0.2].
    - Can only install one of: symfony/console[v3.3.12, v4.0.2].
    - Can only install one of: symfony/console[v3.3.13, v4.0.2].
    - Can only install one of: symfony/console[v3.3.14, v4.0.2].
    - Can only install one of: symfony/console[v3.3.2, v4.0.2].
    - Can only install one of: symfony/console[v3.3.3, v4.0.2].
    - Can only install one of: symfony/console[v3.3.4, v4.0.2].
    - Can only install one of: symfony/console[v3.3.5, v4.0.2].
    - Can only install one of: symfony/console[v3.3.6, v4.0.2].
    - Can only install one of: symfony/console[v3.3.7, v4.0.2].
    - Can only install one of: symfony/console[v3.3.8, v4.0.2].
    - Can only install one of: symfony/console[v3.3.9, v4.0.2].
    - Can only install one of: symfony/console[v3.4.0, v4.0.2].
    - Can only install one of: symfony/console[v3.4.1, v4.0.2].
    - Can only install one of: symfony/console[v3.4.2, v4.0.2].
    - Installation request for symfony/console (locked at v4.0.2) -> satisfiable by symfony/console[v4.0.2].


Installation failed, reverting ./composer.json to its original content.
```

**Comment by nunomaduro** [comment]
@bloggervista Please try this: `composer global require laravel-zero/installer --update-with-dependencies`.

If doesn't work please take a look on this issue: https://github.com/laravel-zero/laravel-zero/issues/89

**Comment by bloggervista** [comment]
no it says like this . I don't know what is happening :(
```

➜  projects composer global require laravel-zero/installer --update-with-dependencies
Changed current directory to /Users/shirshak/.composer
Using version ^1.1 for laravel-zero/installer
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install laravel-zero/installer v1.1.7
    - Conclusion: don't install laravel-zero/installer v1.1.6
    - Conclusion: don't install laravel-zero/installer v1.1.5
    - Conclusion: don't install laravel-zero/installer v1.1.4
    - Conclusion: don't install laravel-zero/installer v1.1.3
    - Conclusion: don't install laravel-zero/installer v1.1.2
    - Conclusion: don't install laravel-zero/installer v1.1.1
    - Conclusion: remove symfony/console v4.0.2
    - Installation request for laravel-zero/installer ^1.1 -> satisfiable by laravel-zero/installer[v1.1.0, v1.1.1, v1.1.2, v1.1.3, v1.1.4, v1.1.5, v1.1.6, v1.1.7].
    - Conclusion: don't install symfony/console v4.0.2
    - laravel-zero/installer v1.1.0 requires laravel-zero/framework ~3.6 -> satisfiable by laravel-zero/framework[v3.10.0, v3.6.0, v3.6.1, v3.6.10, v3.6.11, v3.6.12, v3.6.2, v3.6.3, v3.6.4, v3.6.5, v3.7.0, v3.7.1, v3.7.2, v3.8.0, v3.8.1, v3.8.2, v3.9.0, v3.9.1, v3.9.2].
    - laravel-zero/framework v3.10.0 requires illuminate/console 5.5.* -> satisfiable by illuminate/console[v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28].
    - laravel-zero/framework v3.6.0 requires illuminate/console 5.5.* -> satisfiable by illuminate/console[v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28].
    - laravel-zero/framework v3.6.1 requires illuminate/console 5.5.* -> satisfiable by illuminate/console[v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28].
    - laravel-zero/framework v3.6.10 requires illuminate/console 5.5.* -> satisfiable by illuminate/console[v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28].
    - laravel-zero/framework v3.6.11 requires illuminate/console 5.5.* -> satisfiable by illuminate/console[v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28].
    - laravel-zero/framework v3.6.12 requires illuminate/console 5.5.* -> satisfiable by illuminate/console[v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28].
```

**Comment by nunomaduro** [comment]
Please show me what you have installed globally with composer.

**Comment by bloggervista** [comment]
```
➜  projects composer global show -i
Changed current directory to /Users/shirshak/.composer
You are using the deprecated option "installed". Only installed packages are shown by default now. The --all option can be used to show all packages.
consolidation/cgr                  2.0.4              Safer alternative to 'composer global require'.
doctrine/instantiator              1.1.0              A small, lightweight utility to instantiate objects in PHP without invoking their constructors
guzzlehttp/guzzle                  6.3.0              Guzzle is a PHP HTTP client library
guzzlehttp/promises                v1.3.1             Guzzle promises library
guzzlehttp/psr7                    1.4.2              PSR-7 message implementation that also provides common utility methods
illuminate/container               v5.5.28            The Illuminate Container package.
illuminate/contracts               v5.5.28            The Illuminate Contracts package.
laravel/installer                  v1.5.0             Laravel application installer.
laravel/valet                      dev-master 5df7ed7 A more enjoyable local development experience for Mac.
mnapoli/silly                      1.7.0              Silly CLI micro-framework based on Symfony Console
myclabs/deep-copy                  1.7.0              Create deep copies (clones) of your objects
nategood/httpful                   0.2.20             A Readable, Chainable, REST friendly, PHP HTTP Client
phar-io/manifest                   1.0.1              Component for reading phar.io manifest information from a PHP Archive (PHAR)
phar-io/version                    1.0.1              Library for handling version information and constraints
php-di/invoker                     2.0.0              Generic and extensible callable invoker
phpdocumentor/reflection-common    1.0.1              Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock  4.2.0              With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that is embedded in a DocBlock.
phpdocumentor/type-resolver        0.4.0
phpspec/prophecy                   1.7.3              Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage          5.3.0              Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator          1.4.5              FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template          1.2.1              Simple template engine.
phpunit/php-timer                  1.0.9              Utility class for timing
phpunit/php-token-stream           2.0.2              Wrapper around PHP's tokenizer extension.
phpunit/phpunit                    6.5.5              The PHP Unit Testing framework.
phpunit/phpunit-mock-objects       5.0.5              Mock Object library for PHPUnit
psr/container                      1.0.0              Common Container Interface (PHP FIG PSR-11)
psr/http-message                   1.0.1              Common interface for HTTP messages
psr/simple-cache                   1.0.0              Common interfaces for simple caching
sebastian/code-unit-reverse-lookup 1.0.1              Looks up which function or method a line of code belongs to
sebastian/comparator               2.1.1              Provides the functionality to compare PHP values for equality
sebastian/diff                     2.0.1              Diff implementation
sebastian/environment              3.1.0              Provides functionality to handle HHVM/PHP environments
sebastian/exporter                 3.1.0              Provides the functionality to export PHP variables for visualization
sebastian/global-state             2.0.0              Snapshotting of global state
sebastian/object-enumerator        3.0.3              Traverses array structures and object graphs to enumerate all referenced objects
sebastian/object-reflector         1.1.1              Allows reflection of object attributes, including inherited and non-public ones
sebastian/recursion-context        3.0.0              Provides functionality to recursively process PHP variables
sebastian/resource-operations      1.0.0              Provides a list of PHP built-in functions that operate on resources
sebastian/version                  2.0.1              Library that helps with managing the version number of Git-hosted PHP projects
symfony/console                    v4.0.2             Symfony Console Component
symfony/filesystem                 v4.0.2             Symfony Filesystem Component
symfony/polyfill-mbstring          v1.6.0             Symfony polyfill for the Mbstring extension
symfony/process                    v4.0.2             Symfony Process Component
theseer/tokenizer                  1.1.0              A small library for converting tokenized PHP source code into XML and potentially other formats
tightenco/collect                  v5.5.27            Collect - Illuminate Collections as a separate package.
webmozart/assert                   1.2.0              Assertions to validate method input/output with nice error messages.
```

**Comment by bloggervista** [comment]
tried updating and clear caching also

```
➜  projects composer global update
Changed current directory to /Users/shirshak/.composer
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
```

it was problem with valet also don't know what is happening here.

**Comment by nunomaduro** [comment]
@bloggervista Laravel Zero installer is not compatible with symfony/console `v4.0.2`. What are you using that requires that version?

**Comment by bloggervista** [comment]
i don't know. May be laravel valet etc is using it? How do i fix it?

**Comment by bloggervista** [comment]
I guess i only installed phpunit, laravel installer and laravel valet i don't know what is creating prblem.

**Comment by nunomaduro** [comment]
@bloggervista No problem. We will find the issue. 

What is the OS that you are using?

**Comment by bloggervista** [comment]
Macbook Seirra

**Comment by nunomaduro** [comment]
@bloggervista Please show me that output of this command:

`cat ~/.composer/composer.json`

**Comment by bloggervista** [comment]
```
{
    "require": {
        "laravel/installer": "^1.5",
        "phpunit/phpunit": "^6.5",
        "consolidation/cgr": "^2.0",
        "laravel/valet": "dev-master"
    }
}
```

**Comment by nunomaduro** [comment]
Type:

1. `composer global remove laravel/installer`
2. `composer global remove laravel/valet `

3. `composer global require laravel-zero/installer `
4. `composer global require laravel/installer `
5. `composer global require laravel/valet `

**Comment by bloggervista** [comment]
so there is collision due to laravel valet. I removed laravel installer it didn't work and after removing valet it works. i don't if other version of valet will cause this problem

**Comment by nunomaduro** [comment]
@bloggervista Everything good now ? 🙂

**Comment by bloggervista** [comment]
@nunomaduro  yea its working perfectly thanks. I will now start working on console app . Thanks again

**Comment by drbyte** [comment]
Valet doesn't "need" symfony 4 components, but it doesn't reject installation if they are found. 
So, something else that was installed before valet may have pulled in the symfony 4 console component. Maybe because it's allowing "the most recent", and not prefer-oldest.

It's a matter of time before many other projects will update to be compatible with symfony 4 components. Hopefully laravel-zero will investigate allowing compatibility of the newer components via composer.json rules if there isn't actually a breaking change.

**Comment by nunomaduro** [comment]
@drbyte @bloggervista Just made a small addition to the Laravel Zero documentation where we recommend use tools like `cgr` to avoid this issue:

https://github.com/laravel-zero/website/commit/98759be23049f60690280e8631969fb64628cc0d

**Comment by Tamasneedhelp** [comment]
I have the same problem and I can't fix it

**Comment by bloggervista** [comment]
@Tamasneedhelp use cgr

**Comment by Tamasneedhelp** [comment]
not even that works

**Comment by nunomaduro** [comment]
@Tamasneedhelp Use: `composer create-project --prefer-dist laravel-zero/laravel-zero <your-app-name>`

**Comment by Tamasneedhelp** [comment]
what do you mean with your-app-name

**Comment by bloggervista** [comment]
replace <your...name> with whatever u want

**Comment by Tamasneedhelp** [comment]
if I type in: composer create-project --prefer-dist laravel-zero/laravel-zero <valet>
it says : -bash: syntax error near unexpected token `newline'

**Comment by Tamasneedhelp** [comment]
ok , I made it ,whats now

**Comment by Tamasneedhelp** [comment]
Could't rename: Folder or file already exists.

**Comment by Tamasneedhelp** [comment]
that is the last line after I typed in

**Comment by Tamasneedhelp** [comment]
should I rename it?

**Comment by Tamasneedhelp** [comment]
can it help me by larval/valet

**Comment by bloggervista** [comment]
bro what exactly is your problem?

**Comment by Tamasneedhelp** [comment]
composer global require laravel-zero/installer
Changed current directory to /Users/shirshak/.composer
Using version ^1.1 for laravel-zero/installer
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install laravel-zero/installer v1.1.7
    - Conclusion: don't install laravel-zero/installer v1.1.6
    - Conclusion: don't install laravel-zero/installer v1.1.5
    - Conclusion: don't install laravel-zero/installer v1.1.4
    - Conclusion: don't install laravel-zero/installer v1.1.3
    - Conclusion: don't install laravel-zero/installer v1.1.2
    - Conclusion: don't install laravel-zero/installer v1.1.1
    - Conclusion: remove symfony/console v4.0.2
    - Installation request for laravel-zero/installer ^1.1 -> satisfiable by laravel-zero/installer[v1.1.0, v1.1.1, v1.1.2, v1.1.3, v1.1.4, v1.1.5, v1.1.6, v1.1.7].
    - Conclusion: don't install symfony/console v4.0.2
    - laravel-zero/installer v1.1.0 requires laravel-zero/framework ~3.6 -> satisfiable by laravel-zero/framework[v3.10.0, v3.6.0, v3.6.1, v3.6.10, v3.6.11, v3.6.12, v3.6.2, v3.6.3, v3.6.4, v3.6.5, v3.7.0, v3.7.1, v3.7.2, v3.8.0, v3.8.1, v3.8.2, v3.9.0, v3.9.1, v3.9.2].
    - laravel-zero/framework v3.10.0 requires illuminate/console 5.5.* -> satisfiable by illuminate/console[v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28].
    - laravel-zero/framework v3.6.0 requires illuminate/console 5.5.* -> satisfiable by illuminate/console[v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28].
    - laravel-zero/framework v3.6.1 requires illuminate/console 5.5.* -> satisfiable by illuminate/console[v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28].
    - laravel-zero/framework v3.6.10 requires illuminate/console 5.5.* -> satisfiable by illuminate/console[v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28].
    - laravel-zero/framework v3.6.11 requires illuminate/console 5.5.* -> satisfiable by illuminate/console[v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28].
    - laravel-zero/framework v3.6.12 requires illuminate/console 5.5.* -> satisfiable by illuminate/console[v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28].
    - laravel-zero/framework v3.6.2 requires illuminate/console 5.5.* -> satisfiable by illuminate/console[v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28].
    - laravel-zero/framework v3.6.3 requires illuminate/console 5.5.* -> satisfiable by illuminate/console[v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28].
    - laravel-zero/framework v3.6.4 requires illuminate/console 5.5.* -> satisfiable by illuminate/console[v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28].
    - laravel-zero/framework v3.6.5 requires illuminate/console 5.5.* -> satisfiable by illuminate/console[v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28].
    - laravel-zero/framework v3.7.0 requires illuminate/console 5.5.* -> satisfiable by illuminate/console[v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28].
    - laravel-zero/framework v3.7.1 requires illuminate/console 5.5.* -> satisfiable by illuminate/console[v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28].
    - laravel-zero/framework v3.7.2 requires illuminate/console 5.5.* -> satisfiable by illuminate/console[v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28].
    - laravel-zero/framework v3.8.0 requires illuminate/console 5.5.* -> satisfiable by illuminate/console[v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28].
    - laravel-zero/framework v3.8.1 requires illuminate/console 5.5.* -> satisfiable by illuminate/console[v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28].
    - laravel-zero/framework v3.8.2 requires illuminate/console 5.5.* -> satisfiable by illuminate/console[v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28].
    - laravel-zero/framework v3.9.0 requires illuminate/console 5.5.* -> satisfiable by illuminate/console[v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28].
    - laravel-zero/framework v3.9.1 requires illuminate/console 5.5.* -> satisfiable by illuminate/console[v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28].
    - laravel-zero/framework v3.9.2 requires illuminate/console 5.5.* -> satisfiable by illuminate/console[v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28].
    - illuminate/console v5.5.0 requires symfony/console ~3.3 -> satisfiable by symfony/console[v3.3.0, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.14, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0, v3.4.1, v3.4.2].
    - illuminate/console v5.5.16 requires symfony/console ~3.3 -> satisfiable by symfony/console[v3.3.0, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.14, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0, v3.4.1, v3.4.2].
    - illuminate/console v5.5.17 requires symfony/console ~3.3 -> satisfiable by symfony/console[v3.3.0, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.14, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0, v3.4.1, v3.4.2].
    - illuminate/console v5.5.2 requires symfony/console ~3.3 -> satisfiable by symfony/console[v3.3.0, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.14, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0, v3.4.1, v3.4.2].
    - illuminate/console v5.5.28 requires symfony/console ~3.3 -> satisfiable by symfony/console[v3.3.0, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.14, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0, v3.4.1, v3.4.2].
    - Can only install one of: symfony/console[v3.3.0, v4.0.2].
    - Can only install one of: symfony/console[v3.3.1, v4.0.2].
    - Can only install one of: symfony/console[v3.3.10, v4.0.2].
    - Can only install one of: symfony/console[v3.3.11, v4.0.2].
    - Can only install one of: symfony/console[v3.3.12, v4.0.2].
    - Can only install one of: symfony/console[v3.3.13, v4.0.2].
    - Can only install one of: symfony/console[v3.3.14, v4.0.2].
    - Can only install one of: symfony/console[v3.3.2, v4.0.2].
    - Can only install one of: symfony/console[v3.3.3, v4.0.2].
    - Can only install one of: symfony/console[v3.3.4, v4.0.2].
    - Can only install one of: symfony/console[v3.3.5, v4.0.2].
    - Can only install one of: symfony/console[v3.3.6, v4.0.2].
    - Can only install one of: symfony/console[v3.3.7, v4.0.2].
    - Can only install one of: symfony/console[v3.3.8, v4.0.2].
    - Can only install one of: symfony/console[v3.3.9, v4.0.2].
    - Can only install one of: symfony/console[v3.4.0, v4.0.2].
    - Can only install one of: symfony/console[v3.4.1, v4.0.2].
    - Can only install one of: symfony/console[v3.4.2, v4.0.2].
    - Installation request for symfony/console (locked at v4.0.2) -> satisfiable by symfony/console[v4.0.2].


Installation failed, reverting ./composer.json to its original content.

**Comment by bloggervista** [comment]
have u added /usr/bin to your path. You can add it by editing .~/.bashrc

**Comment by Tamasneedhelp** [comment]
export PATH="$PATH:$HOME/.composer/vendor/bin"

**Comment by Tamasneedhelp** [comment]
thats what is in it

**Comment by bloggervista** [comment]
try `sudo valet`

and what is output of `which valet`

**Comment by Tamasneedhelp** [comment]
sudo: valet: command not found

**Comment by bloggervista** [comment]
my one will look like this 
`export PATH=$HOME/bin:/usr/local/bin:~/.composer/vendor/bin:/usr/local/sbin:$PATH`

**Comment by bloggervista** [comment]
try with that path and please reopen terminal are you from windows or osx or linux?

**Comment by Tamasneedhelp** [comment]
should I make
open .bashrc
the put this in .bashrc
:export PATH=$HOME/bin:/usr/local/bin:~/.composer/vendor/bin:/usr/local/sbin:$PATH

**Comment by Tamasneedhelp** [comment]
OSX

**Comment by bloggervista** [comment]
yea
type `vim ~/.bashrc` and add it there

`export PATH=$HOME/bin:/usr/local/bin:~/.composer/vendor/bin:/usr/local/sbin:$PATH`

After that restart terminal and try `valet install`

**Comment by Tamasneedhelp** [comment]
still not

**Comment by bloggervista** [comment]
ok then instead of chatting it here lets talk in email `bloggervista@gmail.com`

**Comment by Tamasneedhelp** [comment]
ok

**Comment by mfour-merickson** [comment]
Thank you!!!! My phone is going beserk with notifications and I can’t figure out how to mute this thread.
