### ISSUE TITLE
[Proposal] git tag as app version

### ISSUE THREAD

**Issue by MelonSmasher** [laravel-zero/laravel-zero#105]
It would be great if we could have the git tag or the commit hash or both as the application version. This would alleviate the need to update `config/app.php` when we have a new version.

**Comment by nunomaduro** [comment]
I see. I will take a look tomorrow!

**Comment by nunomaduro** [comment]
@MelonSmasher This will be included on Laravel Zero 5.6. 👍

**Comment by nunomaduro** [comment]
Available on Laravel Zero 5.6. 🎉

**Comment by foxted** [comment]
Hey @nunomaduro , any recommendations on using the git tag as a version when using packagist to install the build globally with composer? The issue that I run into is that the build is made before tagging, so the build end up having the previous tag as a version :/

**Comment by nunomaduro** [comment]
Hey @foxted can you create a new issue for that?
