### ISSUE TITLE
Option to disable `make:migration` in phar

### ISSUE THREAD

**Issue by MelonSmasher** [laravel-zero/laravel-zero#106]
It would be nice to be able to hide the `make:migration` command from the available commands in the compiled phar.

**Comment by nunomaduro** [comment]
Just confirmed. That's a bug. It will be fixed tomorrow!

**Comment by nunomaduro** [comment]
@MelonSmasher That issue should be fixed on the `v4.0.23`. Please perform:

`composer update laravel-zero/framework` and perform a new `app:build`.

**Comment by MelonSmasher** [comment]
Looks good!
