### ISSUE TITLE
Update to version 4.0.22/4.0.23 breaks app

### ISSUE THREAD

**Issue by ashleyhood** [laravel-zero/laravel-zero#107]
When I run:

    composer update laravel-zero/framework

and then try to run my app, I get the following error:

    ReflectionException  : Class LaravelZero\Framework\Commands\Component\Vlucas\Phpdotenv\Installer does not exist

I have cleared the `composer` cache, and ran `composer du`. I even deleted my `vendor` directory and `composer.lock` file before running `composer update` but still get the above error.

**Comment by nunomaduro** [comment]
@ashleyhood Your problem should be fixed on the version `v4.0.24`. Do you mind of performing a `composer update laravel-zero/framework`?
