### ISSUE TITLE
[Proposal] Modify output behavior; optional newlines and icons

### ISSUE THREAD

**Issue by philip** [laravel-zero/laravel-zero#108]
Applications are finding different ways to insert newlines into messages. The two ways I've seen thus far in real-world Laravel Zero apps:

```
$this->error("\nFoo\n");
```

```
$this->line('');
$this->error('Foo');
$this->line('');
```

Neither approach seems ideal. Could there be a better way? The following feels right:

```
$this->error('Foo');
```

Related and while we're here, what if we could also (optionally) enable icons for these? For example, maybe `info()` could be configured to prepend `(i)` or similar so these stand out a little more. For my use case, app output includes stdout from `Process` commands so prepending icons to Laravel Zero output could make it stand out a bit. 

All thoughts and idea improvements are welcome :)

**Comment by nunomaduro** [comment]
Thanks @Philip for this proposal. We can introduce the following features on Laravel Zero:

- Add blank line: I have proposed that modification on the laravel is core: https://github.com/laravel/framework/pull/22783

- Add icons to methods error(), info(), etc: I will think about this.

- Process: Would be useful add a new method called `$this->process(..)` ?

**Comment by philip** [comment]
I see that PR references `newLine()` although I still think it feels wrong to write this:

```
$this->newLine();
$this->error('Foo');
$this->newLine();
```

Instead of:
```
$this->error('Foo');
```
This request was hoping we could optionally automagically wrap output for these commands with newlines without having to add the extra clutter.

**Comment by nunomaduro** [comment]
@Philip What do you mean exactly about that? Because if I type:

```php
        $this->error('First error');
        $this->error('First error');
```

I will get:
<img width="100%" alt="screenshot 2018-01-19 20 45 14" src="https://user-images.githubusercontent.com/5457236/35168564-ac3f65b4-fd59-11e7-9166-0f795b53a7f1.png">

**Comment by philip** [comment]
@nunomaduro Some people want more whitespace. Here are two Laravel Zero applications in the wild that indicate this:

This wraps with `line('')`:
https://github.com/jeffochoa/twitter-cli/blob/master/app/Commands/Tweet.php#L63

This wraps with `\n`:
https://github.com/tightenco/lambo/blob/lampho/app/Commands/NewCommand.php#L96

**Comment by nunomaduro** [comment]
@Philip I understand your point of view. I am ok with the ->newLine option. Thanks anyway! 👍
