### ISSUE TITLE
[Question] How to pass all command line parameters

### ISSUE THREAD

**Issue by mikeerickson** [laravel-zero/laravel-zero#109]
Assuming I have the following

```bash
$ cli app:start -d -v -q

or

$ cli app:start -dvq
```

How can I setup the command to pass along the command line options

```
    ... signature ...
    protected $signature = 'app:start {-d: debug, -v: verbose, -q: quiet}';
```

**Comment by nunomaduro** [comment]
Hey @mikeerickson!

You should use the following signature:

```php
    /**
     * The name and signature of the command.
     *
     * @var string
     */
    protected $signature = 'hello {--d|debug} {--i|illuminate}';
```

Usage:

```php
    public function handle(): void
    {
        dd($this->option('debug'), $this->option('illuminate'));
    }
```


➜ **php application hello -d -i** or **php application hello -di**
```
/Users/nunomaduro/dev/laravel-zero/vendor/illuminate/support/Debug/Dumper.php:23:
bool(true)
/Users/nunomaduro/dev/laravel-zero/vendor/illuminate/support/Debug/Dumper.php:23:
bool(true)

```

Is this what you wanted? 🙂

**Comment by mikeerickson** [comment]
@nunomaduro sounds complete, I will give it a whirl after lunch and see how it works out :-)

**Comment by mikeerickson** [comment]
@nunomaduro I think to be clearer here, what i am looking to is grab ALL the parameters and options and pass them along to another routine.

```
$ cli app:start -it -rm -w /var/www/html app
```

Internally, I am going to pass the parameters/options onto docker, will be come

So I need to get everything after `app:start`

**Comment by nunomaduro** [comment]
@mikeerickson I am not getting your question. I am sorry. Can you try to explain in other words? Or code a small example on GitHub?

**Comment by mikeerickson** [comment]
I will give you more precise question tomorrow (out sick today). Sorry for confusion.

**Comment by mikeerickson** [comment]
OK, assuming I supply the following

```
$ ./m4-tools app:start -d -i -t -w /var/www/html
```

all arguments are optional, and can vary.  So how can I define signature to allow ANYTHING beyond command name, thus the optional params are

```
-d -i -t -w /var/www/html
```

or it could be

```
-dit -w /var/www/html
```

**Comment by mikeerickson** [comment]
Further, if I *must* define all the possible arguments, how can I mark each of them as optional, the following does not work (typical optional parameters using `=` symbol

```
    protected $signature = 'app:start {--d|debug=}';
```

**Comment by nunomaduro** [comment]
@mikeerickson I have coded an example for you: https://github.com/nunomaduro/example-issue-110

**Comment by mikeerickson** [comment]
That all makes sense, but does this mean I have to know about (and define) all possible parameters before they are even able to be passed.  Lets say the underlying command supports a new option, I must update my CLI tool to accommodate that update?

**Comment by nunomaduro** [comment]
@mikeerickson Yes. I am sorry.

I have tried and is too much hacking to make it work.

**Comment by mikeerickson** [comment]
Ahhhh gotcha!  Sorry it so long to get here :-)

**Comment by nunomaduro** [comment]
@mikeerickson No problem! Can I close this issue and the issue https://github.com/laravel-zero/laravel-zero/issues/110 ?

**Comment by mikeerickson** [comment]
One other question, is it possible to associate a value (ie as value to a key -w) ONLY if the option is supplied

```
-d -i -t -w /var/www/html
```

The value for -w should only be necessary if -w is supplied

**Comment by nunomaduro** [comment]
@mikeerickson You mean: Make the option `-w` non required, but if provided it can not be empty?

**Comment by mikeerickson** [comment]
@nunomaduro Exactly!

**Comment by nunomaduro** [comment]
@mikeerickson We don't have that functionally. You can always something like:

```php
if ($this->hasOption('xpto') && empty($this->getOption('xpto'))) {
    throw new InvalidArgumentException("The option xpto can't be empty");
}

```

**Comment by mfour-merickson** [comment]
But there is pre validation occurring before it gets to handle method. If I could disable validation, I could do that!?

Mike Erickson
Engineering Manager
Mfour Mobile Research
www.mfourdiy.com

**Comment by nunomaduro** [comment]
Ok. There is a option. It may be to heavy.

First. Create a new class that is a copy from **\Symfony\Component\Console\Input\ArgvInput**.

From that new class, remove the lines "throw new RuntimeException(sprintf('The "-%s" option does not exist.', $name[$i]));" and add lines to verify if the input is **not empty**.

Inject that new input on the app/bootstrap: (new LaravelZero\Framework\Application)->run(new InputMike);

**Comment by mikeerickson** [comment]
Awesome, now I see how you are thinking!  I will give it a whirl and let you know how i get on this.  I am going to close this puppy out as it is really quite the edge case (and special conditions)

**Comment by foxted** [comment]
Old issue but I thought this could help future visitors: 

I was trying to proxy a command via docker-compose via Laravel Zero. I have a Laravel Zero application (https://github.com/WhatDaFox/Harbor) that generates a docker-compose file tailored for Laravel. I need a way to call artisan via `docker-compose run` as when running Laravel in a Docker container, it is recommended to run artisan in the container instead of directly on your machine. 

So I needed a `harbor artisan` command that would proxy into `docker-compose run [...] php artisan [...]`. 

The first thing I had to do was to ignore validation errors: 

```php
public function __construct()
{
    parent::__construct();
    $this->ignoreValidationErrors();
}
```

Then access the original input, proxy it to docker-compose command and proxy the output:

```php
public function handle() {
    $command = $this->input->__toString();
    $output = [];

    exec("docker-compose run --rm -w /var/www/html app php {$command}", $output);

    $this->getOutput()->write(implode("\n", $output));
}
```

**Comment by nunomaduro** [comment]
@foxted You should use symfony process to get real time output from your `exec` result.

**Comment by foxted** [comment]
I was just looking for a way to do that 😆 Thanks! 🙏🏼
