### ISSUE TITLE
Issue with `BASE_PATH` when running tests inside PHPStorm

### ISSUE THREAD

**Issue by mikeerickson** [laravel-zero/laravel-zero#115]
Hey

I am running into the following error when attempting to run my tests while inside PHPStorm (all works fine from CLI)  Any chance you know of how I can get around this issue

![image](https://user-images.githubusercontent.com/183153/35477692-04f937fa-037e-11e8-9203-6443b0e29747.png)

**Comment by nunomaduro** [comment]
@mikeerickson Seems like of you have changed your `phpunit.xml`. Please show me your `phpunit.xml`.

**Comment by mikeerickson** [comment]
Here you go, the only thing added was the printer for my `PHPUnitPrettyResultPrinter` project.

```
<?xml version="1.0" encoding="UTF-8"?>
<phpunit backupGlobals="false"
         backupStaticAttributes="false"
         beStrictAboutTestsThatDoNotTestAnything="true"
         beStrictAboutOutputDuringTests="true"
         bootstrap="bootstrap/autoload.php"
         colors="true"
         convertErrorsToExceptions="true"
         convertNoticesToExceptions="true"
         convertWarningsToExceptions="true"
         failOnRisky="true"
         failOnWarning="true"
         processIsolation="false"
         printerClass="Codedungeon\PHPUnitPrettyResultPrinter\Printer"
         stopOnError="false"
         stopOnFailure="false"
         verbose="true"
>
    <testsuites>
        <testsuite name="Laravel Zero Test Suite">
            <directory suffix="Test.php">./tests/Integration</directory>
        </testsuite>
    </testsuites>
    <listeners>
        <listener class="NunoMaduro\Collision\Adapters\Phpunit\Listener"/>
    </listeners>
    <filter>
        <whitelist processUncoveredFilesFromWhitelist="true">
            <directory suffix=".php">./app</directory>
        </whitelist>
    </filter>
</phpunit>
```

**Comment by mikeerickson** [comment]
@nunomaduro I will share it later this evening or tomorrow morning (not w/ computer). Remember, it is ONLY an issue when using PHPStorm test runner, all is fine when running on CLI

**Comment by nunomaduro** [comment]
@mikeerickson I believe you didn't specify the correct autoload on your phpstorm configuration.

**Comment by mikeerickson** [comment]
peut-être! Je vais jeter un coup d'oeil ce soir

**Comment by mikeerickson** [comment]
@nunomaduro Nope, that was not the issue.  I have confirmed the correct `autoload.php` file is used AND I have recreated it for good measure 

```bash
$ composer dump-autoload
```
![image](https://user-images.githubusercontent.com/183153/35491506-bea63152-045b-11e8-90a7-e4898e10ac81.png)

**Comment by mikeerickson** [comment]
@nunomaduro And, as per your request from earlier, here is the contents of the `autoload.php` file

```php

<?php

// autoload.php @generated by Composer

require_once __DIR__ . '/composer/autoload_real.php';

return ComposerAutoloaderInit724bfcfa6019cb9dfe8d59d77392f010::getLoader();

```

**Comment by mikeerickson** [comment]
@nunomaduro Well, for argument sake, I decided to assign the alternate items (see screenshot) and now it is working as expected 

FWIW, I have not had to assign these objects in other projects, but not going to fret that now that things are working

![image](https://user-images.githubusercontent.com/183153/35491617-5eaedcee-045c-11e8-9e26-4c35e709f5b2.png)
