### ISSUE TITLE
Scheduler commands order

### ISSUE THREAD

**Issue by arall** [laravel-zero/laravel-zero#116]
Is there any way of defining the cron command order? For example, having two commands running every minute, define which one is going to be executed first.

**Comment by nunomaduro** [comment]
@arall Sure. Removed the schedule method from your commands. Then on your AppServiceProvider just put:

```
        $this->app[\Illuminate\Console\Scheduling\Schedule::class]->command(InspiringCommand::class)->everyMinute();
        $this->app[\Illuminate\Console\Scheduling\Schedule::class]->command(HelloCommand::class)->everyMinute();
```

Normally the InspiringCommand runs first.

**Comment by nunomaduro** [comment]
@arall Have news on this?
