### ISSUE TITLE
[5.7] Models and factories just work

### ISSUE THREAD

**Issue by jhoff** [laravel-zero/laravel-zero#124]
First, thanks for making Laravel Zero. It's been incredibly useful so far.

I feel like it's worth pointing out that when you install Eloquent, you get all of the functionality of models and factories that come with it. Maybe this is something worth mentioning in the docs.

Based on the docs, I assumed that when you installed eloquent you would only be able to use the DB facade, but was surprised when I tried making an Eloquent model and everything just worked.

Additionally, if you install fzaninotto/faker and create a database/factories folder, it'll parse anything in there, just like a standard Laravel project. Factories can then be used in tests as expected.

Again, thanks for putting this together!

**Comment by nunomaduro** [comment]
@jhoff I am glad that you enjoyed! 🏄‍♂️

Maybe you can make a PR modifying the `DatabaseInstallerCommand` on the branch `release-5.6.0`. Or just make me a todo list telling me what folders/class/modifications the `DatabaseInstallerCommand` need to make.

**Comment by nunomaduro** [comment]
@jhoff Got news on this?

**Comment by nunomaduro** [comment]
I am closing this due lack of activity.
