### ISSUE TITLE
[Question] Any recommended way to deal with user configs?

### ISSUE THREAD

**Issue by eklundkristoffer** [laravel-zero/laravel-zero#128]
Hi, I was just wondering if there is any recommended way to deal with user configs for the user to store mysql credentials etc. 

edit: I was trying to use `.env` but it seems like the application cant find the file once builded.

Great project so far!

Kind regards,
Kristoffer

**Comment by nunomaduro** [comment]
@eklundkristoffer Fixed on Laravel 5.6.

Can you wait a few days?

**Comment by eklundkristoffer** [comment]
@nunomaduro Oh nice. Yeah take your time, looking forward to it. Thanks.

**Comment by nunomaduro** [comment]
@eklundkristoffer Available on Laravel Zero 5.6. Test and tell me if everything is ok please.

**Comment by eklundkristoffer** [comment]
@nunomaduro now the content of `.env` is included in the bin file, but, how can the user set own env variables without having to build the app? I know you can do like `DB_DATABASE=123 php myapp` but just wondering if there is a easier/cleaner way to let the user set own config.

Thanks!

**Comment by nunomaduro** [comment]
@eklundkristoffer Not that I am aware, sorry.

**Comment by eklundkristoffer** [comment]
I see! If I ever figure out how to solve it I will make sure to post it here.

Thanks :)

**Comment by datashaman** [comment]
You could put the values into a JSON or YAML file and include a command-line parameter in your app like `--config myapp.json`.
