### ISSUE TITLE
Add option to remove own development commands

### ISSUE THREAD

**Issue by Neoscopia** [laravel-zero/laravel-zero#129]
Hi,
Thanks for your amazing job on LZ. I use your app to automate everything on my servers. I use to use bash but it's so much better with the addition of PHP.
I wanted to know if you can add an option to commands config file to hide my custom dev commands only on production.
Like the 'hidden' field but which remove commands on production.
Thanks you.

**Comment by nunomaduro** [comment]
The config files are php. So you can always do something like this:

```php

    /*
    |--------------------------------------------------------------------------
    | Remove Commands
    |--------------------------------------------------------------------------
    |
    | Do you have a service provider that loads a list of commands that
    | you don't need? No problem. Laravel Zero allows you to specify
    | bellow a list of commands that you don't to see in your app.
    |
    */
    'remove' => collect([Illuminate\Console\Scheduling\ScheduleRunCommand::class])->filter(function($command) {
        return app()->environment() === 'production';
    })->toArray(),


```

**Comment by Neoscopia** [comment]
I'm so stupid, I did not even think about that. I was doing a PR to add another filter in **LaravelZero\Framework\Kernel.php** but your way work like a charm, thanks you !

I post the code I use, if other people meet the same need as me
```php
    /*
    |--------------------------------------------------------------------------
    | Remove Commands
    |--------------------------------------------------------------------------
    |
    | Do you have a service provider that loads a list of commands that
    | you don't need? No problem. Laravel Zero allows you to specify
    | bellow a list of commands that you don't to see in your app.
    |
    */
    'remove' => array_merge([
        NunoMaduro\LaravelConsoleSummary\SummaryCommand::class,
        LaravelZero\Framework\Commands\App\CommandMaker::class,
    ], collect([
        App\Commands\System\MakeModule::class,
        App\Commands\System\DownloadModule::class,
        App\Commands\System\UpdateModule::class,
    ])->filter(function($command) {
        return app()->environment() === 'production';
    })->toArray()),
```

**Comment by kaleb14587** [comment]
I tried this, but for me i get a this error: PHP Fatal error: 
 Uncaught ReflectionException: Class env does not exist in /home/kaleb/PhpstormProjects/console-cluster/vendor/illuminate/container/Container.php:779

**Comment by kaleb14587** [comment]
believe this is part of the code : 
`app()->environment() === 'production'`

**Comment by nunomaduro** [comment]
Can you create a new issue?
