### ISSUE TITLE
[Tip] Using IDE Helper package with Laravel Zero

### ISSUE THREAD

**Issue by rohithmeethal** [laravel-zero/laravel-zero#132]
I think most of us are spoiled by the [Laravel ide-helper](https://github.com/barryvdh/laravel-ide-helper) package auto completions :smile: 
I was able to get it working with Laravel Zero by following this method,

Note: I had already enabled database package

```
composer require barryvdh/laravel-ide-helper 
composer require doctrine/dbal
composer require illuminate/view
```

Save this file to config directory https://raw.githubusercontent.com/laravel/laravel/master/config/view.php

On `config/app.php` providers add
```
\Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider::class,
\Illuminate\View\ViewServiceProvider::class
```

**Comment by nunomaduro** [comment]
Give me a few weeks to think about this 👍

**Comment by mikeerickson** [comment]
Weeks, that is an eternity!  How about days :-)

**Comment by pdifeo** [comment]
+1

**Comment by mikeerickson** [comment]
@nunomaduro Did you come up with your own solution here?  I am keep to apply the above installation, but figured I would check in with you before moving forward.

**Comment by nunomaduro** [comment]
@mikeerickson Taylor is adding to the Laravel framework a solution for this problem: https://github.com/laravel/framework/commit/40c80123e8c77594c022703d25c8eb727a3e8c59.

We just need to wait a few days.

**Comment by mikeerickson** [comment]
Sounds good

**Comment by nunomaduro** [comment]
@mikeerickson Most of facades have now type hinting right?

**Comment by mikeerickson** [comment]
@nunomaduro Ya, so far as I can see they are covered.

**Comment by nunomaduro** [comment]
Ok! I am closing this issue than! Thank you all!
