### ISSUE TITLE
Missing Laravel Zero 5.6 Upgrade Guide

### ISSUE THREAD

**Issue by mfour-merickson** [laravel-zero/laravel-zero#133]
Does a document exist outlining what is required to upgrade to Laravel Zero 5.6

I can surely go through the process and figure things out, just curious if a document already exists?  If not, I will forge forward and get it working (and document the process for those who may need in the future)

**Comment by mfour-merickson** [comment]
So, that was just too easy 👍 

1 . update `composer.json` 

```
   ...
    "require": {
        "php": ">=7.1.3",
        "laravel-zero/framework": "5.6.*",
        "illuminate/database": "5.6.*",
        "illuminate/log": "5.6.*",
        "laravel-zero/framework": "5.6.*"
  ...

    "require-dev": {
        "phpunit/phpunit": "~7",
        "symfony/thanks": "^1.0"
    },

```

2. rm -rf vendor

3. composer install

**Comment by mfour-merickson** [comment]
Well, I guess I forgot to remove the `composer.lock` file so it was just doing the old stuff

So, after removing the `composer.lock` it throws all sorts of errors?

Is this package still used (I dont see it in the composer.json file in the current repo)


```
        "laravel-zero/laravel-zero": "4.0",
```

**Comment by mikeerickson** [comment]
@nunomaduro Seeing as you have changed the title, does this mean you have an upgrade guide, or is still under development.  I had to abort my conversion the other night as I needed to continue working on the actual tool (it works with older version, but really want to stay current)

**Comment by nunomaduro** [comment]
This means that the upgrade guide is under development 👍

**Comment by nunomaduro** [comment]
@mfour-merickson @mikeerickson Laravel Zero 5.6 Upgrade Guide is now available. Please ping me if you find any issues!

Link: http://laravel-zero.com/#/upgrade

**Comment by nunomaduro** [comment]
@mfour-merickson @mikeerickson If you have any problems please ping me! Enjoy!

**Comment by mikeerickson** [comment]
@nunomaduro I will be trying the upgrade again this weekend, I will let you know.
