### ISSUE TITLE
Build command fails (on Windows)

### ISSUE THREAD

**Issue by wouter2203** [laravel-zero/laravel-zero#134]
The build command currently throws an exception (on Windows):

![image](https://user-images.githubusercontent.com/8761962/36792532-1cd7de4a-1c9b-11e8-8ca7-52cacceca8c8.png)

(`-v` did not give any info)

~~I'm not sure if this is only happening on Windows~~ It is only happening on Windows, and it's consistently broken for multiple projects.

The build itself is working fine after manually renaming the file.

I'll see if I can get some debugging done this weekend :)

**Comment by nunomaduro** [comment]
@wouter2203 Found something?

**Comment by wouter2203** [comment]
Yup, the compiler was keeping the file locked. I've opened up a pull request that fixes this probleem: https://github.com/laravel-zero/framework/pull/222

**Comment by nunomaduro** [comment]
Thanks!
