### ISSUE TITLE
Unzipping a zip file doesn't work once the app is build

### ISSUE THREAD

**Issue by jorenvh** [laravel-zero/laravel-zero#135]
Hi

In my app I'm downloading a zip file to the storage directory, later on I have to unzip it. This works when I run the command in my dev app. But once I build the app to a phar using the build command it throws an exception.

<img width="1233" alt="screen shot 2018-03-11 at 16 12 46" src="https://user-images.githubusercontent.com/8791625/37255062-25b43c52-2547-11e8-9381-e0c881f053f7.png">

Running it in development just works. Maybe **chumper/zipper** is not compatible?

Joren

**Comment by ashleyhood** [comment]
Nothing in the storage directory will work with out modification because the file path will begin with phar://
You will need to store any files you want to read/write to in a separate directory, or you could try passing in the full URL including _phar://_ to **chumper/zipper** methods.

**Comment by jorenvh** [comment]
@ashleyhood in which directory would you store these files?

**Comment by ashleyhood** [comment]
@jorenvh it depends on how you use your app.  I have a helper that defines the directory my app is in and then I store and additional files in the same directory as my app.

Add the file `app/helpers.php`:

    if (! function_exists('install_path')) {
        /**
         * Get the path to the base of the install.
         *
         * @return string
         */
        function install_path()
        {
            if (!empty($pharPath = Phar::running(false))) {
                return dirname($pharPath);
            } else {
                return app()->basePath();
            }
        }
    }

Autoload `app/helpers.php` in `composer.json`:

    "autoload": {
        "psr-4": {
            "App\\": "app/"
        },
        "files": [
            "app/helpers.php"
        ]
    },

**Comment by jorenvh** [comment]
Genius! I have some time over the weekend to test this, but thanks in advance for this. 

I will keep you updated on this.

**Comment by jorenvh** [comment]
@ashleyhood I tweaked it a little bit but I got it working now 👍 

```
/**
 * Get the path to the base of the install.
 *
 * @return string
 */
function install_path($path)
{
    if (!empty($pharPath = Phar::running(false))) {
        return dirname($pharPath) . '/' . $path;
    } else {
        return app()->basePath($path);
    }
}
```

**Comment by ashleyhood** [comment]
I'm using your tweak with the addition of setting a default for `$path`:

    function install_path($path = '')

**Comment by jorenvh** [comment]
Great enhancement, will add that for sure!
