### ISSUE TITLE
Can we make it work with php 7.0

### ISSUE THREAD

**Issue by makapaka23** [laravel-zero/laravel-zero#136]
I mistakenly built a whole console app with latest laravel-zero, but my servers are currently only php 7.0 and i'm unable to upgrade - is there a way to make it work with php 7.0?

Obviously I don't want to have to rebuild it some other way - I quite enjoyed using this framework

**Comment by nunomaduro** [comment]
@makapaka23 Unfortunately not. Laravel Zero is built on top of Laravel 5.6 witch requires `PHP >= 7.1.3`.

Sorry 😕
