### ISSUE TITLE
Never seen this before `phar.readonly` ...

### ISSUE THREAD

**Issue by mikeerickson** [laravel-zero/laravel-zero#139]
I am seeing a new error message when I attempt to execute my CLI in development mode.

```
Unable to compile a phar because of php's security settings. phar.readonly must be disabled in php.ini. 

You will need to edit /usr/local/etc/php/7.1/php.ini and add or set

    phar.readonly = Off

to continue. Details here: http://php.net/manual/en/phar.configuration.php
```

I can see what needs to be done here, but I don't recall ever having either updating this file, nor being required do this in the past?

**Comment by mikeerickson** [comment]
If this is something common, might want to add this to the documentation :-)

**Comment by nunomaduro** [comment]
By default, every php.ini haves the property `phar.readonly = Off`. In order to perform an `app:build` you need to set the property to `phar.readonly = On` in your php.ini.

I will add that to the docs. Thanks @mikeerickson!

**Comment by SahinU88** [comment]
Hi there,

just to avoid confusions, you have to set the `phar.readonly` value to `Off`.

Cheers,
Sahin

**Comment by nunomaduro** [comment]
@SahinU88 Just edited my response. Thanks men!
