### ISSUE TITLE
Conflicts with other globally installed packages

### ISSUE THREAD

**Issue by foxted** [laravel-zero/laravel-zero#140]
Hi there,

First of all, thanks for the initiative, this is awesome!

I built a quick CLI helper for my team, pushed it on Packagist and when I installed it globally using `composer global require`, it seems like LaravelZero dependencies conflict with other packages (like Laravel Valet).

Here is the error I get when I try to run valet or our tool when both are installed: 

```
PHP Fatal error:  Cannot redeclare info() (previously declared in /Users/valentinprugnaud/.composer/vendor/laravel-zero/foundation/src/Illuminate/Foundation/helpers.php:500) in /Users/valentinprugnaud/.composer/vendor/laravel/valet/cli/includes/helpers.php on line 24
```

**Comment by nunomaduro** [comment]
Hey @foxted! Thanks for considering Laravel Zero.

That's is a composer issue, not a Laravel Zero one. Anyway, you have 2 solutions:

1. Install your CLI helper globally using: https://github.com/consolidation/cgr
2. Only distribute the `build` version of your package, like I did on: https://github.com/laravel-zero/installer

**Comment by foxted** [comment]
I'll try this out, thank you for the suggestion :)
