### ISSUE TITLE
[Question] Can it send emails

### ISSUE THREAD

**Issue by Germanaz0** [laravel-zero/laravel-zero#142]
If I include the email facade, will it send emails ? or I have to install a third party library to do it ?

Sorry for the stupid question, but I was not sure.

**Comment by nunomaduro** [comment]
Nothing is a stupid question. That is a great question actually! 🙂

Here is the non tested solution:

1. `composer require illuminate\mail`
2. Add the `MailServiceProvider::class` to your `config/app.php`.
3. Create a new file called `config/mail.php` with those contents: https://github.com/laravel/laravel/blob/master/config/mail.php

Tell me if it works or not. I can also test it tonight!

**Comment by Germanaz0** [comment]
Hello, thanks for replaying so quick, the solution does not work properly because it works with the view service provider, it says that `Class view does not exist`.

If I try to add illuminate/view and add it to service providers, I am receiving an exception

**Comment by nunomaduro** [comment]
@Germanaz0 I will check that on the next couple hours.

**Comment by nunomaduro** [comment]
Hey @Germanaz0! I will probably make this a component on Laravel Zero 5.7. Meanwhile you can make it work on this way:

1. Include those packages:

```
        "illuminate/bus": "5.6.*",
        "illuminate/view": "5.6.*",
        "illuminate/mail": "5.6.*",
        "illuminate/queue": "5.6.*",
        "illuminate/translation": "5.6.*",
```

2. Add service the following services providers:

```
        Illuminate\Translation\TranslationServiceProvider::class,
        Illuminate\View\ViewServiceProvider::class,
        Illuminate\Mail\MailServiceProvider::class,
``

3. Create the folder `storage/framework/views`.
4. Create the file `config/mail.php` with the contents from [Laravel Mail Config](https://github.com/laravel/laravel/blob/master/config/mail.php).
5. Create the file `config/view.php` with the contents from [Laravel View Config](https://github.com/laravel/laravel/blob/master/config/view.php).

Tell me if it works on your side 👍

**Comment by nunomaduro** [comment]
@Germanaz0 Do you have news on this?

**Comment by Germanaz0** [comment]
Ups, @nunomaduro sorry, did not have the cahnce to test it, give me a couple of hours.

**Comment by nunomaduro** [comment]
@Germanaz0 I'll close this, you can contact me if you have any problems.

**Comment by Treggats** [comment]
@nunomaduro I can confirm that this works 👍

**Comment by mdurao** [comment]
Hello,

I've tested with @nunomaduro suggestion and it works very well in `development`.
But, after build the app for standalone, I get this error:

```
In MailServiceProvider.php line 102:

  Class 'Swift_Mailer' not found```

Any help on this? Thank you,

Miguel

**Comment by nunomaduro** [comment]
Thanks for reporting that issue, I would prefer you to create a new issue. Please also specify the content of `box.json`.

**Comment by magarrent** [comment]
Hey! I've just posted a Medium post to help you with that! This is currently working for Laravel Zero 10 :)

[https://medium.com/@magarrent/sending-emails-in-laravel-zero-10-f2daf9593142](https://medium.com/@magarrent/sending-emails-in-laravel-zero-10-f2daf9593142)

**Comment by german-bortoli** [comment]
Thank you so much for the help and support !
