### ISSUE TITLE
[Question] Where should icon go ?

### ISSUE THREAD

**Issue by kekebeen** [laravel-zero/laravel-zero#143]
Hello, I have a question regarding notify method. As documentation says 
https://laravel-zero.com/#/usage?id=desktop-notifications

Method can receive third param(icon). Where should I put icon(make folder, w/e) when using default laravel-zero installer boilerplate ?

**Comment by nunomaduro** [comment]
Hello 👋

You should create a `resources` and put the icon inside of it.

Than you can use the notify method on the following way:

```
$this->notify('Title', 'Descrption'', resource_path('icon.png'));
```

**Comment by kekebeen** [comment]
That's the way !

Thanks a lot :thumbsup:
