### ISSUE TITLE
default-command

### ISSUE THREAD

**Issue by djamesfar** [laravel-zero/laravel-zero#144]
I assumed that providing a 'default-command' value would run that command if no argument is provided.  I have only one command and would like it to run by default when program name is invoked without argument, ie 'php import', but it requires the command name as an argument, ie. 'php import members' (MembersCommand).
I'm having errors when running with the scheduler, which complains there are too many arguments.
My cron is * * * * * php <path/to/program>/import members schedule:run >> /dev/null 2>&1

In app.php, 'with-scheduler' is set to true.

When cron fires, I get this in log:
[2018-05-23 18:29:13] development.ERROR: Too many arguments, expected arguments "command". {"exception":"[object] (Symfony\\Component\\Console\\Exception\\RuntimeException(code: 0): Too many arguments, expected arguments \"command\". at /home/dj/PhpstormProjects/ArraySystems/SCGA/importClubs/vendor/symfony/console/Input/ArgvInput.php:182)

**Comment by nunomaduro** [comment]
Your cron is not correct.

You should use only `* * * * * <path/to/program>/import schedule:run >> /dev/null 2>&1`.

Your `MembersCommand` class should have the scheduler defined to everyMinute, or something like that. 👍

Tip: Which version of Laravel Zero are you using?

**Comment by nunomaduro** [comment]
Ping @djamesfar

**Comment by djamesfar** [comment]
@nunomaduro thanks, I set the 'default' value in commands.php to my command class, instead of setting the 'default-command' in config/app.php, which does not appear to do anything.
Thanks!

**Comment by djamesfar** [comment]
@nunomaduro , regarding your comment about my cron being incorrect, looks like you removed the 'php' command?  This is from your laravel-zero documentation:
```* * * * * php /path-to-your-project/your-app-name schedule:run >> /dev/null 2>&1```
...with the php.  Which is correct?
