### ISSUE TITLE
[5.7] Laravel Queue component

### ISSUE THREAD

**Issue by nerdalertdk** [laravel-zero/laravel-zero#146]
Hi, 

Any chance for an Queue packge or maybe an clue how to do it :)

**Comment by nunomaduro** [comment]
@nerdalertdk That would be great. You mean turn Laravel Zero into a very light queue worker?

**Comment by nerdalertdk** [comment]
Ye, I’m using the dusk package to do some automated work and it would be cool if I could off load it and run parallel dusk tasks :)

**Comment by nunomaduro** [comment]
That is actually a great idea. I am gonna dig this.

**Comment by nunomaduro** [comment]
@nerdalertdk For info: The version 5.7 contains this feature.

**Comment by nunomaduro** [comment]
@zOxta @pratham2003 Just released laravel Zero 5.7. Please create a new application or follow the upgrade guide [laravel-zero.com/#/upgrade?id=upgrading-to-57-from-56](https://laravel-zero.com/#/upgrade?id=upgrading-to-57-from-56) to enjoy that feature.

**Comment by deleugpn** [comment]
Not sure how to use this? Is it an add-on? Is there an installation for it?

**Comment by deleugpn** [comment]
Looks like running `php artisan app:install queue` will bring most of the things. It doesn't work with Redis, though, so you need to manually `composer require illuminate/redis` and then register the RedisServiceProvider
