### ISSUE TITLE
Bundle migrations with phar

### ISSUE THREAD

**Issue by hskrasek** [laravel-zero/laravel-zero#148]
As the title says, I was wondering if it is possible to bundle database migrations within the phar file when compiling it.

**Comment by nunomaduro** [comment]
@hskrasek Sure! On your `config/app.php` add the following lines:

```

    'structure' => [
        'app'.DIRECTORY_SEPARATOR,
        'bootstrap'.DIRECTORY_SEPARATOR,
        'vendor'.DIRECTORY_SEPARATOR,
        'config'.DIRECTORY_SEPARATOR,
        'composer.json',
        'builder-stub',
        'database'.DIRECTORY_SEPARATOR.'migrations'
    ],

```

Side-note: On Laravel Zero 5.7 the bundle feature will be way better! Get ready.

**Comment by hskrasek** [comment]
@nunomaduro Awesome that worked, thanks for the tip!
