### ISSUE TITLE
[Feature Request] Single File Packaging - PHAR Format

### ISSUE THREAD

**Issue by vzool** [laravel-zero/laravel-zero#149]
Hi,

I like your library it's wonderful, but when I'm thought about single file packaging, I remembered [PHAR](http://php.net/manual/en/intro.phar.php) format which is really nice and easy to distribute and verify.

Do you have any plans to add this feature?

Thanks

**Comment by nunomaduro** [comment]
@vzool We already have that. ☺️

Just type: `php <your-app-name> app:build`.
