### ISSUE TITLE
Not able to use Illuminate Validator Facade

### ISSUE THREAD

**Issue by aurawindsurfing** [laravel-zero/laravel-zero#150]
When I try to validate array in laravel-zero I always get the following:

```
In Container.php line 767:
Class validator does not exist
```

It is properly defined and imported into the command but for some reason, I can not use it to validate the input.

**Comment by nunomaduro** [comment]
Laravel Zero doesn't contains service provider auto discovery. You need to add the "ValidationServiceProvider" into your `config/app.php`.

**Comment by nunomaduro** [comment]
@aurawindsurfing You must include the illuminate/validation component doing: `composer require illuminate/validation`.  After that the class `Illuminate\Validation\ValidationServiceProvider::class` will be available.

**Comment by aurawindsurfing** [comment]
Thank you very much. I guess I'm going backward from using Laravel to actually trying to understand how it is actually working! It required additional TranslationServiceProvider and works now as expected.

**Comment by nunomaduro** [comment]
Ok! 👋
