### ISSUE TITLE
Include external dependeny

### ISSUE THREAD

**Issue by obstschale** [laravel-zero/laravel-zero#151]
I use Laravel Zero to build a simple CLI to access my Laravel App via REST. So far it looks good. Thx for this quick start with Laravel Zero 👏 

I have one question: I need to use a python tool as dependency. During development I downloaded this python program to local `bin` directory within my cli folder. I use `Process()` to run execute the program and it works. But when I use `app:build` to build the standalone version the python script is not included and I would like to ask you how would you solve this problem?

Can I include the python tool somehow to a single PHAR file? Or should I just leave it to the end user to make sure the dependency is installed? My cli tool chould check for its existence.

I love to hear your thoughts on this.

**Comment by digitalkreativ** [comment]
I have been experimenting with **Laravel-Zero** and so far I like it too :) .

I've run into the same issue as you, with wanting to add additional files to the phar file. Although mine are just stub files I wanted to be able to publish in the current working directory.

**What I did is the following:**
1. Created a new config file `build-custom.php` in which I added the extra directory I needed to include.
2. I created a new command `app:build-custom` which extends the `app:build` command to add those additional files I needed to the phar. Make sure you use the same additional arguments as the `app:build` command.

I made a gist of those files here:
https://gist.github.com/digitalkreativ/1220ede8bc14cc40a2af071fd532dad0

With that information I think you should be able to add that python file into your build process and create a command to install that python file to the right directory (if needed). 

Permissions on the file would most likely still need to be set to be able to execute it.

IMO, check if the dependency is installed first, and if it isn't give the option to install the version that you included in the phar with additional install information if needed and maybe a test run afterwards so you can check if it's installed properly.

**Note**
`__DIR__` doesn't work in phar files if you want to publish files of the phar file to an outside directory. Use `getcwd()`

**Comment by obstschale** [comment]
At the moment I have limited time to work on that side project. I bookmark this issue and come back to it if this does not work. I think till now you can close this issue. Thx

Thx @digitalkreativ for this answer.

**Comment by mikeerickson** [comment]
@nunomaduro This link (from above) is now a dead link

> https://github.com/laravel-zero/framework/blob/stable/src/Commands/App/Builder.php#L118

It should be pointing to 

> https://github.com/laravel-zero/website/blob/gh-pages/source/docs/build-a-standalone-application.md

and

> https://github.com/humbug/box/blob/master/doc/configuration.md#including-files
