### ISSUE TITLE
Any way to serve up a web page, even temporarily? (e.g. For an OAuth flow)

### ISSUE THREAD

**Issue by cbzink** [laravel-zero/laravel-zero#152]
Hey all,

Thank-you for your great work on Zero. It "_just works_"! I'm working on an application that requires an OAuth flow with another service, and I'm curious if anyone knows of any creative ways to temporarily serve up a single page to handle that OAuth flow.

Thanks!

**Comment by cbzink** [comment]
@nunomaduro the application is CLI-only, except for authenticating with the third party which has to be done via an embedded auth widget they provide.

**Comment by nunomaduro** [comment]
I see. You should use a Laravel application for that. I am sorry.
