### ISSUE TITLE
Can't rename app as it requires useless components

### ISSUE THREAD

**Issue by SergeyPodgornyy** [laravel-zero/laravel-zero#153]
Installation of `laravel-zero` crashes after running `php application rename`, as it tries to register `router` in application Container.

![image](https://user-images.githubusercontent.com/13667212/44576859-ef321980-a78f-11e8-83af-006cb0805954.png)

**Comment by SergeyPodgornyy** [comment]
Output from `~/.composer/composer.json` is:

```json
{
    "require": {
        "laravel-zero/installer": "^2.0",
        "laravel/installer": "^2.0"
    }
}
```

**Comment by nunomaduro** [comment]
I need the output from your `absence-cli/composer.json`.

**Comment by SergeyPodgornyy** [comment]
@nunomaduro 

```json
{
    "name": "laravel-zero/laravel-zero",
    "description": "The Laravel Zero Framework.",
    "keywords": ["framework", "laravel", "laravel zero", "console", "cli"],
    "homepage": "https://laravel-zero.com",
    "type": "project",
    "license": "MIT",
    "support": {
        "issues": "https://github.com/laravel-zero/laravel-zero/issues",
        "source": "https://github.com/laravel-zero/laravel-zero"
    },
    "authors": [
        {
            "name": "Nuno Maduro",
            "email": "enunomaduro@gmail.com"
        }
    ],
    "require": {
        "php": "^7.1.3",
        "laravel-zero/framework": "5.6.*"
    },
    "require-dev": {
        "phpunit/phpunit": "^7.1"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true,
        "platform": {
            "ext-posix": "0"
        }
    },
    "scripts": {
        "post-create-project-cmd": [
            "@php application app:rename"
        ]
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "bin": ["application"]
}
```

**Comment by nunomaduro** [comment]
This is super weird. That is a fresh application of Laravel Zero? Can I see the config/app.php?

**Comment by SergeyPodgornyy** [comment]
Just tried to install it on another machine. On Ubuntu 14.04 it works well :heavy_check_mark: 
After I run `composer global require "laravel-zero/installer"` I have:

```bash
$ cat ~/.composer/composer.json 
{
    "require": {
        "laravel/installer": "^1.3",
        "fxp/composer-asset-plugin": "~1.1.1",
        "laravel-zero/installer": "^2.0"
    }
}
```

**Comment by nunomaduro** [comment]
So all it’s good right? If yes, can you close this issue?

**Comment by SergeyPodgornyy** [comment]
@nunomaduro yes, for me it works fine right now, but actually core problem was not found by myself, so probably someone else could also face with this problem.

**Comment by nunomaduro** [comment]
I am closing this due lack of activity.

**Comment by mvanduijker** [comment]
I am having the same issue here on our servers. In my homestead box it works just fine.

Both my box and my server running ubuntu 18.04.1 with php 7.2.

Getting the error when creating fresh project with:

```
composer create-project --prefer-dist laravel-zero/laravel-zero cli
```

![image](https://user-images.githubusercontent.com/1771206/51307886-14763b80-1a41-11e9-8344-f481e499ebc4.png)

**Comment by nunomaduro** [comment]
@mvanduijker Can you create a new issue?

**Comment by mvanduijker** [comment]
@nunomaduro for sure

**Comment by nunomaduro** [comment]
Thanks!
