### ISSUE TITLE
The stream or file could not be opened log file

### ISSUE THREAD

**Issue by imajinyun** [laravel-zero/laravel-zero#160]
Execute command after compilation:

```bash
In StreamHandler.php line 107:

  The stream or file "phar:///path/to/builds/xxx-cli/storage/logs/laravel.log" cou
  ld not be opened: failed to open stream: phar error: open mode append not supported
```

**Comment by nunomaduro** [comment]
Consider updating your log driver to: `stderr`. Tell me if works.

**Comment by djamesfar** [comment]
same problem after creating standalone application:
storage/logs/laravel-2019-04-17.log" could not be opened: failed to open stream: phar error: open mode append not supported

**Comment by djamesfar** [comment]
@nunomaduro I have confirmed that it works if I change the log driver to 'stderr' as you suggested

**Comment by nunomaduro** [comment]
GreaT.

**Comment by jankremlacek** [comment]
that's happening because once phar built the `storage_path()` method points into the phar package.

@djamesfar, @imajinyun just change your `/config/logging.php` `path` value on your desired driver.

**Comment by imajinyun** [comment]
@jankremlacek Thanks

**Comment by nunomaduro** [comment]
@jankremlacek @imajinyun Don't hesitate to update the docs. https://github.com/laravel-zero/website

**Comment by djamesfar** [comment]
@jankremlacek I set the logging path as an env value (dotenv), and put the full production path there before building.  That worked - Thanks!
