### ISSUE TITLE
Fatal Error On Windows Using Menu

### ISSUE THREAD

**Issue by funkvn** [laravel-zero/laravel-zero#161]
Hi!

I'm playing around with the menu example form the documentation.
But I run into an fatal error:

```
$ php test-app inspiring
Simplicity is the ultimate sophistication.

   Symfony\Component\Debug\Exception\FatalThrowableError  : Call to undefined function PhpSchool\Terminal\IO\posix_isatty()

  at C:\Users\user\test-app\vendor\php-school\terminal\src\IO\ResourceInputStream.php:45
    41|      * Whether the stream is connected to an interactive terminal
    42|      */
    43|     public function isInteractive() : bool
    44|     {
  > 45|         return posix_isatty($this->stream);
    46|     }
    47| }
    48|

  Exception trace:

  1   PhpSchool\Terminal\IO\ResourceInputStream::isInteractive()
      C:\Users\user\test-app\vendor\php-school\terminal\src\UnixTerminal.php:169

  2   PhpSchool\Terminal\UnixTerminal::isInteractive()
      C:\Users\user\test-app\vendor\php-school\cli-menu\src\CliMenu.php:130

  Please use the argument -v to see more details.
```
Prefixing the command with `winpty` does not change anything. 
And I got the same error in PowerShell.

Regarding to http://php.net/manual/en/intro.posix.php this is expectable.

Are there any work-arounds or other example to get the menu working on windows?
The description implies that: "Supports interactive menus and desktop notifications on Linux, Windows & MacOS."

Thanks in advance
&nbsp;&nbsp;Valentin

**Comment by nunomaduro** [comment]
@funkvn Unfortunately `menus` only work while using the bash console of Windows.
