### ISSUE TITLE
CLI ASCII Logo

### ISSUE THREAD

**Issue by ivancelot** [laravel-zero/laravel-zero#163]
It would be amazing to be able to put an ascii logo

**Comment by victorlap** [comment]
Hi, 

I would love to implement this, but I am asking for some advice.

It is probably best to use a package like [`povils/figlet`](https://github.com/povils/figlet) to handle the ascii art generation. However, would you like this to be included by default, with default settings and the possibility of publishing a config file ? I would like to be sure that something would be merged before I dedicate any time on this.

**Comment by nunomaduro** [comment]
@victorlap I component would be better.

**Comment by nunomaduro** [comment]
@victorlap You can check on the current framework code to see how components are coded.

**Comment by victorlap** [comment]
@nunomaduro Check, Will look into it, thanks for the quick replies!

**Comment by ivancelot** [comment]
good, may be image file to cli ascii logo? it's just a suggestion. Thanks for your work.

**Comment by nunomaduro** [comment]
@ivancelot This component already got added into the core. Check the docs: https://laravel-zero.com/#/usage?id=logo
