### ISSUE TITLE
Env config cache question

### ISSUE THREAD

**Issue by nroussis** [laravel-zero/laravel-zero#164]
Hello, 
Excuse my naiveness and if reposting previous question. After I have made some changes in the env files I see that have not been applied. I suspect some kind of config cache? Can I clear it since commands php artisan cache:clear and php artisan config:clear are not there?.. Thank you for the great laravel version! Zero is exactly what I need.

**Comment by nroussis** [comment]
I am using 5.7
this is my  composer.json file

{
    "name": "laravel-zero/laravel-zero",
    "description": "The Laravel Zero Framework.",
    "keywords": ["framework", "laravel", "laravel zero", "console", "cli"],
    "homepage": "https://laravel-zero.com",
    "type": "project",
    "license": "MIT",
    "support": {
        "issues": "https://github.com/laravel-zero/laravel-zero/issues",
        "source": "https://github.com/laravel-zero/laravel-zero"
    },
    "authors": [
        {
            "name": "Nuno Maduro",
            "email": "enunomaduro@gmail.com"
        }
    ],
    "require": {
        "php": "^7.1.3",
        "guzzlehttp/guzzle": "6.3.3",
        "illuminate/bus": "5.7.*",
        "illuminate/config": "5.7.*",
        "illuminate/contracts": "5.7.*",
        "illuminate/database": "5.7.*",
        "illuminate/log": "5.7.*",
        "illuminate/mail": "5.7.*",
        "illuminate/queue": "5.7.*",
        "illuminate/translation": "5.7.*",
        "illuminate/view": "5.7.*",
        "laravel-zero/framework": "5.7.*",
        "padosoft/laravel-affiliate-network": "^2.6",
        "vlucas/phpdotenv": "^2.5"
    },
    "require-dev": {
        "mockery/mockery": "^1.0",
        "phpunit/phpunit": "^7.3"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true,
        "platform": {
            "ext-posix": "0"
        }
    },
    "scripts": {
        "post-create-project-cmd": [
            "@php application app:rename"
        ]
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "bin": ["apopou-cli"]
}

**Comment by nunomaduro** [comment]
@nroussis You probably are doing something wrong. Please try to create your project from a fresh Laravel Zero application and check if the bug still exists.

**Comment by nunomaduro** [comment]
@nroussis I am closing this, it seems don't be a framework issue.
