### ISSUE TITLE
App after build, stops working. Works OK in development.

### ISSUE THREAD

**Issue by mdurao** [laravel-zero/laravel-zero#165]
Hi,

using this suggestion in the issues:

https://github.com/laravel-zero/laravel-zero/issues/142#issuecomment-384432351

I was able to create a small app to send emails in the console.
In development mode, everything works OK.

After building the app and moving the phar to the `/usr/local/bin`, the app starts spitting an error:

```
In MailServiceProvider.php line 102:

  Class 'Swift_Mailer' not found
```

Any help would be nice.

Here is the `box.json`:

```
{
    "chmod": "0755",
    "directories": [
        "app",
        "bootstrap",
        "config",
        "vendor"
    ],
    "files": [
        "composer.json"
    ],
    "exclude-composer-files": false,
    "compression": "GZ",
    "compactors": [
        "Herrera\\Box\\Compactor\\Php",
        "Herrera\\Box\\Compactor\\Json"
    ]
}
```

**Comment by nunomaduro** [comment]
Can you open source your app? I would like to put my hands on it.

**Comment by mdurao** [comment]
Sure.

https://github.com/mdurao/mailer

Thxs

**Comment by nunomaduro** [comment]
@mdurao Do you mind of performing a `composer update laravel-zero/framework`, build again, and test?

**Comment by mdurao** [comment]
@nunomaduro It worked, thxs!
