### ISSUE TITLE
Symfony\Component\Console\[Input\InputInterface|Output\OutputInterface] are not resolved.

### ISSUE THREAD

**Issue by ssi-anik** [laravel-zero/laravel-zero#166]
What should be the workaround if I want to get the instances for the `Symfony\Component\Console\Input\InputInterface` or Symfony\Component\Console\Output\OutputInterface`.

I want to use `SymfonyStyle` class which expects the implementations of those interfaces. Why using what I can get the concrete classes of those interfaces? 
Sorry for asking this type of vague question.

**Comment by nunomaduro** [comment]
@ssi-anik Can you provide a description?

**Comment by ssi-anik** [comment]
Updated.

**Comment by nunomaduro** [comment]
On the command class you just have to do this:

```
$this->output->success('The success text');
```

`$this->output` is an instance of `SymfonyStyle`.

**Comment by ssi-anik** [comment]
Uh, I see. Thanks man <3
