### ISSUE TITLE
.env after app:build

### ISSUE THREAD

**Issue by mdurao** [laravel-zero/laravel-zero#167]
Not sure if I'm doing something wrong but in my project I have a `.env` to save the mail credentials used. I fetch those vars in `config` to use them.

In develop mode, works OK.
After building, app doesn't load up from `.env`.

Should the `.env` be "compiled" in the binary in order for the app to find the credentials?
It's not my intention to change them after the build is done.
In the other hand, I don't want to save credentials in the repos.

How can I workaround this?

**Comment by nroussis** [comment]
i'm wondering is this similar to #164 ?

**Comment by mdurao** [comment]
Not sure... #164 is about Caching the `.env`... My problem is just using the `.env` after building the binary.

**Comment by nunomaduro** [comment]
@mdurao Why you don't use normal enviroment variables of your OS?

**Comment by mdurao** [comment]
I could use the environment variables of the OS, but I was trying to use the binary "out-of-the-box" without extra configuration!

**Comment by nunomaduro** [comment]
You mean that those credentials are not secret?

**Comment by mdurao** [comment]
Thinking better, you are right, the proper way is to use OS environment variables.
So, for instance, if you want to use the app, you just need to setup your OS environment variables.
More portable that way!

Ty
