### ISSUE TITLE
How to build using current tag

### ISSUE THREAD

**Issue by foxted** [laravel-zero/laravel-zero#170]
Hey @nunomaduro , any recommendations on using the git tag as a version when using packagist to install the build globally with composer? The issue that I run into is that the build is made before tagging, so the build end up having the previous tag as a version :/

**Comment by nunomaduro** [comment]
You can always hard code the version value on the config itself. At the moment, I don't have a solution for this.

**Comment by foxted** [comment]
I found a loophole: 

- Create the tag in git locally
- Build the app
- Delete the tag
- Recreate the tag in git
- Push

**Comment by nunomaduro** [comment]
That is a nice workaround. Let's keep this issue open while we find a clean solution for this.

**Comment by nunomaduro** [comment]
This issue has been fixed on Laravel Zero 5.8.
