### ISSUE TITLE
framework exceptions & illuminate/log

### ISSUE THREAD

**Issue by Broutard** [laravel-zero/laravel-zero#171]
With `illuminate/log` loaded, a missing command argument produce (even in production) :

```
[2018-11-27 13:18:15] development.ERROR: Not enough arguments (missing: "database"). {"exception":"[object] (Symfony\\Component\\Console\\Exception\\RuntimeException(code: 0): Not enough arguments (missing: \"database\"). at /var/www/www2/wbcmd/vendor/symfony/console/Input/Input.php:76)
[stacktrace]
#0 /var/www/www2/wbcmd/vendor/symfony/console/Command/Command.php(250): Symfony\\Component\\Console\\Input\\Input->validate()
#1 /var/www/www2/wbcmd/vendor/illuminate/console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#2 /var/www/www2/wbcmd/vendor/symfony/console/Application.php(893): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#3 /var/www/www2/wbcmd/vendor/symfony/console/Application.php(262): Symfony\\Component\\Console\\Application->doRunCommand(Object(App\\Commands\\Db\\Restore), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#4 /var/www/www2/wbcmd/vendor/symfony/console/Application.php(145): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#5 /var/www/www2/wbcmd/vendor/illuminate/console/Application.php(89): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#6 /var/www/www2/wbcmd/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#7 /var/www/www2/wbcmd/vendor/laravel-zero/framework/src/Kernel.php(76): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#8 /var/www/www2/wbcmd/wbcmd(37): LaravelZero\\Framework\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#9 {main}
"}


  Not enough arguments (missing: "database").

```

without `illuminate/log` loaded, it produce only
```
  Not enough arguments (missing: "database").
```

Is there a way to handle this kind of error ? (be able to log into my commands but not the framework exceptions).

**Comment by nunomaduro** [comment]
Sorry buddy, you will have to detail your problem better.

Can you re-phrase it?

**Comment by Broutard** [comment]
Ok, sorry.

After adding `illuminate/log` with composer, when I run a command without passing the required argument, an exception occured in `vendor/symfony/console/Command/Command.php` and the stacktrace is dumped into stderr (the default stack in my config/logging.php config file).

It's not a problem in development but it's not very clean in production.

Is there a way to handle the framework exceptions in production ?

**Comment by nunomaduro** [comment]
@Broutard Change the log `driver` is not a solution?

**Comment by Broutard** [comment]
And if I want to be able to use `Log::error($message)` in my command ?

Maybe you should add an [exception handler](https://github.com/laravel/laravel/blob/master/app/Exceptions/Handler.php) to choose the kind of exception to render.

**Comment by Broutard** [comment]
I want to log error (with syslog for example) in production, if an error occured in my commands... but not if any user miss to pass an argument.

**Comment by nunomaduro** [comment]
@Broutard You may have to implement your own exception handler, to not report those exceptions.

**Comment by digitalkreativ** [comment]
@Broutard this seemed like a good issue for me to find out how to do it. 

I got a basic implementation up and running. I can get it up on github, if you need it.

I will also probably write an article on my blog for this soon. One of my new years resolutions was to start writing more so this seems like a good start :)

@nunomaduro if needed I can add some basic info on how to write your own ExceptionHandler to the docs.

**Comment by digitalkreativ** [comment]
@nunomaduro the basic info on that shouldn't be to hard to write up, so no problem.

Where do you want it in the menu structure? Inside the **Usage** menu I assume?

**Comment by nunomaduro** [comment]
@digitalkreativ Just propose a pull request. We work from that.

Probably inside a new topic called "The Exception Handler" - where you explain that laravel zero uses one by default on the core, but you can override it blabla.

**Comment by digitalkreativ** [comment]
@Broutard the latest documentation should help you solve your problem.

https://laravel-zero.com/docs/exception-handler/

If you get stuck somewhere in the documentation let me know and I'll see if I can help you and update documentation if necessary.
