### ISSUE TITLE
Posix extension blocks installation on Windows

### ISSUE THREAD

**Issue by sarthaksavvy** [laravel-zero/laravel-zero#173]
I have created a CLI named packer with zero.  [https://github.com/bitfumes/laravel-packer](url)

It is working awesome in macOS, but when I installed it on windows via composer I have this error.

![error](https://user-images.githubusercontent.com/41295276/49634828-d8a08d00-fa23-11e8-8f99-505f622822df.jpg)

I have googled it and found that posix is a php extension which is not available on windows, so how to remove it or how to deal with this issue.

Thanks

**Comment by nunomaduro** [comment]
Thanks for reporting this issue. Normally this line should have been the fix for that https://github.com/bitfumes/laravel-packer/blob/8da3e74aee11de1b4af94d5df5a9a5fd53513ece/composer.json#L41:
```json
"platform": {
    "ext-posix": "0"
}
```

I need to investigate this.

**Comment by nunomaduro** [comment]
@sarthaksavvy Can you try this: `composer global require bitfumes/laravel-packer --prefer-dist --ignore-platform-reqs ext-posix`?

**Comment by marc-pages-onclick** [comment]
> @sarthaksavvy Can you try this: `composer global require bitfumes/laravel-packer --prefer-dist --ignore-platform-reqs ext-posix`?

Not working for me. I've the same issue when running on Windows.

`* The package "php-school/terminal" requires the extension "posix". Enable it
  or install a polyfill.`

**Comment by nunomaduro** [comment]
This was been fixed on the next version of Laravel Zero.

**Comment by LarBearrr** [comment]
@nunomaduro How did you get around this? I'm starting to experiment with Laravel Vapor and we are restricted to Windows environments. I submitted a help ticket on Vapor, but I was curious what your solution was?

**Comment by rafamrs** [comment]
I still have this problem, everything was working on OSX, but now on windows I get posix error, with the latest version. Just installed it, so it must be the latest.

![image](https://user-images.githubusercontent.com/924985/72916379-3a17de00-3d42-11ea-80ba-7869c12f6140.png)

**Comment by yoramdelangen** [comment]
I still have this issue when I have build an application and try to run it on a windows machine.

**Comment by zeevx** [comment]
I am having this issue, please how can I solve it?

**Comment by owenvoke** [comment]
@zayedadel, the menu component is not compatible with Windows. There's not much we can do about this as it relies on POSIX functionality.
