### ISSUE TITLE
Exit code

### ISSUE THREAD

**Issue by Broutard** [laravel-zero/laravel-zero#174]
If an exception is thrown in a command, the exit code remain 0.

Any errors should exit with an exit code > 0.

Step to reproduce:
```
public function handle()
{
    throw new \Exception();
}  
```
In my bash, `echo $?` is `0`

**Comment by nunomaduro** [comment]
That's weird, thanks for reporting this.

**Comment by nunomaduro** [comment]
This issue has been fixed on the version `v5.7.14`. Can you run a quick test on it?

**Comment by Broutard** [comment]
Fixed.
Thanks a lot.
