### ISSUE TITLE
app:build timeouts at 60 seconds

### ISSUE THREAD

**Issue by zecipriano** [laravel-zero/laravel-zero#176]
The `Symfony\Component\Process\Process` object created in `BuildCommand` has a default timeout of 60 seconds.

On my laptop, both on Homestead and the windows linux subsystem, that is not enough.

I would make a pull request but I'm not sure the better way to fix it. Instantiate `Process` with a bigger timeout, `null` to disable the timeout or make it somehow configurable and leave it to the user?

**Comment by nunomaduro** [comment]
@zecipriano Thanks for reporting this. Can you perform a Pull Request with an increased timeout, and probably an new optional argument for the definition of the timeout?

**Comment by zecipriano** [comment]
@Broutard Agreed, but I think that should be a separate issue.

**Comment by nunomaduro** [comment]
Thanks @zecipriano for this.

**Comment by nunomaduro** [comment]
@Broutard Could you create an issue/pr for the `fromShellCommandline` issue?
