### ISSUE TITLE
[5.8] Assert that command was called

### ISSUE THREAD

**Issue by sandervanhooft** [laravel-zero/laravel-zero#178]
(Moved from #99)

Would be great to have an easy way of asserting that a specific command was called.

The use case is that I have a command A, which cascades into command B and command C. Command B and Command C are already covered in other tests, but I want to make sure that when I call command A, command B and command C are called as well.

After doing a quick scan, I can think of three directions currently:

1. Inspired by `Event::fake()`, wrap `Illuminate\Command` in a spy when using `Command:spy` helper. Then use a `assertCommandCalled($command, ?$callback)` test helper for asserting. It seems impossible to me to go a level deeper because then we get into Symphony territory. (The Event::fake() solution doesn't use a Mockery spy, but mimics its functionality anyway).

2. Add lifecycle Events to the Command calls ([like Eloquent model has](https://laravel.com/docs/5.7/eloquent#events)) and track these using `Event::fake()` and `Event::assertDispatched(...)`

3. Do both. But that's a bit much atm.

What do you think?

**Comment by sandervanhooft** [comment]
Here's an helpful post by Freek van den Herten: https://murze.be/handcrafting-mocks .

But what class should be we swapping? @nunomaduro do you know what class is actually invoking the command? Is it the Zero Kernel? If so, what method?

**Comment by sandervanhooft** [comment]
(The Event architecture seems to use a separate Dispatcher class, not sure about the Console commands)

**Comment by nunomaduro** [comment]
Taking holidays until next week. I will get back to you soon as possible.

**Comment by sandervanhooft** [comment]
Getting closer...

I was able to swap the `Illuminate\Contracts\Console\Kernel` and track the command calls made. But it seemed not all calls are triggered through here.

Appears when triggering `call(...)` from a Command (based on `Illuminate\Console\Command`), directly resolves the target command, bypassing the `Kernel` altogether.

**Comment by sandervanhooft** [comment]
So I'll probably have to swap some `BaseCommand` class as well.

**Comment by sandervanhooft** [comment]
> Taking holidays until next week. I will get back to you soon as possible.
> […](#)

Enjoy! ☀️

If you don't mind I log any progress here in the meantime. 😊

**Comment by sandervanhooft** [comment]
I created here https://github.com/laravel/ideas/issues/1449 because I think it's currently harder to implement this than it should be. (Currently need to swap out 2 classes instead of 1)

**Comment by sandervanhooft** [comment]
For now it's best to

- swap both `Illuminate\Foundation\Console\Kernel` and `Illuminate\Console\Command` for handcrafted mocks.
- define `assertCommandCalled` on `TestCase`, which checks both mocks calls.

**Comment by sandervanhooft** [comment]
@nunomaduro I have been able to do all except for swapping out `LaravelZero\Framework\Commands\Command` during tests.

Any suggestion how to do this?

**Comment by nunomaduro** [comment]
@sandervanhooft Thanks for all your work on this. Some questions:

What you exacly mean by a `swap? The `swaps` where done where exacly? Maybe just do a Pull Request with your work to give me a better idea on that.

**Comment by sandervanhooft** [comment]
Hi @nunomaduro ,

I am first building this feature in a local project, will happily extract a PR for Zero Framework after that.

With swapping I mean replacing the normal class with a wrapper that records the command calls made. I am able to do this for all necessary classes, except for the `LaravelZero\Framework\Commands\Command` class.

I think it's currently not being resolved via the container?

Besides I think it would be wise to resolve it via the container anyway, there's also an interesting workaround that coincides with another feature I have been working on in my project: the ability to record calls and rewind, so you can track history and use a method like `$command->back()`.

I am heavily relying on menu's chained together, so a `back` method would be great as well.

Both `assertCommandCalled` and the `back` method are relying on recording the command calls made.

**Comment by sandervanhooft** [comment]
So instead of swapping `LaravelZero\Framework\Commands\Command` I could also add the required functionality to that Command class itself.

**Comment by nunomaduro** [comment]
@sandervanhooft I see. Let's work on this together. Since I understood, you need to `swap` the `LaravelZero\Framework\Commands\Command` because people are calling another commands using the `call` method right?

**Comment by sandervanhooft** [comment]
Yes that's the class I need to swap.

**Comment by sandervanhooft** [comment]
It's also not in `laravel-zero/framework/src/Bootstrap/RegisterFacades.php`, so it's not available as a Facade

**Comment by nunomaduro** [comment]
Since you are mocking the `Kernel.php`, why you don't decorate all commands instead? Could you perform a Pull Request with your current code?

**Comment by sandervanhooft** [comment]
In a minute 😄

**Comment by sandervanhooft** [comment]
Done. It's probably not what you're looking for right now, but I hope it clarifies the direction I'm thinking of.

(Tests are failing on an unrelated issue)

**Comment by nunomaduro** [comment]
Thanks for the Pull Request, I will work on that and get back to you ok? Working in some docs today :)

**Comment by sandervanhooft** [comment]
Sure thing!

I've not used any mocks/swaps but worked directly on the source classes, because I think I'll need the recording functionality for implementing the `back()` method as well.

**Comment by nunomaduro** [comment]
@sandervanhooft No worries, currently working the new website for Laravel Zero: https://github.com/laravel-zero/website/tree/feat/v2.

**Comment by nunomaduro** [comment]
This feature was been added.
