### ISSUE TITLE
Please provide an example app, thanks!

### ISSUE THREAD

**Issue by wowcut** [laravel-zero/laravel-zero#180]
Could you please provide an example app? I read the docs and still can not manage to start with your code - much too abstract - I just need to build a quick cli tool - it would be really nice to see a full fledged example app that implements all features - much easier to learn from that.

I am sure it is possible to use this wonderful library without having to study Laravel concepts for three months, but it would be helpful to have a working example as a starting point. 

Thanks!

**Comment by nunomaduro** [comment]
@wowcut Check this youtube video: https://www.youtube.com/watch?v=6H5eCphgqVc.

**Comment by nunomaduro** [comment]
Some other resources: https://github.com/laravel-zero/awesome-laravel-zero

**Comment by wowcut** [comment]
I have seen the youtube - these minimal examples do not help, sorry, but the awesome link might bring up something to study, thank you very much for the quick reaction! You should put that on the frontpage!

**Comment by wowcut** [comment]
I would like to learn how to organize menus and code, how to reuse code, how to build reliabe error handling and logging. A __real__ app. 

Is there something in Laravel Zero that helps me to build / organize / structure the menu system or do I have to invent that?

**Comment by nunomaduro** [comment]
@wowcut I would like to work on me on improving the documentation? Unfortunately today, Laravel Zero is kind off for people that already know Laravel.

**Comment by wowcut** [comment]
OK, I figured it out, at least the most important parts to get it do what I want it to do. I read the docs of the PhpSchool class and some more about Laravel. I still do not understand everything about how this wrapper exactly works and why it is needed at all and why I can not use the PhpSchool classes directly with Laravel, but this is some research work to be done in the future. BTW I really liked the in-depth articles by [Alan Storm](https://alanstorm.com/category/laravel/) - I believe it would be extremely helpful if you made a similar tutorial with line-by-line explanations of this integration work you have done - I would buy that!

Regarding the docs, at some point I was stuck because I did not understand why the original usage [instructions](https://github.com/php-school/cli-menu#usage) from the PhpSchool docs do not work, e.g. the code below does not work when copy pasted into a `Commands/Example.php` file into `$this-handle()` - of course this is very obvious if you are deep into Laravel internals and I am laughing about myself _now_  - but it would be a great help for starters to explain the integration into Laravel and the mapping of classes and why and how names change, so it is easier to draw conclusions from the source and translate the original instructions to the Laravel world. Just a few sentences that give some short explanation would be a great help, just to enable the possibility of better self-help.

Thanks again for your attention and your great work! Peaceful holidays!

Example below from the original PhpSchool repo - this would make a good article... like 
_"Why this example code does not work and how to translate classes into the Laravel Zero integration - a short introduction to make you better understand the internals of Laravel classes so you can translate examples yourself"_ ... of course the maximum version of this would be a 1:1 translation of the original examples and how to use them in your Laravel integration. 
```php
<?php

use PhpSchool\CliMenu\CliMenu;
use PhpSchool\CliMenu\Builder\CliMenuBuilder;

require_once(__DIR__ . '/../vendor/autoload.php');

$itemCallable = function (CliMenu $menu) {
    echo $menu->getSelectedItem()->getText();
};

$menu = (new CliMenuBuilder)
    ->setTitle('Basic CLI Menu')
    ->addItem('First Item', $itemCallable)
    ->addItem('Second Item', $itemCallable)
    ->addItem('Third Item', $itemCallable)
    ->addLineBreak('-')
    ->setBorder(1, 2, 'yellow')
    ->setPadding(2, 4)
    ->setMarginAuto()
    ->build();

$menu->open();
```

One more BTW: Can this integration be made in a way that these examples _just work_? If not, why not? I have the suspicion that Laravels tools for meta programming should allow to make the usage 100% compatible to the original PhpSchool classes... I would like that very much, so code could also be reused outside of the Laravel world... I mean this is what classes are meant to be, aren´t they?

**Comment by nunomaduro** [comment]
Thanks for your words @wowcut. I am working on the new documentation website that hopefully will be better starting point for developers that didn't interact with Laravel before.

Feel free to take a look:
```
git clone https://github.com/laravel-zero/website
cd website
git checkout feat/v2
```

Let's make sure you fully understood how Laravel Zero works behind the scenes before you write something about it. Please give me your feedback about the new docs, it may be unstable.
