### ISSUE TITLE
[5.8] Why does folder bootstrap exist? Let's consider remove it.

### ISSUE THREAD

**Issue by wowcut** [laravel-zero/laravel-zero#182]
Ok, I think I figured it out, at least the parts I need... :) 

However, some questions remain, especially regarding the file structure. One is: 
_Why does the `bootstrap/` folder exist?_ I do not understand that. 
From what I see everything that is in `bootstrap/app.php` could also go into the command file, like in the example below. It seems to work, at least I had no problems, but what am I missing? Is there some behind-the-scenes abstraction thing going on that will break if that folder does not exist? 

Yes, I am kind of pedantic about the directory structure of an app :) I think `app, config, tests, vendor` is enough... I will not die if `bootstrap` is totally needed for some reason, but then please tell me what that reason is. 

Thank you very much for your attention, I wish you lovely holidays!

Example console command with everything from `bootstrap/app.php`:
```php
#!/usr/bin/env php
<?php

define('LARAVEL_START', microtime(true));

/*
|--------------------------------------------------------------------------
| Register The Auto Loader
|--------------------------------------------------------------------------
|
| Composer provides a convenient, automatically generated class loader
| for our application. We just need to utilize it! We'll require it
| into the script here so that we do not have to worry about the
| loading of any our classes "manually". Feels great to relax.
|
*/

$autoloader = require file_exists(__DIR__.'/vendor/autoload.php') ?
	__DIR__.'/vendor/autoload.php' : __DIR__.'/../../autoload.php';

// $app = require_once __DIR__.'/bootstrap/app.php';

/*
|--------------------------------------------------------------------------
| Create The Application
|--------------------------------------------------------------------------
|
| The first thing we will do is create a new Laravel application instance
| which serves as the "glue" for all the components of Laravel, and is
| the IoC container for the system binding all of the various parts.
|
*/

$app = new LaravelZero\Framework\Application(dirname(__FILE__));

/*
|--------------------------------------------------------------------------
| Bind Important Interfaces
|--------------------------------------------------------------------------
|
| Next, we need to bind some important interfaces into the container so
| we will be able to resolve them when needed. The kernels serve the
| incoming requests to this application from both the web and CLI.
|
*/

$app->singleton(
    Illuminate\Contracts\Console\Kernel::class,
    LaravelZero\Framework\Kernel::class
);

$app->singleton(
    Illuminate\Contracts\Debug\ExceptionHandler::class,
    Illuminate\Foundation\Exceptions\Handler::class
);

/*
|--------------------------------------------------------------------------
| Run The Artisan Application
|--------------------------------------------------------------------------
|
| When we run the console application, the current CLI command will be
| executed in this console and the response sent back to a terminal
| or another output device for the developers. Here goes nothing!
|
*/

$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);

$status = $kernel->handle(
    $input = new Symfony\Component\Console\Input\ArgvInput,
    new Symfony\Component\Console\Output\ConsoleOutput
);

/*
|--------------------------------------------------------------------------
| Shutdown The Application
|--------------------------------------------------------------------------
|
| Once Artisan has finished running, we will fire off the shutdown events
| so that any final work may be done by the application before we shut
| down the process. This is the last thing to happen to the request.
|
*/

$kernel->terminate($input, $status);

exit($status);

```

**Comment by nunomaduro** [comment]
@wowcut The bootstrap directory contains files that bootstrap the framework and configure autoloading. This directory also houses a cache directory which contains framework generated files for performance optimization such as services cache files.

Service cache files are not used anymore since version `v5.7`, let's consider remove this for the next major version.

**Comment by wowcut** [comment]
Nuno, do you have a reference for this?

> Service cache files are not used anymore since version v5.7

I could not find any hints about that, the [Laravel 5.7 release notes](https://laravel.com/docs/5.7/releases#laravel-5.7) do not mention service cache.

**Comment by nunomaduro** [comment]
Service cache are not used in **Laravel Zero**. The core of Laravel Zero is different from Laravel's core.

**Comment by wowcut** [comment]
Ah, ok, so Laravel Zero 5.7... ok. BTW it woud be great to have a few sentences about what is different and, more importantly as we all can read diffs, _why_ these changes exist. Thanks and have a nice day!

**Comment by nunomaduro** [comment]
@wowcut You welcome! Thanks for the feedback.

Please don't hesitate and contribute for the new documentation website. To setup the documention website just perform the following steps locally:

```
git clone http://github.com/laravel-zero/website
cd website
git checkout feat/v2
```

_Be sure to stay tuned to my twitter account [@enunomaduro](http://twitter.com/enunomaduro) for more information about this package. Are you enjoying this package? Please tweet the link [https://github.com/laravel-zero/laravel-zero](https://github.com/laravel-zero/laravel-zero) and tells us your favourite feature!_ 🚀
