### ISSUE TITLE
Dotenv loader failing

### ISSUE THREAD

**Issue by gdecris** [laravel-zero/laravel-zero#186]
After running ```php <app-name> app:install dotenv``` getting an error loading the .env

```Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Argument 1 passed to Dotenv\Dotenv::__construct() must be an instance of Dotenv\Loader, string given, called in .../vendor/laravel-zero/foundation/src/Illuminate/Foundation/Bootstrap/LoadEnvironmentVariables.php```

Am I missing a step? I did not see anything else in the docs. It looks like the dotenv library is expecting an object in its constructor but receiving a path (string).

**Comment by gdecris** [comment]
I figured it out. I had a newer version of dotenv installed. SIgnature was changed. Not sure if I did that or the app:install just installed an incompatible version.

**Comment by nunomaduro** [comment]
This issue was being fixed on the latest version of Laravel Zero. Can you update it using `composer update laravel-zero`.

**Comment by gdecris** [comment]
I just installed ~2.2 of dotenv to resolve the issue. Thanks for the quick reply!
