### ISSUE TITLE
Laravel Zero 5.8 Features

### ISSUE THREAD

**Issue by nunomaduro** [laravel-zero/laravel-zero#190]
- We are going to focus on the Windows environment
- phar builds with a self-update command
- phpunit 8

**Comment by mikeerickson** [comment]
@nunomaduro Hey bud

Have any of the above items been addressed, or do you still need help?

I am working on a new secret CLI and will be using this framework, so I will be hitting against all of these issues at some point during development.

**Comment by mikeerickson** [comment]
@nunomaduro First, I will be hitting against `PHPUnit 8` as it will be used heavily during development (seeing as I TDD all the things) so I can surely aid in this portion.

**Comment by nunomaduro** [comment]
Laravel Zero 5.8 it's released. It's all done.

**Comment by nunomaduro** [comment]
cc @mikeerickson
