### ISSUE TITLE
Which repo contains documentation

### ISSUE THREAD

**Issue by mikeerickson** [laravel-zero/laravel-zero#192]
@nunomaduro Hey bud, which repo contains the website documentation?  I would like to add a section to describe how 3rd Party libraries should be registered, etc.  If it already exists, I could not locate it

I know it was easy enough to simply add to `config/app.php` for Laravel supported packages, but also want to include some information about using non-laravel packages.

**Comment by nunomaduro** [comment]
Thank you!

This is the website: https://github.com/laravel-zero/website
