### ISSUE TITLE
PHP Version issues

### ISSUE THREAD

**Issue by alrik11es** [laravel-zero/laravel-zero#195]
Based on #23 issue I want to open this issue. Is not about 5.6 but 7.0 or future. Well my reasoning is the following:

Stable branch on Debian only supports PHP 7.0 right now. That's also true for every other architecture that Debian supports like ARM or whatever. My point is that this kind of library should be at least usable on the latest stable version of Debian.

**Why I say all this?**
I'm trying to develop an application for raspberry pi and the actual raspbian stable PHP version is 7.0.*
Said that, there aren't any compilation of PHP latest versions on ondrej repository for ARM. Of course I'm going to try to compile PHP 7.1 or later for ARM, but it's going to be hours compiling since my raspberry is one of the first models. Update: My raspberry have not enough memory to compile so I'm going to try to do cross compiling...

**So what I'm meaning with this issue?**
Is it possible to be Debian PHP stable version aware as minimun requirement for this library after Debian Buster release?

I guess that Debian Buster will have as stable the PHP 7.1 version.

BTW: This library is amazing keep up the good work.

**Comment by nunomaduro** [comment]
Sorry buddy,

There is nothing I can do. Mainly because Laravel 5.8 no longer supports PHP 7.0.

**Comment by alrik11es** [comment]
@nunomaduro I understand that you're pinned to what Laravel do related PHP version.

Thanks for taking your time to look into my issue.

Still compiling PHP 7.3.3 on Raspberry Pi from yesterday after enabling swap :cry:, cross compiling yet another option but too complex to try after burning all my cards on Raspbian.
