### ISSUE TITLE
[Proposal] Add support for `descriptionHelp` (to document arguments)

### ISSUE THREAD

**Issue by mikeerickson** [laravel-zero/laravel-zero#196]
@nunomaduro Hey there, have a feature request which I am in need of and I am sure at least one other user would like it as well :-)

Add a new property to the various command classes `$descriptionHelp` which will be displayed whenever help is requested for the desired command.

```bash

$ <app> <cmd> --help

Description:
  <cmd>

Arguments:
  --name              Command name option (required)
  --arg, -a           Alternate argument one [default: ./xxx]
  --case, -c          Desired name case (lowercase, Title Case, UPPERCASE) [default lowercase]
  --plural, -p        Pluralize name

Options:
....

```

To me, this will look more viusally appealing than using the existing `$description` property and will be more consistent with other CLIs (including Artisan)   The `$description` property is typically more for the quick single line description.

If you are keen to accepting, I can add it while I am working on my new CLI and submit as PR accordingly

**Comment by nunomaduro** [comment]
Proposal accepted.

You can start working in a pull request. We probably need to rename `descriptionHelp` to `summary` and put the summary bellow the description:

```
$ <app> <cmd> --help

Description:
  <cmd>

Summary:
  <cmd>

Arguments:
  --name              Command name option (required)
  --arg, -a           Alternate argument one [default: ./xxx]
  --case, -c          Desired name case (lowercase, Title Case, UPPERCASE) [default lowercase]
  --plural, -p        Pluralize name

Options:

```

**Comment by mikeerickson** [comment]
@nunomaduro just to let you know,  i will be getting started on this soon.  Just needed to get `laravel-craftsman` out the door.

**Comment by linuxjuggler** [comment]
May I ask why you don't you use `Symfony/Console` configure function which provides a simple way to `setHelp` message, which can be more than one line and more descriptive than the description or summary?

using `setHelp` you will be able to show something like:

```
    protected function configure()
    {
        parent::configure();
        $this->setHelp('You know this is a help'. PHP_EOL .'And this is another line');
    }
```

Will produce this:


```
Description:
  my command description

Usage:
  cmd:signature

Options:
  -h, --help            Display this help message
  -q, --quiet           Do not output any message
  -V, --version         Display this application version
      --ansi            Force ANSI output
      --no-ansi         Disable ANSI output
  -n, --no-interaction  Do not ask any interactive question
      --env[=ENV]       The environment the command should run under
  -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Help:
  You know this is a help
  And this is another line
```

**Comment by matt-allan** [comment]
I just made [a PR](https://github.com/laravel/framework/pull/28437) to Laravel to accept the `help` property by default.  Zero could make a similar change if we wanted to add support before the next major Laravel release.  In the interim I'm just overriding my constructor like this:

```php
    public function __construct()
    {
        parent::__construct();

        $this->setHelp($this->help);
    }
```

Symfony's help property does not show up when you run `php myapp list` but does show up when you run `php myapp my:command --help`.  It seems like the only difference between the `help` and the proposed `summary` is the name and if it shows up either before or after the arguments and options?

**Comment by matt-allan** [comment]
The PR was accepted upstream but it won't be available until 5.9.

**Comment by mikeerickson** [comment]
Fair enough, I have already integrated this using the `setHelp` in the constructor

**Comment by nunomaduro** [comment]
@matt-allan This can be closed?

**Comment by matt-allan** [comment]
yeah, we don't really need to anything here.

**Comment by nunomaduro** [comment]
Thanks buddy.
