### ISSUE TITLE
Desktop notifications are not working

### ISSUE THREAD

**Issue by svallamsetti** [laravel-zero/laravel-zero#198]
`$this->notify('test', 'test')` is not dispalying any notifications.

**Comment by nunomaduro** [comment]
What is your OS?

**Comment by svallamsetti** [comment]
> What is your OS?

macOS Mojave, Application is running under
 Operating System: CentOS Linux 7 (Core)
 CPE OS Name: cpe:/o:centos:centos:7
 Kernel: Linux 3.10.0-957.1.3.el7.x86_64

**Comment by nunomaduro** [comment]
@svallamsetti Can you report your bug here please? https://github.com/jolicode/JoliNotif
