### ISSUE TITLE
[Proposal] List schedule Command

### ISSUE THREAD

**Issue by billysmithers** [laravel-zero/laravel-zero#199]
Hello

Love the application. Thanks for building it.

I have a proposal of a command that lists the schedules as a table consisting of command signature, crontab, next run date and previous run date. Also potentially if you run in verbose mode add the description of the command.

I could provide a PR if you think this is a good idea.

Keep up the good work.

Billy

**Comment by nunomaduro** [comment]
It's seems a good idea, have your tried to propose it to the core of Laravel first?

**Comment by billysmithers** [comment]
That is a good call.

I will add a proposal to the core and post a link.

**Comment by billysmithers** [comment]
There is already a proposal - https://github.com/laravel/ideas/issues/1320 - as yet no movement on this though. However the proposal suggests building into the core something like this package - https://github.com/hmazter/laravel-schedule-list.

However this would be another dependency pulled into Laravel Zero.

What do you think?

**Comment by nunomaduro** [comment]
It's fine if you make it as a new component. Here is an example: https://github.com/laravel-zero/framework/commit/287f97356fc044596494251358414011a5442b33.

**Comment by billysmithers** [comment]
Thanks @nunomaduro - I will take a look at making it a component.

**Comment by billysmithers** [comment]
Hello @nunomaduro .

I have finally managed to find some time to add this as a component.

I have a branch ready to create a pull request would I do this against the framework repository?

If so do I need to be a contributor?

**Comment by nunomaduro** [comment]
You just need a fork the laravel-zero/framework, and do a normal pull request.

**Comment by billysmithers** [comment]
@nunomaduro Thanks

**Comment by billysmithers** [comment]
@nunomaduro - I have created a PR - hope you like it - https://github.com/laravel-zero/framework/pull/351

**Comment by billysmithers** [comment]
@nunomaduro - I have updated the PR, any chance of re-review please.

**Comment by pxgamer** [comment]
Merged and implemented in v6.2.0! :tada: Thanks @billysmithers.
