### ISSUE TITLE
[Question] Is it planned to create a mail component

### ISSUE THREAD

**Issue by Max13** [laravel-zero/laravel-zero#201]
The title says it all. I wanted to know if it's planned.

I'm on `5.8.*`, and I can't work it around like described in #142 .

Thx

(This question isn't about how to make it work, it's about the roadmap).

**Comment by nunomaduro** [comment]
At the moment: No.

**Comment by nunomaduro** [comment]
Fell free to propose buddy @mikeerickson.

**Comment by mikeerickson** [comment]
Don’t mind if I do @ nunomaduro

**Comment by mikeerickson** [comment]
> The title says it all. I wanted to know if it's planned.
> 
> I'm on `5.8.*`, and I can't work it around like described in #142 .
> 
> Thx
> 
> (This question isn't about how to make it work, it's about the roadmap).

@Max13 When tried the above-mentioned solution with Laravel-Zero 5.8?

Does it work in either case (development or build)

**Comment by Max13** [comment]
> @Max13 When tried the above-mentioned solution with Laravel-Zero 5.8?

Nope.

Here is how I call the mailable: `Mail::to($abuse->emails->toArray())->send(new ReportingAbuse($abuse));`

`ReportingAbuse::build()`:

```php
return $this->view('emails.abuse.report')
                    ->with([
                        'hostname' => gethostname()
                    ])
                    ->attach($this->abuse->logfile);
```

Error:

```
Symfony\Component\Debug\Exception\FatalThrowableError  : Argument 2 passed to Illuminate\View\FileViewFinder::__construct() must be of the type array, null given, called in /Users/adnan/Downloads/secretary/vendor/illuminate/view/ViewServiceProvider.php on line 77
```

**Comment by lzomedia** [comment]
3 hours spent on streeming how to build an mail bomber using laravel zero, :) 
Laravel zero , it's like you can do that :) 
Pls kill me now :))
