### ISSUE TITLE
Debugging Laravel Zero app using xDebug

### ISSUE THREAD

**Issue by mikeerickson** [laravel-zero/laravel-zero#204]
Has anybody been able to use xDebug w/ PHPStorm to debug Laravel Zero apps?  

I have been beating my keyboard for hours trying to get this working.

If anybody has been successful, what did you do to make it work?

**Comment by mikeerickson** [comment]
And just like that, I figured it out (finally)  I should have posted this message hours ago, I guess that is all that was needed for me to figure it out.

**Comment by nunomaduro** [comment]
@mikeerickson Thanks.

**Comment by Wulfheart** [comment]
Ok. But how did you do this?
