### ISSUE TITLE
`Class filesystem does not exist` in Test class tearDown method

### ISSUE THREAD

**Issue by godbout** [laravel-zero/laravel-zero#209]
Using `Laravel Zero v2.2.0`.

Here's a basic Command Class:

```php
class GrabCommandTest extends TestCase
{
    public function tearDown(): void
    {
        parent::tearDown();

        Storage::deleteDirectory('tailwindcss/next.tailwindcss.com');
    }

    /** @test */
    public function the_command_requires_a_docset_name_as_argument()
    {
        $this->expectException(RuntimeException::class);
        $this->expectExceptionMessage('Not enough arguments (missing: "docs").');

        $this->artisan('grab');
    }
}
```

I was using `setUp` at first and it worked fine. I'm changing it to `tearDown` and I'm having now the following issue:

```php
1) Tests\Feature\GrabCommandTest::the_command_requires_a_docset_name_as_argument
  ReflectionException: Class filesystem does not exist

/Users/guill/Development/dash-docset-builder/vendor/illuminate/container/Container.php:790
/Users/guill/Development/dash-docset-builder/vendor/illuminate/container/Container.php:667
/Users/guill/Development/dash-docset-builder/vendor/illuminate/container/Container.php:615
/Users/guill/Development/dash-docset-builder/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Application.php:756
/Users/guill/Development/dash-docset-builder/vendor/illuminate/container/Container.php:1225
/Users/guill/Development/dash-docset-builder/vendor/illuminate/support/Facades/Facade.php:175
/Users/guill/Development/dash-docset-builder/vendor/illuminate/support/Facades/Facade.php:144
/Users/guill/Development/dash-docset-builder/vendor/illuminate/support/Facades/Facade.php:231
/Users/guill/Development/dash-docset-builder/tests/Feature/GrabCommandTest.php:15

ERRORS!
Tests: 1, Assertions: 2, Errors: 1.

   PHPUnit\Framework\ExceptionWrapper  : Class filesystem does not exist

  at /Users/guill/Development/dash-docset-builder/vendor/illuminate/container/Container.php:790
    786|         if ($concrete instanceof Closure) {
    787|             return $concrete($this, $this->getLastParameterOverride());
    788|         }
    789| 
  > 790|         $reflector = new ReflectionClass($concrete);
    791| 
    792|         // If the type is not instantiable, the developer is attempting to resolve
    793|         // an abstract type such as an Interface or Abstract Class and there is
    794|         // no binding registered for the abstractions so we need to bail out.

  Exception trace:

  1   PHPUnit\Framework\TestResult::run(Object(Tests\Feature\GrabCommandTest))
      /Users/guill/Development/dash-docset-builder/vendor/phpunit/phpunit/src/Framework/TestCase.php:808

  2   PHPUnit\Framework\TestCase::run(Object(PHPUnit\Framework\TestResult))
      /Users/guill/Development/dash-docset-builder/vendor/phpunit/phpunit/src/Framework/TestSuite.php:761
```
Any advice on where I should dig? Could it be possible that before the `tearDown` is hit the service container has already and strangely been cleaned?

**Comment by matt-allan** [comment]
Try moving your `Storage` call above the `parent::tearDown` call.

The parent `tearDown` will clear the current application and container, which you need to use the `Storage` facade.

**Comment by nunomaduro** [comment]
Meanwhile @godbout, you could consider upgrade your laravel zero version. You are working with a very old one.

**Comment by godbout** [comment]
@matt-allan 🤦️ The power of habits! That does totally make sense (and it worked). I just got used to call the parent setUp (and tearDown)  before doing my cleaning. Realizing now the mistake, thank you so much! Was right under my nose but too close. Greatly helpful, for more than just this specific case.

@nunomaduro yeah I was surprised to see `v2.2.0` to be honest, was expecting to get the same as latest Laravel release. Just tried to get it (Laravel Zero) updated but can't reach anything higher than `2.2.0`. Now I'm thinking, is the main doc correct? 

https://laravel-zero.com/docs/installation/

Shouldn't it be `composer global require "laravel-zero/laravel-zero"` rather than `composer global require "laravel-zero/installer"`?

**Comment by pxgamer** [comment]
Sorry for the delayed reply, just picking this up. The docs are correct as this is the Laravel Zero installer (kind of like the [Laravel Installer](https://github.com/laravel/installer)). So the version you've mentioned (I'm assuming) is the output of `laravel-zero --version`?

The version of Laravel Zero (the framework) will be available by checking the output of `composer info "laravel-zero/framework" | grep "versions"` in your project.

---

From @matt-allan's reply, is this issue ok to close? 🙂

**Comment by owenvoke** [comment]
I'm going to close this as it appears to be resolved. If you have any further issues, please feel free to open a new issue. 👍
