### ISSUE TITLE
Allowing environment type other than just production or development

### ISSUE THREAD

**Issue by juniorb2ss** [laravel-zero/laravel-zero#210]
@nunomaduro

I have not found a way to set the type of environment like `testing`, ` staging` or `local`.

I do not think it's a good practice to limit the `detectEnvironment` method to just about the boolean value in `app.production` configuration.

Why not follow the standard of the laravel core itself? Keeping the environment type on the `app.env` setting?

**Comment by matt-allan** [comment]
I ran into this as well.

If we used `APP_ENV` we coud set it to `testing` in `phpunit.xml.dist` and then `app()->runningUnitTests()` would work.

**Comment by juniorb2ss** [comment]
> I ran into this as well.
> 
> If we used `APP_ENV` we coud set it to `testing` in `phpunit.xml.dist` and then `app()->runningUnitTests()` would work.

Exactly. I faced same problem.

**Comment by owenvoke** [comment]
This is now in Laravel Zero 7, thanks. 👍
