### ISSUE TITLE
Option to automatically update git tag when building app (for packagist distros)

### ISSUE THREAD

**Issue by chasdevs** [laravel-zero/laravel-zero#215]
The solution to include git tag as app version works great, but I agree with @foxted that automatic deploys to packagist would be easier if `./my-app app:build` could have an option to automatically update the git tag.

What I really want is something like this:
```sh
$ ./my-app app:release 1.1.3    # Builds app, sets git tag
$ git push --tags               # Sends tag to packagist
```

Original comment:

Hey @nunomaduro , any recommendations on using the git tag as a version when using packagist to install the build globally with composer? The issue that I run into is that the build is made before tagging, so the build end up having the previous tag as a version :/

_Originally posted by @foxted in https://github.com/laravel-zero/laravel-zero/issues/105#issuecomment-437802142_

**Comment by nunomaduro** [comment]
That should be a manual process IMO, what about if the build is in a incorrect state?

**Comment by mikeerickson** [comment]
I agree this should be a manual process.  That is how we handle for our zero based projects, using a build bash script (among many tasks, bumps version info) which also has switch to deploy.
