### ISSUE TITLE
Cancelling app:build leaves app in production mode

### ISSUE THREAD

**Issue by matt-allan** [laravel-zero/laravel-zero#217]
Issue:

I was building my app then realized I forgot something so I cancelled it:

```
$ php hours app:build --no-interaction

                                                
                Building process                
                                                

   1. Moving application to production mode: ✔

  7/25 [=======🍺--------------------]  28%
^C
```

After making my update I tried to build again and got this error:

```
php hours app:build --no-interaction
                                                         
  There are no commands defined in the "app" namespace.
```

It looks like this happened because `config/app.php` had been modified. Reverting the changes fixed it.

The BuildCommand destructor attempts to prevent this from happening but it doesn't look like constructors are called when you send a SIGINT signal to the process.

Proposal:

If we update `app:build` to trap the SIGINT signal we can run the `clear` command before the process is killed.

**Comment by nunomaduro** [comment]
Sounds a good idea, can you work a pull request on that?

**Comment by pxgamer** [comment]
I think this was closed by https://github.com/laravel-zero/framework/pull/365?

**Comment by matt-allan** [comment]
yep 😁, I will close this
