### ISSUE TITLE
Database component doesn't autoload seeds

### ISSUE THREAD

**Issue by matt-allan** [laravel-zero/laravel-zero#219]
If you use the database component the autoload mapping isn't setup by default for the seeds. You need to manually add `"classmap": ["database/seeds"]` to `composer.json`.

It would be nice if zero could add this and dump the classmap automatically. Alternatively it would be nice to output instructions if that isn't possible.

**Comment by nunomaduro** [comment]
I am quite sure that I have coded something to autoload those files, can you double check?

**Comment by matt-allan** [comment]
Ah I see, the service provider is [manually requiring the files](https://github.com/laravel-zero/framework/blob/9854a8a69809ce011386a58455bc48f76d57681d/src/Components/Database/Provider.php#L90).
