### ISSUE TITLE
Artisan command using updated IOC bindings.

### ISSUE THREAD

**Issue by mtvbrianking** [laravel-zero/laravel-zero#227]
It's a whole day now, trying to get my console command to use the newest service container binding by all in vain.

From #99 elaborates that the command is created earlier in the application bootstrap, but the solution given is a bit obsolete for v5.8

I bump into errors like;
- `Call to undefined method LaravelZero\Framework\Application::getContainer()`
- `Call to undefined method LaravelZero\Framework\Application::add()`

So I've made the following adjustments. But what's the replacement for `add()`.

```diff
/**
 * @param string $command
 * @param array  $arguments
 */
protected function call($command, array $arguments = [])
{
-     $command = $this->app->getContainer()->make($command);
+    $command = $this->app->make($command);

*     $this->app->add($command); // Unknown method 'add'

    $this->app->call($command->getName(), $arguments);
}
```

This way, we can do the following in the tests:

```diff
/** @test */
function it_tests_a_mocked_dependency()
{
    $mock = $this->createMock(TestService::class);

-    $this->app->getContainer()->instance(TestService::class, $mock);
+    $this->app->instance(TestService::class, $mock);

    $mock->expects($this->once())->method('someMethod')->willReturn('from the tests');

    $this->call(HelloCommand::class);
}
```

**Comment by owenvoke** [comment]
Hi @mtvbrianking, apologies that this has been sitting here so long. Did you manage to resolve the issue? I've had a look into this and can't find a direct replacement other than using `registerCommand()` (but that's on the Console Kernel), or `bind()` on the container which seems kind of awkward to do.

**Comment by mtvbrianking** [comment]
@owenvoke then, I was new to TDD with Laravel but I settled with `registerCommand()`  too.
