### ISSUE TITLE
Using facades in tests

### ISSUE THREAD

**Issue by clarkeash** [laravel-zero/laravel-zero#228]
I am trying to write tests but my application uses the the Storage Facade to access the filesystem and the tests fail.

Here is a test I have to demonstrate the error:

```php
<?php

namespace Tests\Unit;

use Illuminate\Support\Facades\Storage;
use PHPUnit\Framework\TestCase;

class ConfigTest extends TestCase
{
    /**
    * @test
    */
    public function it_can_use_storage()
    {
        $data = Storage::disk('local')->allFiles('.');

        var_dump($data);
    }
}
```

And this is the error I get when I run phpunit:

![image](https://user-images.githubusercontent.com/1612186/58764868-a99b4c00-856c-11e9-87e9-4e1034b7a1ea.png)

This all works fine in the application code, just not in the tests. Is there anything I am missing?

**Comment by clarkeash** [comment]
Crap! I was extending the wrong TestCase class 😞

**Comment by nunomaduro** [comment]
Yeah, no problem.
