### ISSUE TITLE
Please update the Dusk's chromedriver version to latest

### ISSUE THREAD

**Issue by tushargugnani** [laravel-zero/laravel-zero#229]
Installed console-dusk component on Laravel zero

Running dusk test gives the following error

Facebook\WebDriver\Exception\WebDriverException::throwException("session not created: Chrome version must be between 70 and 73
  (Driver info: chromedriver=2.45.615355

**Comment by nunomaduro** [comment]
Can you do a pull request on this?

**Comment by xaniuskarlhall** [comment]
Experiencing the same problem

**Comment by nunomaduro** [comment]
Can you try to debug this?

**Comment by manelgavalda** [comment]
Same problem. Created a pull request adding the command to solve this.

**Comment by pxgamer** [comment]
Laravel Dusk Console v1.5.0 adds support for updating the ChromeDriver component.

Now you'll just need to run:
```bash
# Update Chrome Driver to latest version
application dusk:chrome-driver

# Update Chrome Driver to latest version for Chrome 78
application dusk:chrome-driver [78]
```

See nunomaduro/laravel-console-dusk#14 for more information.
