### ISSUE TITLE
can I use scout-algolia with laravel zero?

### ISSUE THREAD

**Issue by nroussis** [laravel-zero/laravel-zero#231]
Hello,
I installed laravel scout.
Then followed instructions here:
https://www.algolia.com/doc/framework-integration/laravel/getting-started/installation/

then:
php app-name scout:import
gives me an error
There are no commands defined in the "config" namespace.
Note: When publishing php artisan vendor:publish --provider="Laravel\Scout\ScoutServiceProvider" nothing happened although I got the message that it was successfully published. Maybe I need to add something in my config/app.php file?
Thanks.

**Comment by nunomaduro** [comment]
You need to add the `ScoutExtendedServiceProvider::class` into your `providers` key on the app.php.

**Comment by owenvoke** [comment]
I'm going to close this as it appears to be resolved. If you have any further issues, please feel free to open a new issue. 👍
