### ISSUE TITLE
changing timezone

### ISSUE THREAD

**Issue by nroussis** [laravel-zero/laravel-zero#232]
Hello,
Im trying to change my timezone by adding to app.php as suggested here
https://stackoverflow.com/questions/32884388/change-timezone-in-lumen-or-laravel-5
Do i need to refresh my config cache?
If yes then php app-name config:cache not supported.
Thank you for a great app and your support.

**Comment by nunomaduro** [comment]
If that doesn't work, it may be a bug.

**Comment by ahmic** [comment]
I've added timezone in `config/app.php` this way `'timezone' => 'Europe/Sarajevo'`, and it's working

**Comment by nroussis** [comment]
indeed it works!
