### ISSUE TITLE
`php application install` exception thrown in Build.php:57

### ISSUE THREAD

**Issue by arswright** [laravel-zero/laravel-zero#234]
Full exception:

    PHP Fatal error:  Uncaught TypeError: Return value of App\Console\Commands\Build::configure() must be an instance of App\Console\Commands\void, none returned in /tmp/test/app/Console/Commands/Build.php:57

Console session output attached.

[190721_1934-laravel_zero.txt](https://github.com/laravel-zero/laravel-zero/files/3415496/190721_1934-laravel_zero.txt)

**Comment by nunomaduro** [comment]
@arswright What php version are you using?

**Comment by arswright** [comment]
`php -v` / `PHP 7.0.33-0ubuntu0.16.04.5 (cli) ( NTS )`

**Comment by arswright** [comment]
It appears as though everything is working after removing `: void` from function signatures in `Build.php` and `Install.php` under `app/Console/Commands`, though there's also the warning for deprecated Carbon version (haven't gotten into testing whether upgrading introduces issues, though I figured anything blocking successful install from documentation is probably of interest to you).

**Comment by nunomaduro** [comment]
Laravel Zero requires `Requires PHP 7.1.3+`.

**Comment by arswright** [comment]
Looks like composer will "helpfully" install v1.0.0 (`composer.json:17: "php": ">=7.0"`) under 7.0.33 - explains a lot (if any similarly-confused issues get raised).

Thanks!
