### ISSUE TITLE
 ReflectionException  : Class auth does not exist

### ISSUE THREAD

**Issue by hersdyanata** [laravel-zero/laravel-zero#235]
Hi,
I'm just used this package, and following steps. I'm using laravel-zero and need to connect to oracle server. The problem comes everytime i'm add :

`Yajra\Oci8\Oci8ServiceProvider::class
`
into the config\app.php

I get this error :
![image](https://user-images.githubusercontent.com/12206640/61894315-6214b900-af3a-11e9-9a9e-a1e91cc0f412.png)

but when i'm removed that from providers, everything's fine but i can't connect to oracle.
please advise. thanks

**Comment by juniorb2ss** [comment]
Error is clean. `Auth` does not exist. Because you don't need `Auth` for a micro-framework to build console applications.

If this package need `Auth` for some reason, you need install: https://github.com/illuminate/auth

**Comment by nunomaduro** [comment]
Exactly what @juniorb2ss said.

**Comment by hersdyanata** [comment]
@nunomaduro , please take a look [here](https://github.com/laravel-zero/laravel-zero/issues/207). Thanks

**Comment by juniorb2ss** [comment]
@hersdyanata Do you have any doubt? You need install `Auth` package to use this library.
