### ISSUE TITLE
How to get all arguments when error occurs

### ISSUE THREAD

**Issue by mikeerickson** [laravel-zero/laravel-zero#236]
I have a custom Exception handler and when invoked, I would like to have access to the entire command executed (including all the arguments).  

Currently, I am only able to see what the actual command was, but can't seem to track down the arguments.

If there is an easier way to perform personal validation before hitting the Exception handler, that would be more ideal

Does anybody have an idea how to do this?

**Comment by mikeerickson** [comment]
I have managed to get access to the class using exception stacktrace and it has the values I am looking for, but not sure how to access them, I need the values from `tokens` property.


```php
$st = $exception->getTrace()[2]["args"][0];
```

```php
Symfony\Component\Console\Input\ArgvInput {#13
  -tokens: array:2 [
    0 => "command"
    1 => "Argument1"
  ]
  -parsed: []
  #definition: Symfony\Component\Console\Input\InputDefinition {#289
```

**Comment by mikeerickson** [comment]
I have figured it out :-)

**Comment by nunomaduro** [comment]
Can you share @mikeerickson ?
