### ISSUE TITLE
"Let’s Build a console app with Laravel Zero" on Medium.com is obsolete

### ISSUE THREAD

**Issue by johnsnook** [laravel-zero/laravel-zero#238]
This seems to be out of date with the current version of Laravel Zero. 
1. There is no app/DefaultCommand.php. Creating one doesn't work, so I moved it to app/Commands.
2.  "php application rename weather" is deprecated, should be "app:rename"
3. When I ran "php weather", this error occurred: "Symfony\Component\Debug\Exception\FatalThrowableError : Class 'NunoMaduro\ZeroFramework\Commands\AbstractCommand' not found" 
4. After attempting to adapt to how I think it's supposed work (creating new command called "WeatherCommand", adding zttp use statement), and running "php weather weather" I received this error: " BadMethodCallException : Method App\Commands\WeatherCommand::getContainer does not exist."

I give up.

**Comment by nunomaduro** [comment]
Thanks for reporting this issue, Laravel Zero is different now: better. I will make sure to update the article soon.

**Comment by owenvoke** [comment]
I guess in a way, that's kind of what I intended [this blog post](https://voke.dev/blog/getting-started-with-laravel-zero/) to be. 👍🏻
