### ISSUE TITLE
Calling the config:clear command doesn't work.

### ISSUE THREAD

**Issue by wotta** [laravel-zero/laravel-zero#239]
Hello, 

I am running into the following issue. I made a command that writes a config file if it doesn't exist. When this file is written I want to display some output that everything has worked.

But I cannot do that since it seems ( cannot figure it out for a 100% ) that the class I am calling still has the old env/config values.
If I run the same command again without changes and the file there it does work.

So I tried to run `$this->call('config:clear')` and `Artisan::call('config:clear')`.
Both commands fail.
I get the following errors:
`$this->call` results in: `There are no commands defined in the "config" namespace.`
`Artisan::call` results in: `The command "config:clear" does not exist.`

I can verify that the illuminate package is included as it should be.
If you want I can give you access to a private repo where this happens.

**Comment by nateritter** [comment]
Have you registered the command and/or ensured you can actually call that command from the CLI?

**Comment by wotta** [comment]
@nateritter first off I want to wish you a happy New year.

Yes I have registered the command and I did run it from the CLI.
But both the CLI invocation and the invocation from within a command don't seem to work.

**Comment by pxgamer** [comment]
Hi @wotta, I've taken a look at this and the `config:clear` command appears to work as expected when the command is registered. To get this working, I updated this mapping in `config/commands.php`:
```php
'add' => [
    Illuminate\Foundation\Console\ConfigClearCommand::class,
],
```

**Comment by wotta** [comment]
@pxgamer Thanks for double-checking, I will recheck this when I have time 🙂 
Maybe it wasn't working with the version I was using at the time.
