### ISSUE TITLE
sentry package has errors when loaded to laravel-zero

### ISSUE THREAD

**Issue by ccsliinc** [laravel-zero/laravel-zero#241]
Looking to log errors to sentry, I am not quite sure how to go about installing sentry into laravel-zero as everything I tried contains errors.  Can you provide any information or guidance to help with the installation and usage of sentry or provide a comparable alternative which does work.

**Comment by pxgamer** [comment]
Hi @ccsliinc, I set up a test repository detailing how I managed to set up Sentry into Laravel Zero. 👍 Hope it helps. 🙂

https://github.com/pxgamer/laravel-zero-sentry-example

You can either follow the [README instructions](https://github.com/pxgamer/laravel-zero-sentry-example/blob/master/README.md), or check [the commits](https://github.com/pxgamer/laravel-zero-sentry-example/commits/master) to see what was done.

<details>
<summary>Output results in the Sentry dashboard</summary>

![Image showing the Sentry exception results](https://user-images.githubusercontent.com/1899334/65413196-d0fe7900-dde8-11e9-8f67-5292aab19ff6.png)

</details>

**Comment by nunomaduro** [comment]
Thank you @pxgamer !

**Comment by ccsliinc** [comment]
@pxgamer Thank You.

**Comment by opicodes** [comment]
Hi, sorry about commenting on an old post.
I'm trying to integrate sentry on a L0 ver 9.2, using laravel-sentry 3.3.2.
I followed the instructions from the post above but I get an error about the Log facade "A facade root has not been set."

Maybe with the updates something changed since 2019?
