### ISSUE TITLE
Dynamic Application Name

### ISSUE THREAD

**Issue by sarthaksavvy** [laravel-zero/laravel-zero#246]
Hey, 
My laravel-packer command-line tool is working fine but what if I can give an option to the user to set the application name while installing or after installing.

Like currently if you install a packer, then you need to write 'packer' to use this CLI but I want to give functionality to the user so that he/she can use any name like 'pkr' or 'packr' whatever they like.

So it is possible and if yes then how?

Thanks for this awesome framework.

**Comment by pxgamer** [comment]
Hi @sarthaksavvy, I'm assuming that this is for [bitfumes/laravel-packer](https://github.com/bitfumes/laravel-packer)?

I guess the easiest way would be for people to add an alias for the app (i.e. `alias pkr='packer'`). However, are you wanting this functionality through the Composer install, or the Phar install?

**Comment by octoper** [comment]
Hi @sarthaksavvy have you found a solution to this issue?

**Comment by sarthaksavvy** [comment]
no not yet
