### ISSUE TITLE
Laravel-Zero/Framework v6.0 breaks database factories

### ISSUE THREAD

**Issue by web3devin** [laravel-zero/laravel-zero#247]
This appears to be related to the changes in https://github.com/laravel-zero/framework/pull/353.

Steps to reproduce:

1. `composer global require "laravel-zero/installer"`
2. `laravel-zero new <your-app-name> && cd <your-app-name>`
3. `php <your-app-name> app:install database`
4. `php <your-app-name> make:factory <your-factory-name>`

At this point, I am unable to use any commands on the CLI as the following error is thrown:
```
ErrorException  : Undefined variable: factory

at .../test-cli/database/factories/test-factory.php:8
     4| 
     5| use App\Model;
     6| use Faker\Generator as Faker;
     7| 
>    8| $factory->define(Model::class, function (Faker $faker) {
     9|     return [
    10|         //
    11|     ];
    12| });

  Exception trace:

  1   Illuminate\Foundation\Bootstrap\HandleExceptions::handleError("Undefined variable: factory", ".../test-cli/database/factories/test-factory.php", [Object(Symfony\Component\Finder\SplFileInfo)])
     .../test-cli/database/factories/test-factory.php:8

  2   require_once(".../database/factories/test-factory.php")
      .../test-cli/vendor/illuminate/filesystem/Filesystem.php:109

  Please use the argument -v to see more details.
```

I am able to fix the issue if I revert the changes made in this commit: https://github.com/laravel-zero/framework/pull/353/commits/0f6f302e877ea31aa81eae8550b8147b23798957

After reviewing the PR linked and the associated issue(https://github.com/laravel-zero/laravel-zero/issues/219), I am not sure why the change in the above commit was even made, as it provides no functionality to the basic usage of the repo. The Factory models aren't needed to be autoloaded, as they are loaded using `factory(ClassName::class)`; Instead, it introduced a breaking change to the repo.

**Comment by nunomaduro** [comment]
Can you create a pull request addressing this issue?

**Comment by web3devin** [comment]
> Can you create a pull request addressing this issue?

Already created [here](https://github.com/laravel-zero/framework/pull/366).

**Comment by mikeerickson** [comment]
@nunomaduro hey bud, would you like me to test this PR so you don’t have to worry about it? I can do it tomorrow

**Comment by nunomaduro** [comment]
@mikeerickson That would be awesome.
