### ISSUE TITLE
self-update git location

### ISSUE THREAD

**Issue by Drivez** [laravel-zero/laravel-zero#248]
There was nothing in the docs on how the self-updater gets the git location. 

When i installed the self update the default search location for the update was `file_get_contents(https://packagist.org/p/....`

How can i point it to the right private github location?
the name in composer.json is the github org. and repo name

Is there something i might be missing in the composer file, or another settings file to set te location?

**Comment by nunomaduro** [comment]
I am not sure about this one, can you dive into the source code to fully understand this? Also maybe improve the docs?

**Comment by Drivez** [comment]
I will give it a shot 👍

**Comment by owenvoke** [comment]
I think that this would be a good issue to resolve. The update strategy we use extends:
https://github.com/humbug/phar-updater/blob/master/src/Strategy/GithubStrategy.php

Currently the updater pings Packagist for the JSON API (e.g. https://packagist.org/packages/laravel-zero/laravel-zero.json), it then retrieves the `package.versions.[version].source.url` value from the JSON response, and uses this to [generate a download URL](https://github.com/laravel-zero/framework/blob/7.x/src/Components/Updater/GithubStrategy.php#L19).

This download URL is hardcoded by default to be in `builds/{binary-name}` in the repository.

However, obviously for private packages that aren't available through Packagist (or an alternative like Satis), this isn't possible to do so the request to Packagist's API fails.

----

I think to resolve this, we can either add some details to the ["Self update" section of the docs](https://laravel-zero.com/docs/build-a-standalone-application) mentioning that the self-updater won't work for packages not in Packagist, or... we resolve the issue by changing the way the auto-update works. I'm not really sure what a better way to do the auto-update would be. Unless we added alternative update methods to [the service provider](https://github.com/laravel-zero/framework/blob/7.x/src/Components/Updater/Provider.php#L56)?

If there was a `self-update` configuration file that we could optionally publish with something such as:
```php
<?php

use LaravelZero\Framework\Components\Updater\GithubStrategy;

return [

    /*
    |--------------------------------------------------------------------------
    | Update Strategy
    |--------------------------------------------------------------------------
    |
    | This value determines the strategy used to update your application. By
    | default the "self-update" command uses the "GitHub" strategy which
    | checks Packagist's API for the repository source URL, and then
    | downloads the compiled binary directly from the repository.
    |
    | See the "Self Update" documentation for a list of available strategies.
    |
    */

    'driver' => GithubStrategy::class,

];
```

**Comment by octoper** [comment]
@owenvoke is this resolved?

**Comment by owenvoke** [comment]
Yes. :+1: A custom provider can now be created that implements this.
