### ISSUE TITLE
Logo component does not work in PHP 7.4

### ISSUE THREAD

**Issue by pxgamer** [laravel-zero/laravel-zero#253]
One of the deprecations in PHP 7.4 was to deprecate the computation of invalid characters in base conversion functions. This causes the Logo module test to fail on 7.4 with a notice.

The PHP deprecation notes state:
> Passing invalid characters to base_convert(), bindec(), octdec() and hexdec() will now generate a deprecation notice.

This appears to occur when loading the font in [the Zend Text `Figlet` class](https://github.com/zendframework/zend-text/blob/master/src/Figlet/Figlet.php#L1095), I'm not quite sure if this is an issue with the Zend Text package, or the `big.flf` font pack we provide with Laravel Zero's Logo component.

---

I've now tested using the built in `zend-framework.flf` file that the Zend Text package provides, and the text is successfully output. So I think that this is an issue with the `big.flf` file we provide. I've also now tested a few others. Not sure why there is an issue with `big.flf` specifically. 🤔

**Comment by ahpetrot** [comment]
Brew updated to PHP 7.4.0 (cli) (built: Nov 29 2019 16:18:30) ( NTS ) , broke the logo package. 

>  ErrorException  : Invalid characters passed for attempted conversion, these have been ignored

  xxx/xxx/vendor/zendframework/zend-text/src/Figlet/Figlet.php:1095
    1091|                 $uniCode = hexdec(substr($uniCode, 2));
    1092|             } elseif (0 === strpos($uniCode, '0') &&
    1093|                        $uniCode !== '0' or
    1094|                        0 === strpos($uniCode, '-0')) {
  > 1095|                 $uniCode = octdec($uniCode);
    1096|             } else {
    1097|                 $uniCode = (int) $uniCode;
    1098|             }
    1099|

Quick fix to get around the logo issues - <your-zero-project>/config/logo.php 

> 'enable' = false 


This will disable the logo and allow the program to run... for me at least.

**Comment by pxgamer** [comment]
It looks like the Zend Text package has been deprecated, and work has moved to the [`laminas-text`](https://github.com/laminas/laminas-text) repository. I'm going to take a look at this later today / this week.

Related to the upgrade to PHP 7.4, we'll need to update Humbug Box to 3.8.4 👍
