### ISSUE TITLE
Queueing a command from within a command does not work. Missing `queue()` in `Commands/Command.php`?

### ISSUE THREAD

**Issue by nateritter** [laravel-zero/laravel-zero#255]
**The goal:** To run a command which will queue another artisan command.  

_Please note there is a lot of work being done around this. This is a very simplified example and doesn't make sense to do on the surface, but this is the essence of what I need._

Given the following command:

```
class OrgsScrapeCommand extends Command
{
    protected $signature = 'scrape:orgs {id}';
    protected $description = 'Set queued job to scrape organization user names.';

    public function handle()
    {
        $id = $this->argument('id');
        $this->queue('scrape:org-user-names', ['id' => $id]); // This is the line I'm working on.
    }

    public function schedule(Schedule $schedule)
    {
        $schedule->command(static::class)->daily();
    }
}
```

The `$this->queue()` line throws an exception: `Method App\Commands\OrgsScrapeCommand::queue does not exist.` 

So, I've tried using `Artisan::queue()` directly but when I do that, the command gets queued but when it's run it throws `The "id" argument does not exist. {"exception":"[object] (Symfony\\Component\\Console\\Exception\\InvalidArgumentException(code: 0): The \"id\" argument does not exist. at /Users/nateritter/Sites/cug-active-users/vendor/symfony/console/Input/ArrayInput.php:203)`.

The `$signature` is `scrape:org-user-names { id : The ID of the Organization }`, so the `id` argument is set.  

So, based on some other googling I've done I tried adding the following to the `scrape:org-user-names` command, but it doesn't seem to make a difference:

```
    protected function getArguments()
    {
        return [
            ['id', InputArgument::REQUIRED, 'The ID of the Organization.'],
        ];
    }
```

Thus, I'm wondering if perhaps this would be fixed if the `queue()` method was added to the `Commands/Command.php` file.  I tried, but am unable to get it to work properly, so I have to create this issue to request some assistance.  Perhaps I'm going about it the wrong way or there's a work around available?

**Comment by nateritter** [comment]
**Update:** I did just find that running `Artisan::queue('scrape:org-user-names', [$id => true]);` does queue the command, however, it seems the command doesn't get run as I get no errors and I added a `Log::info('handling command');` line in, which doesn't seem to ever get hit as it doesn't show in the logs at any point.

**Comment by nunomaduro** [comment]
Have you tried to install the queue component? `app:install queue`.

**Comment by nateritter** [comment]
🤦‍♂ I had not tried that.  I will do that. My apologies for being daft and not R'ingTFM.

**Comment by pxgamer** [comment]
Glad you got it sorted, I'll close this issue. If you have any further issues, feel free to open another. 👍
