### ISSUE TITLE
(build) How can I use sqlite from a laravel-zero app?

### ISSUE THREAD

**Issue by upandfine** [laravel-zero/laravel-zero#258]
How can I use sqlite from a laravel-zero app?
When I try, I get the following error message: Database (phar:///app/shop2erp/builds/shop2erp/database/database.sqlite) does not exist. (SQL: PRAGMA foreign_keys = ON;)

(App name is shop2erp)

database/database.sqlite exists in the builds folder, parallel to the build.

By the way - a really great project!

**Comment by pxgamer** [comment]
You would need to set up the custom database path in your configuration file. You can also set this using the `DB_DATABASE` environment variable.

By default, the path is `database_path('database.sqlite')`, which will resolve to being inside your PHAR file once built.

**Comment by nunomaduro** [comment]
This kind of stuff should go to the docs. @upandfine can you make a pull request on the website?

**Comment by upandfine** [comment]
works.

**Comment by upandfine** [comment]
> This kind of stuff should go to the docs. @upandfine can you make a pull request on the website?

How can I do that?

**Comment by pxgamer** [comment]
@upandfine, thank you for the PR. That's great!
