### ISSUE TITLE
SQLite with PHAR - migrate fails

### ISSUE THREAD

**Issue by upandfine** [laravel-zero/laravel-zero#259]
If you call `php myapp migrate` with a PHAR, an error occurs:

 `The "phar:///path/to/phar/database/migrations" directory does not exist.`

Is there also a configuration value that can be set here? 
(See `DB_DATABASE`)

**Comment by pxgamer** [comment]
Is the `database` directory included in your `box.json`?

This might be related to the migration files being collected and searched using a glob, as far as I know `glob()` doesn't support streams in PHP. But I will look into this later hopefully. 👍

I'm not sure if there is a way to change the migrations directory, I'd have to look into that.

**Comment by upandfine** [comment]
> Is the `database` directory included in your `box.json`?
How can I do that?

**Comment by pxgamer** [comment]
In your project directory, there should be a `box.json` (https://github.com/laravel-zero/laravel-zero/blob/stable/box.json). Under the `directories` array, add an entry for `database`. For example:

```diff
{
    "chmod": "0755",
    "directories": [
        "app",
        "bootstrap",
        "config",
+       "database",
        "vendor"
    ],
    "files": [
        "composer.json"
    ],
    "exclude-composer-files": false,
    "compression": "GZ",
    "compactors": [
        "KevinGH\\Box\\Compactor\\Php",
        "KevinGH\\Box\\Compactor\\Json"
    ]
}
```

**Comment by upandfine** [comment]
solved
