### ISSUE TITLE
Fix component installers with Symfony Process v5

### ISSUE THREAD

**Issue by owenvoke** [laravel-zero/laravel-zero#262]
There is an issue with Symfony Process that needs to be resolved for Laravel Zero v7.

With the [`ComposerContract`](https://github.com/laravel-zero/framework/blob/7.x/src/Providers/Composer/Composer.php) we allow providing a string (i.e. `illuminate/log "^7.0"`) to the [`require()`](https://github.com/laravel-zero/framework/blob/7.x/src/Providers/Composer/Composer.php#L67-L70) method. However, due to changes in the Symfony Process component, the space with quotes causes it to be a double-quoted argument. Which fails with Composer stating:
```txt
[UnexpectedValueException]                                        
  Could not parse version constraint ": Invalid version string """
```
On Windows, you get the following as the actual command it attempts to run:
```cmd
composer require "padraic/phar-updater """^^"1.0.6""" "" C:\Users\owen.voke\projects\laravel-zero"
```

---

Part of #254

**Comment by dbpolito** [comment]
Fixed with https://github.com/laravel-zero/framework/pull/379
