### ISSUE TITLE
Do not try to generate resource controller on make:model --all

### ISSUE THREAD

**Issue by peterjaap** [laravel-zero/laravel-zero#263]
When using `make:model --all`, Laravel Zero (well, Illuminate) creates a factory, a migration, a seeder and a resource controller. Since we're in CLI context only, the resource controller cannot be created;

``` 
  Command "make:controller" is not defined.  
                                             
  Did you mean one of these?                 
      make:command                           
      make:factory                           
      make:migration                         
      make:model                             
      make:seeder                            
                                            
```

I now have to use `--factory --migration --seed` instead of `--all` or ignore he warning (since the resource controller is created the last of the 4, the other 3 are created correctly).

Maybe it's an idea to overload [ModelMakeCommand](https://github.com/laravel/framework/blob/6.x/src/Illuminate/Foundation/Console/ModelMakeCommand.php#L46) and set `$this->input->setOption('resource', true);` to `$this->input->setOption('resource', false);`?

**Comment by owenvoke** [comment]
I guess that this can be applied to the [laravel-zero/foundation][] repository. Or, we can overload this in the framework, and then updated the reference in the [database component provider][].

[laravel-zero/foundation]: https://github.com/laravel-zero/foundation
[database component provider]: https://github.com/laravel-zero/framework/blob/09c7af708d10944ccbb6e6903b76acd2b9aa7b51/src/Components/Database/Provider.php#L62

**Comment by peterjaap** [comment]
Oh yeah foundation is already in the laravel-zero namespace. Updating this line would do it; https://github.com/laravel-zero/foundation/blob/6.x/src/Illuminate/Foundation/Console/ModelMakeCommand.php#L47

**Comment by peterjaap** [comment]
Would we then still keep the resource / controller option and the `createController()` method in the `ModelMakeCommand` at all? Is there a use-case I'm missing where creating the controller *is* useful?

**Comment by owenvoke** [comment]
We could probably remove the references to `controller` and `resource`. However, not sure if there might be packages that use these. 🤔

**Comment by peterjaap** [comment]
Since it doesn't work right now, probably not?

**Comment by owenvoke** [comment]
True! 😋 Would you like to make a PR that updates the foundation with this change? 👍

/cc @nunomaduro, just interested if you think this would be fine?

**Comment by peterjaap** [comment]
PR: https://github.com/laravel-zero/foundation/pull/12
