### ISSUE TITLE
Remove inconsistencies in Command Class

### ISSUE THREAD

**Issue by felixdorn** [laravel-zero/laravel-zero#266]
Hello!

I noticed that some commands are not implemented for the laravel OutputStyle to Laravel Zero Command.

Some of them: 
* New line
* Warning block
* Array or string in `warning, error, success, line, etc...` (super useful)
* and so on...

What do you thing about that?

I would like to submit a PR.

**Comment by owenvoke** [comment]
Would these just be proxy methods for the underlying `$this->getOutput()->{method}()`?

e.g. for `newLine()`
```php
public function newLine(int $count = 1): void
{
    $this->output->newLine($count);
}
```

**Comment by felixdorn** [comment]
Yeah.

* write()
* newLine()
* Blocks (success, warning) as their is already a error block.
* Lists
* Sections
* Progress bars

Actually, for progress bars, i think we can go further and find a better api than progressStart, progressAdvance, progressFinish.

Same thing for the naming, why listing and not `list` ?

I think their is a  place for improvements here.

What do you think ?

**Comment by felixdorn** [comment]
ping @owenvoke, can i start working on this or you don't think Laravel zeo need it ?

**Comment by owenvoke** [comment]
Hi @felixdorn, apologies I've been away this weekend. I think that some of these may be useful (i.e. a block for success, `warn()` is already available), and `newLine()`.

**Comment by felixdorn** [comment]
Cool! Will PR something tomorrow.
