### ISSUE TITLE
Add option to validate ask() input

### ISSUE THREAD

**Issue by peterjaap** [laravel-zero/laravel-zero#267]
Wouldn't it be cool if we could pass in a validation rule directly into the third argument of the ask method like this?

```
$title = $this->ask('Title', null, 'required|min:2|max:255');
```

If we extend `\Illuminate\Console\Concerns\InteractsWithIO` into the Laravel Zero framework, and we update the `ask()` method to the following:

```
    /**
     * Prompt the user for input.
     *
     * @param  string  $question
     * @param  string|null  $default
     * @param  string|null  $validationRule
     * @return mixed
     */
    public function ask($question, $default = null, $validationRule = null)
    {
        $validator = null;
        if ($validationRule) {
            $validator = function ($answer) use ($question, $validationRule) {
                \Illuminate\Support\Facades\Validator::make([$question => $answer], [
                    $question => $validationRule,
                ])->validate();
            };
        }
        return $this->output->ask($question, $default, $validator);
    }
```

If the `illuminate/validation` package isn't required through composer yet, this will of course give an exception that it can't find the validator; `Target class [validator] does not exist.`. Also see #150

**Comment by owenvoke** [comment]
I think this would be an interesting addition. 🤔 I'd probably implement this as `array|string|null` for the property, as you may want to use an array of rules (I personally prefer this over a string).

This could possibly be added as a new method, but maybe that would just cause unnecessary duplication.

---

Regarding the failure without the validation package, the class could be checked if you provide a validation rule. For example, something like:
```php
if ($validationRule) {
    if (! class_exists(\Illuminate\Validation\Validation::class) || ! $this->app->bound('validator')) {
        throw new \RuntimeException('The "illuminate/validation" package is required to use validation rules');
    }

    // ...
}
```
And then it can be added as a suggested package in the `composer.json` maybe? 🤔

**Comment by peterjaap** [comment]
All of them great ideas!

I'll try to get around to making a PR for it one of these days :)

**Comment by peterjaap** [comment]
PR: https://github.com/laravel-zero/framework/pull/381
