### ISSUE TITLE
Add release guide to the ignore-export list

### ISSUE THREAD

**Issue by danielsuguimoto** [laravel-zero/laravel-zero#272]
The framework release guide is unnecessary inside project vendors.

**Comment by owenvoke** [comment]
If you would like to open a PR for this on the framework repository, feel free. :+1: If not, I will resolve this later today. Thanks.

**Comment by danielsuguimoto** [comment]
I saw your message just now haha. You're welcome!

**Comment by owenvoke** [comment]
This should be resolved in any future releases. 👍 Thanks @danielsuguimoto

**Comment by danielsuguimoto** [comment]
@owenvoke Happy to help!
