### ISSUE TITLE
Is it possible that execute a console command inside the Command class?

### ISSUE THREAD

**Issue by Nothing-Works** [laravel-zero/laravel-zero#273]
Is it possible that execute a console command inside the Command class?
like [Symfony Process Component](https://symfony.com/doc/current/components/process.html)

**Comment by owenvoke** [comment]
Yes, this is possble. `symfony/process` is included by default, so you can run commands using it if you want to.

If you are running one of your application commands you can use `$this->call('command')`. However, for running external commands, you will need to manually specify it using the `Process` class.

**Comment by Nothing-Works** [comment]
cool thanks @owenvoke

**Comment by Nothing-Works** [comment]
@owenvoke  would you take pr that wraps `symfony/process`? I mean support external commands natively?

**Comment by mikeerickson** [comment]
@Nothing-Works what is your proposed API that wraps `symfony/process`?

**Comment by Nothing-Works** [comment]
@mikeerickson tbh, I do not know, I am very new to this project and not sure if the maintainer likes the idea. do you have any suggestions?

**Comment by mikeerickson** [comment]
@Nothing-Works using the `symfony/process` method is pretty straight forward, thus the reason for asking what you were proposing.  

What is your desired use case and does `symfony/process` not provide you what you’re looking for?

**Comment by Nothing-Works** [comment]
@mikeerickson  yes you are right, as I said I just want a wrapper for it, manually using the `Process` class provides everything for me.

**Comment by owenvoke** [comment]
Personally I've created an `InteractsWithExternalProcess` concern/trait for adding this functionality to projects. This just adds some methods that instantiate a `Process` instance from either a string or an array, and return the `Process` so you can perform whatever actions are necessary.
