### ISSUE TITLE
Update to use GitHub Actions

### ISSUE THREAD

**Issue by owenvoke** [laravel-zero/laravel-zero#274]
This isn't really a necessary thing to do and is just a proposal, but would it be good to move to [GitHub Actions](https://github.com/features/actions)?

I've tested this in a development branch on my fork and it appears to be a bit faster. The output is also integrated with GitHub directly.

https://github.com/owenvoke/laravel-zero-framework/commit/b22740722f7674aedc0a38aaeb32e4f7e9d19075

----

The difference in speed can be seen on the Action Run pages:

- [GitHub Actions](https://github.com/owenvoke/laravel-zero-framework/actions/runs/50410792)
- [Travis CI](https://github.com/owenvoke/laravel-zero-framework/runs/488893420)

For GitHub Actions, each matrix build took around 1 minute. For Travis CI, they took about 2.5 to 3 minutes. This isn't a huge boost, but it opens up more possibilities in future.

----

I've also used [PCov](https://github.com/krakjoe/pcov) for code coverage on the GitHub Actions build, instead of Xdebug.

**Comment by nunomaduro** [comment]
If you think its best, you can do it. I never worked with GitHub actions tho.

**Comment by owenvoke** [comment]
This is now implemented. 👍
