### ISSUE TITLE
Disable the "artisan test" command in production

### ISSUE THREAD

**Issue by owenvoke** [laravel-zero/laravel-zero#277]
When upgrading to version 7 of Laravel Zero, it now includes the `[application] test` command from Laravel core. The `test` command is provided [by Collision here](https://github.com/nunomaduro/collision/blob/stable/src/Adapters/Laravel/Commands/TestCommand.php).

This should be disabled in production builds. 👍

It should be a relatively simple change to the [`laravel-zero/framework`](https://github.com/laravel-zero/framework) repository.

**Comment by nunomaduro** [comment]
@owenvoke Maybe you can point people on the right direction? File name or line?

**Comment by wotta** [comment]
@nunomaduro yeah that would be helpful. I was looking in the repo but couldn't figure it out directly.

With some more information I would love to try to fix this issue.

**Comment by peterjaap** [comment]
@wotta I guess this is it; https://github.com/laravel-zero/framework/blob/2c37734945a6d24edd151434adc8761c5dab3f2a/src/Kernel.php#L34

**Comment by peterjaap** [comment]
Guess it should either be hidden here; https://github.com/laravel-zero/laravel-zero/blob/stable/config/commands.php#L57

Or removed here; https://github.com/laravel-zero/laravel-zero/blob/stable/config/commands.php#L76

**Comment by wotta** [comment]
@peterjaap thanks for the information. I couldn't really find it at first.

The first link looks like the spot where it should be implemented.
That config file looks like it will be used for local development.

When I look at the [documentation](https://laravel-zero.com/docs/configuration/#js-nav-menu) it feels like those are the command for local development.
@nunomaduro is this a correct assumption or not?

**Comment by owenvoke** [comment]
This is now resolved in https://github.com/laravel-zero/framework/pull/392, thanks @wotta!

**Comment by wotta** [comment]
Thanks for helping and thinking to find a solution @owenvoke.
