### ISSUE TITLE
Please provide a valid cache path on email

### ISSUE THREAD

**Issue by innoflash** [laravel-zero/laravel-zero#280]
When using the illuminate/mail services in production the email sents successfully but in production i get `Please provide a valid cache path.` What exactly am i supposed to do. 

I added the `storage/framework/views` to the `box.json`

**Comment by Pe46dro** [comment]
In `config/view.php` check the `compiled` key
```
...
'compiled' => realpath(storage_path('framework/views')),
...
```
In storage folder i have `framework/views` folders

**Comment by innoflash** [comment]
@Pe46dro yeah its set that way and probably thats why it works when I run the mail in development. The issue starts when i push the app into production

**Comment by owenvoke** [comment]
That will probably be because it's trying to save the compiled views inside the compiled Phar file.

I've found that the easiest way in most cases is to point it at a temporary directory, or to use the current directory. I think this is an open issue which involves a similar problem: #177

**Comment by innoflash** [comment]
@owenvoke thanks, i think i will force it to use the same dir i am using as my Storage default on the system. The app i built is using system folders rather than the app folders. Will see if the magic will work there.

**Comment by owenvoke** [comment]
Good luck! If you do have any issues, let me know. And hopefully we can resolve this whole thing in future. 🤔

**Comment by innoflash** [comment]
I managed to hack my around the `views` folder. I will show you just now after i prove a theory.

I just bumped into another silly one.

I build the phar and am running it out of the project folder (on Unbuntu desktop) and i am getting this error. 

Any idea on how to fix this?
![Screenshot from 2020-03-18 19-08-17](https://user-images.githubusercontent.com/12772919/76987603-1e991000-694c-11ea-9cfc-ef683a6531e2.png)

**Comment by innoflash** [comment]
So for setting the app to use system storage. I built a helper class and named it `Config.php` (its doing quite a lot :))

I accessed the system using a method:
```php
//Config.php

function getMyDesiredDir(): string
    {
        $fullPathArray = collect(explode('/', realpath(null)));
        return DIRECTORY_SEPARATOR . $fullPathArray[1] . DIRECTORY_SEPARATOR . $fullPathArray[2] . DIRECTORY_SEPARATOR . 'my-dir';
    }
```

I realized `realpath()` with a `null` will always give back where the PHP program is running from. For a person on a Linux environment if I explode the `$path` the first 2 items of that array will always give me `$HOME` for the OS nomatter where i am running the program from.
There could be a shorter and efficient way but this one worked for me now.

In the `filesystems.php` I set the local path to that my desired directory.
```php
//filesystems.php
'local' => [
            'driver' => 'local',
            'root' => (new Config())->getMyDesiredDir()
        ],
```

This worked for me. `Storage` facade uses this system folder and hopefully the email views will be able to but so far running it from anywhere its using the desired folder

**Comment by innoflash** [comment]
Yeeeeeeeeeees it worked. So yeah i had been seeng the error because i forgot to include the `.env` file into box.json.

What works on a built app is setting the view.php > compiled to use system folder(files). In mine i used 
```php
//view.php

'compiled' => $_SERVER['HOME'] . '/my-dir/storage/framework/views'
```

PS: i had to create the `views` folder though
