### ISSUE TITLE
Why use laravel-zero/foundation instead of illuminate/foundation

### ISSUE THREAD

**Issue by innoflash** [laravel-zero/laravel-zero#285]
I know you guys are PHP kings and you certainly have a reason for that but i still have to ask.

Looks like when i run `composer update` the `laravel foundation` is not updated because we are using the one in `laravel-zero`

**Comment by nunomaduro** [comment]
I guess you found the answer yourself, but there is no illuminate/foundation.

**Comment by innoflash** [comment]
@nunomaduro i did notice there is a mirror of illuminate/foundation :). I closed this one because i saw an update on LaravelZero v7.5

It had all i needed this time.

Thanks for this awesome tool
