### ISSUE TITLE
Can`t require app from packagist

### ISSUE THREAD

**Issue by innoflash** [laravel-zero/laravel-zero#286]
So i been building some CLI app using Laravel Zero and its building and all. Now i am at a phase to distribute it via packagist and i am having the following issues when i run:

composer global require innoflash/larapack

![Screenshot from 2020-04-09 19-16-19](https://user-images.githubusercontent.com/12772919/78922558-0cb41400-7a97-11ea-8de3-bb06271dc3e8.png)

What have i possibly done wrong?

**Comment by mikeerickson** [comment]
Hello, apps created with Laravel-Zero are self contained CLI, they are not designed to be installed as dependencies into other applications.

**Comment by innoflash** [comment]
@mikeerickson thanks, so do we have a way of sharing them?

But i do remember using Packer by Bitfumes which he built on Laravel Zero

**Comment by mikeerickson** [comment]
Yes, it is a stand-alone cli application that is installed using composer require global xxx

**Comment by nunomaduro** [comment]
Maybe we can write more docs on this but:

1. Adds `"bin": ["builds/lambo"]` to composer json.
2. Adds `"exclude-dev-files": false,`.
3. Remove the framework as dependency 
4. Perform app: build.

Would be very cool if someone write a full section on docs on this.

**Comment by innoflash** [comment]
So i followed the steps given above by @nunomaduro and now i am getting the error with illuminate packages:

Does it mean i have to remove all dependencies when submitting to packagist? 


![Screenshot from 2020-04-10 10-32-12](https://user-images.githubusercontent.com/12772919/78976611-cef6d000-7b16-11ea-997f-13e742bff2b9.png)

**Comment by nunomaduro** [comment]
Show me your `composer.json`.

**Comment by innoflash** [comment]
@nunomaduro here it is.
https://github.com/innoflash/larapack/blob/master/composer.json

**Comment by owenvoke** [comment]
I think it would be good to add some information to the docs as Nuno has mentioned.
