### ISSUE TITLE
Allow for undefined commands to be passed to the default command

### ISSUE THREAD

**Issue by mattstauffer** [laravel-zero/laravel-zero#287]
In #211 there's a discussion about single-command apps.

However, that doesn't solve for my current use case, *but* my idea *does* solve that use case, *as well as* mine.

Here's my proposal:

Add a config toggle that sets it up so that the error generated by an un-defined console command, instead of bubbling up, is caught by Laravel Zero, and then the full parameter list is just passed to the default command.

Take [Lambo](https://github.com/tightenco/lambo) for example.

Currently I have a few small commands:
```
lambo edit-config
lambo edit-after
lambo help
```

But 90% of the interactions with the app happen with my `new` command.

When I wrote Lambo as a shell script, this was your syntax:

```
lambo myProject --flags
```

But with Laravel Zero as it is right now, I now have to force this syntax:

```
lambo new myProject --flags
```

If I could toggle "pass unmatched commands to default command", I could enable the old syntax again.

Thanks!

**Comment by owenvoke** [comment]
I think this sounds pretty useful, although as far as I know the underlying issue of arguments/options passed to the default command being ignored still exists so I'm not entirely sure how this could be implemented.

Unless it catches it using something like...
```php
try {} catch (CommandNotFoundException $exception) {
    $this->call($this->config->get('commands.default'), $arguments);
}
```

**Comment by mattstauffer** [comment]
Thanks Owen! That’s exactly what I was thinking. If I remember I’ll test that idea on Lambo on my stream tomorrow morning. If it works we can maybe see what it would look like to PR it to Zero.

**Comment by owenvoke** [comment]
That would be great! I'll make sure to watch the stream as usual. :+1:
