### ISSUE TITLE
Path issue while bundling package with box 

### ISSUE THREAD

**Issue by mrzainulabideen** [laravel-zero/laravel-zero#290]
I had the issue with laravel-zero/framework 7.0.
For me the issue was with the path of box file
The command `php %~dp0/box %*` does not get names with spaces in them so i used this `php "%~dp0box" %*`

Created PR on framework for this so nobody gets this particular error again.

**Comment by owenvoke** [comment]
Issue reference is https://github.com/laravel-zero/framework/pull/398. 👍 I'll take a look in a few minutes.

**Comment by owenvoke** [comment]
Thanks for that PR @mrzainulabideen 👍 I'll make a release soon.
