### ISSUE TITLE
Framework CI build tests failing

### ISSUE THREAD

**Issue by owenvoke** [laravel-zero/laravel-zero#296]
Currently the CI on the framework repository is failing. I first noticed this when updating the tests to use Pest, however since pushing a commit for release `v7.2.1`, the build is failing with PHPUnit as well.

This appears to just be a single test that fails, however all tests seem to pass when I run it locally on PHP 7.2, 7.3, and 7.4.

As far as I can tell, this appears to be related to an update to the `setup-php` action.
https://github.com/shivammathur/setup-php

- [With v2.1.4 (passing)](https://github.com/owenvoke/laravel-zero-framework/actions/runs/111872873)
- [With v2.2.0 (failing)](https://github.com/owenvoke/laravel-zero-framework/actions/runs/111880531)

Differences between these 2 versions [are here](https://github.com/shivammathur/setup-php/compare/2.1.4...2.2.0).

---

After further testing, this issue appears to have been introduced by commit https://github.com/shivammathur/setup-php/commit/0f3f6042491235c5ea8b71948528887d2d6d08fa, which added support for self-hosted runners. 🤔

I'm wondering if it's down to some permissions-related changes. 🤷

**Comment by shivammathur** [comment]
@owenvoke After `2.0.0` there hasn't been a breaking change. If you run the workflow with `2.1.4` again the same test-case will fail, it is most likely due to some dependency update in your project.

**Comment by owenvoke** [comment]
@shivammathur, this is re-running it with `v2.1.4` and it seems to pass. 🤔
https://github.com/owenvoke/laravel-zero-framework/actions/runs/111872873

**Comment by shivammathur** [comment]
@owenvoke Yes, there is a file ownership issue. I'm testing a patch, give me some time to push it and update the latest release

**Comment by owenvoke** [comment]
Thank you very much for your quick response!

**Comment by shivammathur** [comment]
Fixed in shivammathur/setup-php@190220c . It should now work with `2.2.2` release and `v2`.

**Comment by owenvoke** [comment]
I've re-run the jobs with `v2` and it's working. 👌 Thanks, that's brilliant!

Closing this issue as CI is now passing.
