### ISSUE TITLE
RunTime exception on standalone build

### ISSUE THREAD

**Issue by conveydk** [laravel-zero/laravel-zero#298]
When initiating build of standalone PHAR runtime exception is thrown:

➜  core-cli (master|✔) $ php ~/Projects/core-cli/core app:build core -v

In ArgvInput.php line 171:

  [Symfony\Component\Console\Exception\RuntimeException]
  Too many arguments, expected arguments "namespace".

Exception trace:
  at /Projects/core-cli/vendor/symfony/console/Input/ArgvInput.php:171
 Symfony\Component\Console\Input\ArgvInput->parseArgument() at /Projects/core-cli/vendor/symfony/console/Input/ArgvInput.php:82
 Symfony\Component\Console\Input\ArgvInput->parse() at /Projects/core-cli/vendor/symfony/console/Input/Input.php:55
 Symfony\Component\Console\Input\Input->bind() at /Projects/core-cli/vendor/symfony/console/Command/Command.php:214
 Symfony\Component\Console\Command\Command->run() at /Projects/core-cli/vendor/symfony/console/Application.php:912
 Symfony\Component\Console\Application->doRunCommand() at /Projects/core-cli/vendor/symfony/console/Application.php:264
 Symfony\Component\Console\Application->doRun() at /Projects/core-cli/vendor/symfony/console/Application.php:140
 Symfony\Component\Console\Application->run() at /Projects/core-cli/vendor/illuminate/console/Application.php:93
 Illuminate\Console\Application->run() at /Projects/core-cli/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Console/Kernel.php:129
 Illuminate\Foundation\Console\Kernel->handle() at /Projects/core-cli/vendor/laravel-zero/framework/src/Kernel.php:91
 LaravelZero\Framework\Kernel->handle() at /Projects/core-cli/core:37

Laravel Zero Framework 7
PHP 7.4

**Comment by owenvoke** [comment]
This is odd, I've been unable to replicate the issue. Could you let us know what OS you are using, and the exact version of the Laravel Zero framework? 🙂

**Comment by conveydk** [comment]
We are running macOS 10.15.5 Catalina.
Laravel Zero Framework v7.2.1

**Comment by owenvoke** [comment]
Hi, apologies for the delay on this. I'm still not able to replicate this issue on MacOS 10.15.5 with Laravel Zero v7.2.1 🤔

The only thing I can think of is another package providing an `app:build` command, but that's unlikely. Would you be able to post your Composer requirements list?

@dbpolito / @nunomaduro, any ideas on this one?

**Comment by conveydk** [comment]
No worries :). I migrated the project to a brand new mac and the issue arised.
Can it maybe be incompatibility with PHP 7.4?

{
    "name": "laravel-zero/laravel-zero",
    "description": "The Laravel Zero Framework.",
    "keywords": ["framework", "laravel", "laravel zero", "console", "cli"],
    "homepage": "https://laravel-zero.com",
    "type": "project",
    "license": "MIT",
    "support": {
        "issues": "https://github.com/laravel-zero/laravel-zero/issues",
        "source": "https://github.com/laravel-zero/laravel-zero"
    },
    "authors": [
        {
            "name": "Nuno Maduro",
            "email": "enunomaduro@gmail.com"
        }
    ],
    "require": {
        "php": "^7.2.5",
        "fduch/netrc": "^2.0",
        "kitetail/zttp": "^0.4.0",
        "laravel-zero/framework": "^7.0",
        "laravel/helpers": "^1.1",
        "nunomaduro/laravel-console-menu": "^2.1",
        "phlak/config": "^6.0",
        "laminas/laminas-text": "^2.7"
    },
    "require-dev": {
        "mockery/mockery": "^1.0",
        "phpunit/phpunit": "^7.5"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        },
        "files": [
            "app/Helpers/Helpers.php"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true
    },
    "scripts": {
        "post-create-project-cmd": [
            "@php application app:rename"
        ]
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "bin": ["core"]
}

**Comment by owenvoke** [comment]
Right, it doesn't seem to be a dependency issue. _sigh_ One other thing, could you post your `box.json` content here? 🤔

**Comment by conveydk** [comment]
{
    "chmod": "0755",
    "directories": [
        "app",
        "bootstrap",
        "config",
        "vendor"
    ],
    "files": [
        "composer.json"
    ],
    "exclude-composer-files": false,
    "compression": "GZ",
    "compactors": [
        "Herrera\\Box\\Compactor\\Php",
        "Herrera\\Box\\Compactor\\Json"
    ]
}

I can't quite figure out why the arguments aren't passed.

Too many arguments, expected arguments "namespace": Doesn't seem to be a common issue.

**Comment by owenvoke** [comment]
That looks pretty normal to me. 🤨

I mean, the only thing I can think of is that the app is in production mode for some reason (maybe through a build that was partially completed) and then the `app:build` command wouldn't be autoloaded. But that doesn't seem likely.

**Comment by conveydk** [comment]
After changing 'production' => 'false' to 'env' => 'development' in app.php build process started working.

**Comment by owenvoke** [comment]
Oh, it was just a config that hadn't been updated as per the [upgrade guide](https://laravel-zero.com/docs/upgrade/#upgrade-7.0.0)? No worries. 👍 Glad you managed to sort it. 🙂

**Comment by conveydk** [comment]
Yes. I followed all other upgrade steps but missed this particular step. Sorry for the inconvenience.

**Comment by owenvoke** [comment]
No problem, I'm going to close this issue. If you have any further problems, feel free to open a new one. 👍
