### ISSUE TITLE
Posix blocks execution on Windows system

### ISSUE THREAD

**Issue by def-studio** [laravel-zero/laravel-zero#299]
Hi, I've created a fresh laravel-zero executable in a Linux system:

`laravel-zero new dock`

I didn't install anything, nor added any code, just a fresh laravel-zero app

on my linux machine everything runs without any issue:

![image](https://user-images.githubusercontent.com/8792274/84018445-5aa6a480-a980-11ea-8e0b-7232a0fb5c9a.png)

if I run the build command:

`php dock app:build`

everything works fine and the phar build executes without any problem:

![image](https://user-images.githubusercontent.com/8792274/84018603-7d38bd80-a980-11ea-824b-0bcb92d51bc4.png)

BUT, if I move the executable on a windows system, here's the result:

![image](https://user-images.githubusercontent.com/8792274/84018706-993c5f00-a980-11ea-95b6-698ca423aa66.png)

How can I get rid of this error?

I don't see any package requiring `php-school/cli-menu` nor `php-school/terminal` but I still get the error

**Comment by def-studio** [comment]
This was just an error caused by an old version of my cli, not updated, sorry

**Comment by owenvoke** [comment]
No need to apologise 👍 Glad you sorted it.

**Comment by yoramdelangen** [comment]
@def-studio how did you solve this?

**Comment by def-studio** [comment]
@yoramdelangen It was just a typo in code, nothing related to laravel zero framework
