### ISSUE TITLE
$this->call() does not build commands like Artisan::call()

### ISSUE THREAD

**Issue by defunctl** [laravel-zero/laravel-zero#301]
`$this->call()` seems to place the command at the end the arguments, vs the first index of the array like `Artisan::call()`.

```
        $this->call( 'custom-command', [
            '--some-option',
            'hello',
            '-f',
            'forced',
        ] );
```
```
        Artisan::call( 'custom-command', [
            '--some-option',
            'hello',
            '-f',
            'forced',
        ] );
```

And in CustomCommand's `handle()` method.

`var_dump( (string) $this->input  );`

**$this->call()**

`--some-option hello -f forced custom-command`

**Artisan::call()**

`custom-command --some-option hello -f forced`

**Comment by owenvoke** [comment]
Hi @defunctl, sorry for the delayed reply. This is interesting. The [`call()` method in the `Command` class](https://github.com/laravel-zero/framework/blob/master/src/Commands/Command.php#L79) actually just calls the underlying [Laravel class'](https://github.com/laravel/framework/blob/7.x/src/Illuminate/Console/Concerns/CallsCommands.php#L26) method.

When `Artisan::call()` is run, it calls [the `Kernel::call()`](https://github.com/laravel/framework/blob/7.x/src/Illuminate/Foundation/Console/Kernel.php#L259) method which finally calls this:

https://github.com/laravel/framework/blob/730e7bf3c3139e7c3533f3e6838ae18515585b1f/src/Illuminate/Console/Application.php#L176

---

I guess the correct syntax would be the `Artisan::call()` one? Have you been able to replicate this issue in a normal Laravel app (if not, I'll try, but I'd assume it would be the same in both Laravel Zero and Laravel core)?

**Comment by defunctl** [comment]
Hi @owenvoke,

I have not tested this in a normal Laravel app, sorry :( 

I believe the correct syntax should also be `Artisan::call()`.

Thanks for the response.

**Comment by owenvoke** [comment]
Just tested on Laravel, looks like it does happen there as well. So this might be an issue with Laravel core. 🤔

![image](https://user-images.githubusercontent.com/1899334/85854209-de97c380-b7ab-11ea-9534-f774fc8fa97a.png)

**Comment by owenvoke** [comment]
I'm going to close this as I think the issue should be opened on the Laravel framework. 🤔

Basically I think this just comes down to the differences between [`Application::call()`](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Console/Application.php#L176) and [`CallsCommands::runCommand()`](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Console/Concerns/CallsCommands.php#L51).
