### ISSUE TITLE
 Fatal error: Uncaught ReflectionException: Class config does not exist

### ISSUE THREAD

**Issue by Ahmard** [laravel-zero/laravel-zero#302]
I created configuration file located at "./config/test.php" directory and i tried loading it using `config('test.hello');` and i got the below error

`Fatal error: Uncaught ReflectionException: Class config does not exist in /storage/emulated/0/www/vendor/illuminate/container/Container.php:805 Stack trace: #0 /storage/emulated/0/www/vendor/illuminate/container/Container.php(805): ReflectionClass->__construct('config') #1 /storage/emulated/0/www/vendor/illuminate/container/Container.php(687): Illuminate\Container\Container->build('config') #2 /storage/emulated/0/www/vendor/illuminate/container/Container.php(633): Illuminate\Container\Container->resolve('config', Array) #3 /storage/emulated/0/www/vendor/laravel-zero/foundation/src/Illuminate/Foundation/helpers.php(119): Illuminate\Container\Container->make('config', Array) #4 /storage/emulated/0/www/vendor/laravel-zero/foundation/src/Illuminate/Foundation/helpers.php(275): app('config') #5 /storage/emulated/0/www/app/Test.php(18): config('test.hello') #6 /storage/emulated/0/www/app/Router.php(12): App\Test->__construct in /storage/emulated/0/www/vendor/illuminate/container/Container.php on line 807`

**Comment by owenvoke** [comment]
Hi @Ahmard, I just set up a fresh Laravel Zero instance, added a `config/test.php` containing the following:

```php
<?php return ['hello' => 'world'];
```

And calling `dd(config('test.hello'));` worked as expected with the correct value. Could you perhaps provide the contents of the `test.php` file? 🙂

**Comment by Ahmard** [comment]
Yeah you are right.
I run the code through http, i was reckless, forgetting that Laravel-Zero will not load the framework.
Sorry for wasting your time.

**Comment by owenvoke** [comment]
No need to apologise. :+1: Glad you sorted your issue.
