### ISSUE TITLE
Emergency logging

### ISSUE THREAD

**Issue by yoramdelangen** [laravel-zero/laravel-zero#303]
I encountered a problem for error logging in a builded phar: 

I didn't register a database connection within my .env file. causing my migrate command to fail before the AppServiceProvider updated my configuration for logging. 

In cases of "emergency" the Laravel logger tries to log into an "emergency channel" if defined else it uses `storage_path`. 
[Source can be found here](https://github.com/laravel/framework/blob/7.x/src/Illuminate/Log/LogManager.php#L164-L177)

Perhaps its something worth mentioning within the docs?

**Comment by owenvoke** [comment]
I think this is kind of mentioned in the [Logging documentation](https://laravel-zero.com/docs/logging/)? If there are any changes you'd like to suggest or ways to make it clearer, feel free to open a pull request, or let us know. 👍

**Comment by yoramdelangen** [comment]
I will try and create a reproduce the issue.

**Comment by octoper** [comment]
Hi @yoramdelangen have you reproduced this issue?

**Comment by nunomaduro** [comment]
Close pending inactivity.

**Comment by yoramdelangen** [comment]
No, I couldn't. Didn't encounter the issues again. One time happening I guess
