### ISSUE TITLE
Extending command

### ISSUE THREAD

**Issue by loranger** [laravel-zero/laravel-zero#304]
Hello,

My app is a “modules“ manager. Each module is a git repository and I need to know where those repositories are stored locally on each dev machine..

I fought with the writing files issues and finally used the [XDG package](https://packagist.org/packages/dnoegel/php-xdg-base-dir) as suggested by [matt-allan](https://github.com/laravel-zero/laravel-zero/issues/177#issuecomment-490134204) in order to store the modules root path in a _config dotfile_.

I also had to find a way to [dynamically define](https://stackoverflow.com/a/50464178) the modules path as a storage disk on runtime, using the _config dotfile_.

Now I need to check if the _config dotfile_ exists each time a command is call and fallback onto the config command which prompt for the path and generates the _config dotfile_ before trying to handle the command.

I could copy paste the code on each command but that's not DRY and not really maintainable.
I tried to extend my commands with a parent command wrapping the _config dotfile_ verification, but this parent needs a signature, and is exposed as a command too. I could hide it using the `$hidden` attribute, but it results with hiding all the inherited commands.

Here is my question : How can I extends commands using Laravel-zero, or how can I add such a middleware in order to mutualize check or verification on some commands ?

**Comment by owenvoke** [comment]
Hi @loranger, sorry for the late reply. Could you use an abstract class that extends the core Command class, and just store it outside of the `app\Commands` directory so it doesn't get autoloaded in the list? Alternatively maybe this could be in a trait?

**Comment by octoper** [comment]
@loranger have you fixed that?

**Comment by loranger** [comment]
Sorry…
Yes it was exactly what I was looking for, thanks @owenvoke !

**Comment by owenvoke** [comment]
No need to apologise, glad you sorted it. 👍🏻
