### ISSUE TITLE
chore: start preparing next version of laravel zero 8

### ISSUE THREAD

**Issue by owenvoke** [laravel-zero/laravel-zero#305]
Work for this will be implemented in the [`develop` branch](https://github.com/laravel-zero/framework/tree/develop).

- [x] Update to use Pest for test suite
- [x] Update to stable Pest version ([v0.3 PR](https://github.com/laravel-zero/framework/pull/403))
- [x] Update dependencies (Collision 5, etc.)
- [x] Update Illuminate dependencies to v8
- [x] Update LZ components (see list below)
- [x] Update to support PHP 8 (https://github.com/laravel-zero/framework/pull/409)
- [x] Deprecate the installer
- [x] Publish the foundation (and update the [reference in the framework](https://github.com/laravel-zero/framework/blob/develop/composer.json#L30))
- [x] Publish the framework (and update the [reference in the main repo](https://github.com/laravel-zero/laravel-zero/blob/develop/composer.json#L20))
- [x] Update the [Upgrade Guide](https://github.com/laravel-zero/website/blob/gh-pages/source/docs/upgrade.md) (https://github.com/laravel-zero/website/pull/51)
- [x] Update any other docs on the website
- [x] Write blog post about the changes, etc. (https://voke.dev/blog/whats-new-in-laravel-zero-8)

**Component checklist**

- [x] Console Dusk
- [x] Database
- [x] DotEnv
- [x] Http
- [x] Log
- [x] Logo
- [x] Menu
- [x] Queue
- [x] Schedule List
- [x] Self Update

**Comment by nunomaduro** [comment]
This sounds good to me, can you add `upgrade-guide.md`, and blogpost?

**Comment by owenvoke** [comment]
Waiting on [`hmazter/laravel-schedule-list`](https://github.com/hmazter/laravel-schedule-list) to release a version that includes https://github.com/hmazter/laravel-schedule-list/commit/887e7df4a4b30656532d7d71a0e23445f69a8fc3
