### ISSUE TITLE
Issues with finding Laravel Zero classes after app:build

### ISSUE THREAD

**Issue by damcclean** [laravel-zero/laravel-zero#307]
I'm building my first Laravel Zero application so I may be doing things wrong. 

Basically, my issue is that whenever I run `php application app:build` on my Laravel Zero app, the binary file compiles without any issues. However, when I try and run the built binary, either through `./builds/app` or via a globally installed Packagist version, it still fails, saying it can't find Laravel Zero's `Application` class.

```
PHP Fatal error:  Uncaught Error: Class 'LaravelZero\Framework\Application' not found in phar:///Users/duncan/Sites/package-bootstrapper/builds/fabric/bootstrap/app.php:14
Stack trace:
#0 phar:///Users/duncan/Sites/package-bootstrapper/builds/fabric/fabric(19): require_once()
#1 /Users/duncan/Sites/package-bootstrapper/builds/fabric(14): require('phar:///Users/d...')
#2 {main}
  thrown in phar:///Users/duncan/Sites/package-bootstrapper/builds/fabric/bootstrap/app.php on line 14

Fatal error: Uncaught Error: Class 'LaravelZero\Framework\Application' not found in phar:///Users/duncan/Sites/package-bootstrapper/builds/fabric/bootstrap/app.php:14
Stack trace:
#0 phar:///Users/duncan/Sites/package-bootstrapper/builds/fabric/fabric(19): require_once()
#1 /Users/duncan/Sites/package-bootstrapper/builds/fabric(14): require('phar:///Users/d...')
#2 {main}
  thrown in phar:///Users/duncan/Sites/package-bootstrapper/builds/fabric/bootstrap/app.php on line 14
```

Here's a [link to the source code](https://github.com/steadfast-collective/fabric) of the application I'm working on.

I'm not sure if this is related but I recently changed the code directory from `app` to `src` on the application to structure it like a normal Laravel package. I wonder if that could be the issue?

**Comment by damcclean** [comment]
Just converted my package back to the `/app` folder but I still get the same error when I run my built binary (I rebuilt after moving the files around, obviously)

**Comment by owenvoke** [comment]
If your Laravel Zero dependency is in the Composer `require-dev` section, then you'll need to add `exclude-dev-files` to your `box.json` configuration file. 👍🏻

**Comment by damcclean** [comment]
@owenvoke Ah... that makes sense. Everything works now. Thanks for your quick help!

**Comment by owenvoke** [comment]
No problem! Glad it's sorted. 👏🏻

**Comment by nunomaduro** [comment]
@damcclean Add something to the docs, if you think is missing.
