### ISSUE TITLE
Increase timeout when using app:install

### ISSUE THREAD

**Issue by evaleries** [laravel-zero/laravel-zero#315]
## The Problem
While installing the add-on via `php <application name> app:install` I found an error that was caused by a default execution timeout (5 mins). It doesn't matter whether the process is almost complete or completely fail, anything that exceeded the maximum execution time it will throw an error.
This problem can be occurred by anyone who has a poor network connection. Because this looks normal to me when using a composer that consumes a time more than 5 minutes.

## The Question
How do I increase a timeout for a process like `php <application name> app:install menu --timeout 7` to maximize timeout that will last for 7 minutes?

## My own solution
Using composer directly to install add-on `composer require nunomaduro/laravel-console-menu "^3.1"`

## Error
```bash
~/projects/laravel-zero via 🐘 v7.4.3 
➜ php lazero app:install menu
Installing menu component...
Require package via composer: loading...
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 4 installs, 0 updates, 0 removals
  - Installing php-school/terminal (0.2.1): Downloading (100%)         
  - Installing beberlei/assert (v3.2.7): Downloading (100%)         
  - Installing php-school/cli-menu (4.0.0): Downloading (100%)         
  - Installing nunomaduro/laravel-console-menu (v3.1.0): Downloading (100%)         
Writing lock file
Generating optimized autoload files
Require package via composer: failed

   Symfony\Component\Process\Exception\ProcessTimedOutException 

  The process "composer require nunomaduro/laravel-console-menu "^3.1"" exceeded the timeout of 300 seconds.

  at vendor/symfony/process/Process.php:1201
    1197▕ 
    1198▕         if (null !== $this->timeout && $this->timeout < microtime(true) - $this->starttime) {
    1199▕             $this->stop(0);
    1200▕ 
➜ 1201▕             throw new ProcessTimedOutException($this, ProcessTimedOutException::TYPE_GENERAL);
    1202▕         }
    1203▕ 
    1204▕         if (null !== $this->idleTimeout && $this->idleTimeout < microtime(true) - $this->lastOutputTime) {
    1205▕             $this->stop(0);

  1   vendor/symfony/process/Process.php:413
      Symfony\Component\Process\Process::checkTimeout()
 .... (another vendor stacktrace) 
```

**Comment by owenvoke** [comment]
So currently this is hardcoded in the framework's Composer provider.
https://github.com/laravel-zero/framework/blob/master/src/Providers/Composer/Composer.php#L87

I guess it could be possible to allow configuring it via the constructor, and then it would be set in the service provider. With the configurable config value as `app.composer_timeout`. 🤷🏻 I'll have a look at a PR later today to see whether that would work nicely.

**Comment by owenvoke** [comment]
So after discussing with Nuno, he mentioned to just increase the timeout to 900 or something rather than having it customisable (like in https://github.com/laravel-zero/framework/pull/416). Would this be ok? 🤔

**Comment by nunomaduro** [comment]
I think that would be ok @owenvoke.

**Comment by evaleries** [comment]
Looks good to me, thanks for the work @owenvoke
