### ISSUE TITLE
License file missing

### ISSUE THREAD

**Issue by spekulatius** [laravel-zero/laravel-zero#316]

**Comment by owenvoke** [comment]
The project is licensed as MIT. I assume this was excluded as this is a template repository, so people can choose the license they want. @nunomaduro, should a LICENSE be added, and we just add it to the `.gitattributes` so that it gets excluded from a `composer create-project`?

**Comment by nunomaduro** [comment]
It's good this way. Just like Laravel's template.

**Comment by spekulatius** [comment]
Okay, cool. I noticed it originally because the readme link. I guess that can go then... People replace the readme anyways I assume...
