### ISSUE TITLE
Commands from app/Commands not loaded within standalone application

### ISSUE THREAD

**Issue by nhedger** [laravel-zero/laravel-zero#317]
Hi there,

I'm currently playing with Laravel Zero and I think I may have stumbled upon an issue. It is my understanding that every command added to the `app/Commands` directory will be loaded and made available to the application unless specifically excluded. If that is not correct please let me know.

### The issue

When the application is packed as standalone, it seems not to be loading the commands from the `app/Commands` folder unless the command is specifically added to the `add` configuration array in `config/commands.php`.

### Relevant information

- **OS:** macOS Catalina v10.15.7
- **PHP version:** PHP 7.4.11 (cli) (built: Oct  1 2020 23:30:54) ( NTS )
- **Laravel Zero version:** 8.0

### Steps to reproduce

1. Create a new Laravel Zero application: `laravel-zero new zero-issue`
2. Run the application `./application`
3. See that the _Inspiring_ command is listed
```
  Application  unreleased

  USAGE: application <command> [options] [arguments]

  inspiring    Display an inspiring quote
  test         Run the application tests

  app:build    Build a single file executable
  app:install  Install optional components
  app:rename   Set the application name

  make:command Create a new command

  stub:publish Publish all stubs that are available for customization
```
4. Build the standalone application: `php application app:build application`
5. Run the standalone application: `builds/application -vvv`
6. See that the _Inspiring_ command is **not** listed:
```
Box Requirements Checker
========================

> Using PHP 7.4.11
> PHP is using the following php.ini file:
  /usr/local/etc/php/7.4/php.ini

> Checking Box requirements:
  ✔ The application requires the version "^7.3" or greater.
  ✔ The application requires the extension "zlib".
  ✔ The package "brick/math" requires the extension "json".
  ✔ The package "illuminate/support" requires the extension "json".
  ✔ The package "laravel-zero/framework" requires the extension "json".
  ✔ The package "nesbot/carbon" requires the extension "json".
  ✔ The package "ramsey/uuid" requires the extension "json".
  ✔ The package "league/flysystem" requires the extension "fileinfo".
  ✔ The package "league/mime-type-detection" requires the extension "fileinfo".
  ✔ The package "vlucas/phpdotenv" requires the extension "pcre".
  
                                                                                
 [OK] Your system is ready to run the application.                              
                                                                                


  Application  unreleased

  USAGE: application <command> [options] [arguments]
```
7. Add the the _Inspiring_ command to the `add` array in `config/commands.php`:
```php
'add' => [
     \App\Commands\InspiringCommand::class
],
```
8. Build the standalone application once more: `php application app:build application`
9. Run the standalone application: `builds/application -vvv`
10. See that the _Inspiring_ command is now listed
```
Box Requirements Checker
========================

> Using PHP 7.4.11
> PHP is using the following php.ini file:
  /usr/local/etc/php/7.4/php.ini

> Checking Box requirements:
  ✔ The application requires the version "^7.3" or greater.
  ✔ The application requires the extension "zlib".
  ✔ The package "brick/math" requires the extension "json".
  ✔ The package "illuminate/support" requires the extension "json".
  ✔ The package "laravel-zero/framework" requires the extension "json".
  ✔ The package "nesbot/carbon" requires the extension "json".
  ✔ The package "ramsey/uuid" requires the extension "json".
  ✔ The package "league/flysystem" requires the extension "fileinfo".
  ✔ The package "league/mime-type-detection" requires the extension "fileinfo".
  ✔ The package "vlucas/phpdotenv" requires the extension "pcre".
  
                                                                                
 [OK] Your system is ready to run the application.                              
                                                                                


  Application  unreleased

  USAGE: application <command> [options] [arguments]

  inspiring Display an inspiring quote
```

### Expected behaviour

I'm expecting the Inspiring command to be listed in the standalone application, just as **it is listed when the application is ran in development mode**.

**Comment by owenvoke** [comment]
That definitely doesn't seem right. 🤔 I haven't experienced this before, but I can replicate the issue.

**Comment by owenvoke** [comment]
Apologies, wasn't intending to close this with the commit. But updating to v8.9.1 of the Foundation should resolve this issue. 👍🏻 Let me know if you have any further problems.

**Comment by nhedger** [comment]
Hi @owenvoke ! No harm done. Thanks for your quick reply. I will definitely check this ASAP. Have a nice day.

**Comment by nhedger** [comment]
Everything works as expected @owenvoke . I've kicked you a few bucks on Github Sponsors as a thank you.

**Comment by owenvoke** [comment]
Wow! Thank you. 🥳 Hope you have a great day. 👍🏻
