### ISSUE TITLE
How to use Blade?

### ISSUE THREAD

**Issue by monkeymonk** [laravel-zero/laravel-zero#319]
Hello there,

I cannot find a way to use Blade inside of my laravel-zero command... at best I have a "ReflectionException  : Class view does not exist".

Any help?

Thank you.

**Comment by owenvoke** [comment]
Laravel Zero isn't really designed to be used with Blade as it's a CLI framework.

I think you need to have `illuminate/view` installed, and then add the `Illuminate\View\ViewServiceProvider` to your list of providers. There are probably other services that are depended on as well though.
