### ISSUE TITLE
Standalone - Runtime Error

### ISSUE THREAD

**Issue by mokchend** [laravel-zero/laravel-zero#320]
Hello,
After generating the stand alone file, when executing it have the following error:
Any idea on how to solve this ?
PS: By the way congrat for this remarquable tools for thoses who still like command line in 2020 :-) 

Box Requirements Checker
========================

> Using PHP 7.4.12
> PHP is using the following php.ini file:
  WARNING: No configuration file (php.ini) used by PHP!

> Checking Box requirements:
  ........EE.

 [ERROR] Your system is not ready to run the application.

Fix the following mandatory requirements:
=========================================

 * The package "league/flysystem" requires the extension "fileinfo". Enable it
   or install a polyfill.
 * The package "league/mime-type-detection" requires the extension "fileinfo".
   Enable it or install a polyfill.

**Comment by owenvoke** [comment]
As mentioned in the requirements, you'll need to enable the `fileinfo` extension. You can do this by adding `extension = fileinfo` to your `php.ini`. 👍🏻

**Comment by mokchend** [comment]
Sorry I have missed this information. I will close this issue. 
Congrats team for this apps !
