### ISSUE TITLE
Ability to add controller

### ISSUE THREAD

**Issue by mokchend** [laravel-zero/laravel-zero#321]
Hello,

This request sounds strange at a first glance, but I have a use case where I want to integrated Laravel Library (https://github.com/omniphx/forrest) which require Controller to work . For example in a situation where I need to interact with Oauth/OIDC Flow which require interaction with browser.
How should I handle this use case ?

**Comment by owenvoke** [comment]
I don't really know if this is easily possible. Laravel Zero has most of the web components stripped out, so it would basically be putting all those back in to use a controller. 🤔 I mean, you can try installing that package and adding the service provider to your `config/app.php` which should throw errors about all the service providers/packages you'll need to add the functionality back in.

When working with OAuth, I've previously just opened the browser and waited until it retrieves a response. Similar to how [the `gh` CLI tool works](https://github.com/cli/cli/blob/trunk/auth/oauth.go). Or just ask for the details to be entered and then the CLI tool does the OAuth calls.
