### ISSUE TITLE
problem in Autoloading of packages

### ISSUE THREAD

**Issue by hh7843175** [laravel-zero/laravel-zero#323]
Hi there,

I've created a simple/sample package for testing , my packages is:

> https://github.com/hh7843175/asntest/

after installing through composer

> composer require nasn/asn

 I have to add it manually in the `providers` section of `config/app.php`. I guess there is a problem in Autoloading/Autodiscovery process cause the package works properly in Laravel!

I have no idea what is happening there, thank you so much for any hint.

Alex.

**Comment by owenvoke** [comment]
There is currently no autoloading of package service providers in Laravel Zero. We have thought about adding this though.

**Comment by hh7843175** [comment]
Thanks @owenvoke , Do you have this feature in your backlog ?
