### ISSUE TITLE
Question: PHP8 Support

### ISSUE THREAD

**Issue by tomasnorre** [laravel-zero/laravel-zero#324]
Hi. 

I know you have a lot on your plate, but do you have any timeline for the PHP8 update?

If I can support you in any way, please let me know.

**Comment by owenvoke** [comment]
We are just waiting on PHP 8 support in Box. Once that's released, we'll create a release that's compatible with PHP 8. 👍🏻

You can follow the progress of PHP 8 support in https://github.com/laravel-zero/framework/pull/421 as well. 🙂

**Comment by tomasnorre** [comment]
Thanks, then no need to keep this open.
