### ISSUE TITLE
Add support for parallel testing

### ISSUE THREAD

**Issue by owenvoke** [laravel-zero/laravel-zero#333]
[Foundation v8.27.0](https://github.com/laravel-zero/foundation/compare/v8.23.1...v8.27.0) added support for parallel testing in the `test` command. However, this is currently broken as per the notes in https://github.com/laravel-zero/foundation/pull/52.

![Preview of console error](https://user-images.githubusercontent.com/1899334/106117977-819e2a80-614b-11eb-877d-8253975253c8.png)

The issue appears to be related to the use of `$app['config']` in [`LaravelZero\Framework\Bootstrap\LoadConfiguration`](https://github.com/laravel-zero/framework/blob/master/src/Bootstrap/LoadConfiguration.php#L38-L39). I think this is because `config()` is a function/closure, so the app appears to try and instantiate this when checked with `$this->isBuildable($concrete, $abstract)` in the container resolution. 🤔

If we remove the `Artisan::starting` block the parallel testing works, however the actual application then has the wrong version and name.

---

On a side note, running Paratest directly using `LARAVEL_PARALLEL_TESTING=1 ./vendor/bin/paratest` works fine. 🤷🏻

**Comment by kzvonov** [comment]
@owenvoke Hello 👋 
Do you want `--parallel` flag working? 
If the issue is still here, I think I can try to take this one.

**Comment by owenvoke** [comment]
@kzvonov, if you're able to work on this, that would be brilliant! Sorry I haven't really had time recently to work on Laravel Zero much unfortunately.

**Comment by kzvonov** [comment]
@owenvoke yep, I will try to get into this today's evening or tomorrow.

Thanks for the trust)

**Comment by owenvoke** [comment]
Any issues, feel free to ping me in a comment. 👍🏻

**Comment by kzvonov** [comment]
@owenvoke Hello! 
I've updated compose.json, and then `--parallel` works for me https://github.com/Zvonov-Devs/laravel-zero/commit/19c4e604d47a45adf6b83240790ebcb02c01fae3

But as I understand the issue in `laravel-zero/foundation` with version `8.27.0`. Am I right that I need to change my `composer.lock` file and then try with an older foundation? if the answer is **yes** then it's also working
![Screenshot 2021-09-22 at 14 50 36](https://user-images.githubusercontent.com/7114795/134338538-83278c5d-41e4-4985-acc9-a764595ef7fa.png)
The same 👌  result I got when run with `laravel-zero/foundation` with version `8.26.0`.

Did I miss something?

**Comment by owenvoke** [comment]
Hmm, that's weird... perhaps it's an issue on my local setup. 🤔 It seems to be working fine for me now too! That's great. 😬 I have no idea what the issue was then... And I guess this can be closed, thank you for testing!

**Comment by kzvonov** [comment]
@owenvoke no problem) But can you give me another issue to work on?

**Comment by owenvoke** [comment]
@kzvonov, I think the main things are just:
- Making sure Laravel Zero supports PHP 8.1, which I'm currently looking into
- Going through any of the old issues in the issues tab and working through them

Personally this was the main issue I wanted to try and fix.
https://github.com/laravel-zero/laravel-zero/issues/343
