### ISSUE TITLE
Class "Illuminate\Queue\Queue" not found

### ISSUE THREAD

**Issue by zembrowski** [laravel-zero/laravel-zero#335]
After running `composer update` the `laravel-zero/foundation` dependency gets updated to 8.29.

Running `vendor/bin/pest` produces the following error:

> Class "Illuminate\Queue\Queue" not found

This seems to be happening due to this commit https://github.com/laravel-zero/foundation/commit/44462ae66d34296cddb895e60418b2565b24b04e

How could I fix this error?

**Comment by owenvoke** [comment]
Ah, I'll provide an update for this. 👍🏻 I forgot that the queue driver isn't included by default. 🤔

Could you try installing `v8.29.1` of the foundation? (Should work with a `composer update`)
