### ISSUE TITLE
Path helpers not working

### ISSUE THREAD

**Issue by srdante** [laravel-zero/laravel-zero#339]
Path helpers which seems to be included on the code do not work as expected.

## Base path:
```php
base_path();
```

Throws:
```
Call to undefined method Illuminate/Container/Container::basePath()
```

## Storage path:
```php
storage_path();
```

Throws:
```
Illuminate/Contracts/Container/BindingResolutionException with message 'Target class [path.storage] does not exist.'
```

I´ve also testes ``app_path()``, ``config_path()`` and both don't work too.

**Comment by srdante** [comment]
This only occurs when using tinkerwell.

**Comment by srdante** [comment]
However, I checked that tinkerwell has a driver to detect laravel zero. However mine does not detect anything.

I reproduced the detection function of the driver inside the own Tinkerwell using: 
```php
file_exists(__DIR__ . '/bootstrap/app.php') && is_dir(__DIR__ . '/vendor/laravel-zero/framework');
```
and it's returning true, I don't know why the laravel zero tinkerwell driver is not being used/detected.

**Comment by owenvoke** [comment]
@srdante, I'm not sure whether this is an issue with Laravel Zero, or even the driver. 🤔 Do you mind trying to copy [the `LaravelZeroTinkerwellDriver.php`](https://github.com/tinkerwellapp/drivers/blob/master/src/Drivers/LaravelZeroTinkerwellDriver.php) to a `.tinkerwell` directory in your project and then refreshing the directory?

I've tried that on my Tinkerwell and it works great, however the [built-in "drivers"](https://github.com/tinkerwellapp/drivers) don't seem to load for me.

**Comment by srdante** [comment]
When copying the file to a .tinkerwell folder worked. But because this driver is in the official tinkerwell repository, wasn’t it supposed to be working automatically?

**Comment by owenvoke** [comment]
Yes. We might need to ask the people at Beyond Code about this. 👍🏻
