### ISSUE TITLE
Validetor

### ISSUE THREAD

**Issue by pcualmac** [laravel-zero/laravel-zero#344]
Dear All,

I got many problem with use of Validator. 

I have tried different way.

Can same one post an example Validator in a command?

OR

Can same one  let me now how importe the validator from "Laravel"

Please.

Thanks

@dbpolito, @vojtasvoboda , @Bogardo,

**Comment by pcualmac** [comment]
to @nunomaduro

Thanks for replay but I still have the problem.
Can you help me? please

**Comment by owenvoke** [comment]
Could you let us know what problems you are getting, any error messages or notices? A screenshot?

**Comment by pcualmac** [comment]
```bash
php image-Basekit-cli tinker
use Validator;
$tem = Validator::make([],[]);
<warning>PHP Warning:  Class 'LaravelZero\Framework\Bootstrap\Illuminate\Support\Facades\Validator' not found in /var/www/vhosts/image-Basekit-cli/vendor/laravel-zero/foundation/src/Illuminate/Foundation/AliasLoader.php on line 80</warning>
PHP Error:  Class 'Validator' not found in /var/www/vhosts/image-Basekit-clieval()'d code on line 1
```

```bash
php image-Basekit-cli tinker
use Illuminate\Support\Facades\Validator;
$tem = Validator::make([],[]);
Illuminate\Contracts\Container\BindingResolutionException with message 'Target class [validator] does not exist.'
```

It is same if I use the code inside to Comand.

I have tried 
composer require illuminate/support illuminate/validation

**Comment by pcualmac** [comment]
Can reopen this ticket

**Comment by pcualmac** [comment]
Sorted 

Thanks

**Comment by owenvoke** [comment]
Apologies, I was away for a bit. Did you register the `Illuminate\Validation\ValidationServiceProvider` service provider in your `config/app.php`?

**Comment by irineujunior** [comment]
Hi, maybe this can help.

```
composer require illuminate/support illuminate/validation
```

On `config/app.php`
```
...
    'providers' => [
        App\Providers\AppServiceProvider::class,
        \Illuminate\Validation\ValidationServiceProvider::class,
        \Illuminate\Translation\TranslationServiceProvider::class,
    ],
...
```

In our app
```
    $validator = app('validator')->make(['email' => $email], ['email' => 'email:rfc,dns']);
    if ($validator->fails()) {
        $this->error("O email {$email} é inválido");
        die();
    }
```
