### ISSUE TITLE
Posix extension issue on windows

### ISSUE THREAD

**Issue by zeevx** [laravel-zero/laravel-zero#345]
Please help me, how can i fix this?

**Comment by owenvoke** [comment]
There shouldn't be an issue anymore as far as I know. I use Windows for a lot of my command line development for work using Laravel Zero, could you provide a screenshot of the error, and if possible specify the version of Laravel Zero you are using. Any reproducible repository would be helpful too. 👍🏻

**Comment by zeevx** [comment]
Good day Owen, thanks for your response.

Here is the error I get on windows:
Problem 1 - php-school/cli-menu[4.0.0, ..., 4.1.0] require ext-posix * -> it is missing from your system. Install or enable PHP's posix extension.  

My Composer.json:

"require": {
        "php": "^7.3|^8.0",
        "ext-json": "*",
        "guzzlehttp/guzzle": "^6.5.5",
        "laravel-zero/framework": "^8.9",
        "illuminate/http": "^8.0",
        "illuminate/log": "^8.0",
        "laminas/laminas-text": "^2.8",
        "laravel-zero/phar-updater": "^1.0.6",
        "nunomaduro/laravel-console-menu": "^3.2"
    },
    "require-dev": {
        "fakerphp/faker": "^1.9.1",
        "mockery/mockery": "^1.4.3",
        "pestphp/pest": "^1.3"
    },

**Comment by owenvoke** [comment]
Ah, unfortunately I don't think the Console component (which uses [`nunomaduro/laravel-console-menu`](https://github.com/nunomaduro/laravel-console-menu) / [`php-school/cli-menu`](https://github.com/php-school/cli-menu) under the hood) supports Windows.

**Comment by owenvoke** [comment]
I'm going to close this as it's not really a Laravel Zero issue. I may add a notice when installing that notes the "Menu Component" isn't compatible with Windows.
