### ISSUE TITLE
  Method performTask does not exist.

### ISSUE THREAD

**Issue by ardzz** [laravel-zero/laravel-zero#346]
Method App\Commands\TopicsCommand::performTask does not exist.

Do laravel-zero support performTask like laravel 8?

source [https://laravel.com/docs/8.x/artisan#command-io](https://laravel.com/docs/8.x/artisan#command-io)

**Comment by owenvoke** [comment]
I can see the reference to `performTask()` in the docs, however I can't find any reference in [the Console package](https://github.com/illuminate/console), on Symfony Console, or in the framework. Any ideas where this actually is? 🤔
