### ISSUE TITLE
ascii logo instead of figlet

### ISSUE THREAD

**Issue by necrogami** [laravel-zero/laravel-zero#349]
So I am working on an internal project and we have an ascii logo.

I looked into the logo module you have and I don't see an easy way of overloading my logo into the help menu instead of the figlet.

Is there a good way about doing this or can this be made an easy option?

**Comment by sixlive** [comment]
Hey!

You can set it in the `AppServiceProvider::register` method.

```php
    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
       \Illuminate\Console\Application\App::starting(
           function ($artisan) {
               $artisan->setName(<<<EOF

                    ███          ▄█
                ▀█████████▄     ███
                   ▀███▀▀██     ███
                    ███   ▀     ███
                    ███         ███
                    ███         ███
                    ███         ███
                   ▄████▀   █▄ ▄███
                            ▀▀▀▀▀▀

               EOF);
           }
        );
    }
 ```
 
 
<img width="502" alt="image" src="https://user-images.githubusercontent.com/5108034/146858857-00703a18-76d5-490f-bac5-11d1ccf6a38b.png">

**Comment by owenvoke** [comment]
Apologies, somehow I missted this notification @necrogami. Alternatively, you can change the font by updating your `logo.font` configuration string. For example:
```php
    'font' => app_path('resources/3d.flf'),
```

There are a bunch of available fonts [in this repository](https://github.com/xero/figlet-fonts) which should all work with Figlet, and I'm happy to assist if they need tweaks to work. 👍🏻
