### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by bnomei** [laravel-zero/laravel-zero#359]
https://laravel-zero.com/

**Comment by nunomaduro** [comment]
We are working on it.

**Comment by owenvoke** [comment]
This is a known issue, Nuno is working on it. 👍🏻

**Comment by wpoortman** [comment]
Any updates on this matter?

**Comment by owenvoke** [comment]
@wpoortman, I've just asked Nuno for an update.

**Comment by nunomaduro** [comment]
We are working on it. I din't get an response from the domain provider yet.
