### ISSUE TITLE
laravel-zero.com is inaccessible

### ISSUE THREAD

**Issue by JuhaniGeniem** [laravel-zero/laravel-zero#360]
The website is nowhere to be found.

**Comment by owenvoke** [comment]
Please look over at #359 👍🏻 It's known by Nuno and is being resolved.

**Comment by wpoortman** [comment]
> Please look over at #359 👍🏻 It's known by Nuno and is being resolved.

The issue is already closed but the website is still down.

**Comment by owenvoke** [comment]
Looks like it's now [back up again](https://laravel-zero.com), so closing this issue. Thanks. 👍🏻
