### ISSUE TITLE
Add Optinable Visual Interface (via VladReshet/ArtisanUi package)

### ISSUE THREAD

**Issue by VladReshet** [laravel-zero/laravel-zero#361]
Hi! 

I want to propose you to add this package https://github.com/VladReshet/ArtisanUI to your project, to have it "out of the box". I have just tested it - it already works on Laravel Zero without any changes, it's necessary just to install it and register command (Laravel does it by itself).

![Image](https://habrastorage.org/webt/gx/ea/g5/gxeag570yxla64pqaqnst9lilp8.jpeg)

I can create pull request, if you find that as an interesting idea

Thanks!

**Comment by owenvoke** [comment]
I'm not sure that this should be provided out of the box, I'd be happy with this as [a new component](https://github.com/laravel-zero/framework/tree/master/src/Components). But @nunomaduro, what are your thoughts?

**Comment by nunomaduro** [comment]
No plans for this.
