### ISSUE TITLE
Empty box.json, any way to generate it ?

### ISSUE THREAD

**Issue by Erwyn** [laravel-zero/laravel-zero#362]
Hi there,

for whatever reason my `box.json` file is empty. Is there a way to generate/regenerate it ?

Thanks in advance,

**Comment by nunomaduro** [comment]
You don't use git?

**Comment by Erwyn** [comment]
Okay, so what you are saying is that there is no way to generate it again.

Thanks

**Comment by owenvoke** [comment]
You could copy the latest version from:
https://github.com/laravel-zero/laravel-zero/blob/master/box.json
