### ISSUE TITLE
make:command --test throws error

### ISSUE THREAD

**Issue by goodevilgenius** [laravel-zero/laravel-zero#366]
Options listed for `make:command` include `--pest` and `--test` to create correspond Pest or PHPUnit tests for the new command.

When doing `make:command --test Name` or `make:command --pest Name`, the command is still created, but an error is shown that says:

```
  Command "make:test" is not defined.

  Did you mean one of these?
      make:command
      pest:test
```

This happens on a new installation with the current version (8.8) with nothing additional added.

**Comment by goodevilgenius** [comment]
Bug is still present in 9.0.

I found a workaround by adding `Illuminate\Foundation\Console\TestMakeCommand::class,` to `config/commands.php` under `add`.

Seems like this command should already be included.

**Comment by owenvoke** [comment]
It should probably be added to this array. 👍🏻 (Apologies for the delayed reply)
https://github.com/laravel-zero/framework/blob/master/src/Kernel.php#L36
