### ISSUE TITLE
How to show logo on every command?

### ISSUE THREAD

**Issue by rognales** [laravel-zero/laravel-zero#371]
Hi there.

I've installed the logo add-on. The main ````php my-app```` command did show beautiful app.name in ASCII.
Now, how to i extend this to all my commands?

````php my-app mycommand```` will have ASCII logo as header.

**Comment by owenvoke** [comment]
You should be able to just run the following before each command in the `handle()` method. You could add this as a base class if you wanted to.
```php
$this->line($this->getName());
```

This should work because the `Logo` component sets the applications name to a rendered Figlet string of the app name.

**Comment by rognales** [comment]
````$this->getName()```` only returns the command name

**Comment by owenvoke** [comment]
Hmm, the `Logo` component should have set it to the logo.

**Comment by sixlive** [comment]
So you can output it in the `handle()` method but you have to reference the name off of the application.

```php
$this->line($this->getApplication()->getName());
```

**Comment by owenvoke** [comment]
Thanks @sixlive, that's what I was thinking of, forgot it was on `getApplication()->getName()` rather than `->getName()` 👍🏻

**Comment by rognales** [comment]
That did the trick! Thx @sixlive & @owenvoke.
