### ISSUE TITLE
Call to undefined method Psr\Log\NullLogger::channel()

### ISSUE THREAD

**Issue by roy-bongers** [laravel-zero/laravel-zero#374]
I hope this is the right place since the issue is in the `laravel-zero/foundation` package.

With recent changes in the `Illuminate\Foundation\Bootstrap\HandleExceptions` class there will always be a NullLogger instance created (`handleDeprecation` method). The `with()` will always receive an object and will never fail. The NullLogger instance doesn't have a channel() method which causes the error. See:

https://github.com/laravel-zero/foundation/blob/main/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php#L97

A possible fix would be to add this fragment directly below `$this->ensureDeprecationLoggerIsConfigured();`:

```php
        if ($logger instanceof NullLogger) {
            return;
        }
```

**Comment by rtuin** [comment]
@nunomaduro @owenvoke what do you think of the suggested solution?

**Comment by owenvoke** [comment]
@roy-bongers / @rtuin, can you confirm where you receive this issue? 🤔 I've tried triggering a deprecation warning and it appears to work fine with the latest version of `laravel-zero/foundation`. If this is an error, it should probably be addressed in `laravel/framework` (where `laravel-zero/foundation` is pulled from). 👍🏻

**Comment by roy-bongers** [comment]
I've updated all composer packages and the issues is resolved indeed. Thanks!
