### ISSUE TITLE
laravel valet not compatible (symfony/var-dumper 5.1/6.0)

### ISSUE THREAD

**Issue by lintaba** [laravel-zero/laravel-zero#377]
not compatible on global level with laravel valet, due to version mismatch. Is there any special reason to keep `symfony` dependencies on `^5.1`?

**Comment by owenvoke** [comment]
Yes, this would be changed as part of the release of LZ9.

**Comment by owenvoke** [comment]
Closing as LZ9 supports Symfony 6 👍🏻
