### ISSUE TITLE
`config('app.version')` is always `unreleased`

### ISSUE THREAD

**Issue by bilogic** [laravel-zero/laravel-zero#383]
I tagged my project as `1.0.0` in git, however when running it with `--version`, the version is `unreleased`.

If I do a `dd(config('app.version'))` in my code, it also shows as unreleased even though my `config/app.php` is as follows

```PHP
    /*
    |--------------------------------------------------------------------------
    | Application Version
    |--------------------------------------------------------------------------
    |
    | This value determines the "version" your application is currently running
    | in. You may want to follow the "Semantic Versioning" - Given a version
    | number MAJOR.MINOR.PATCH when an update happens: https://semver.org.
    |
    */

    'version' => app('git.version'),
```

**Comment by owenvoke** [comment]
Just to confirm, is this running `<your-app> --version` in your current Git repository, or after installing via Composer? 🤔 If it's in your Git repo, can you try running `git describe --tags --abbrev=0`. Which is what the [`GitVersionServiceProvider`](https://github.com/laravel-zero/framework/blob/master/src/Providers/GitVersion/GitVersionServiceProvider.php#L36) uses behind the scenes.

If it's from a global install via Composer, it may not be including the Git tags which might cause this to fail. 🤔 Not entirely sure though.

**Comment by bilogic** [comment]
Hi,

1. I created a project from the instructions into a `example/` folder
1. This ends up with the laravel-zero app named `example/example` and the `example/example/app/` folder where all my code lives
1. The config file shared above sits at `example/config/app.php`
1. Next, I ran `git init` in my `example/` folder and that's my git repository, make sense?
1. Running `git describe --tags --abbrev=0` in `example/` gives me `1.0.1`, which is the latest tag that I have, there is another earlier `1.0.0`
1. Running `example --version` in `example/` gives me `example unreleased`
1. Don't quite get the meaning of "global install via Composer"...

Or possible to provide your steps such that `example --version` will show the git tag version? Thank you!

**Comment by bilogic** [comment]
@owenvoke I think it might have been a bug from an earlier version of Laravel zero.

I ran the above again, and this time, `example --version` is showing the tag version for `"laravel-zero/framework": "^8.8"`.

The earlier one that wasn't working was `"laravel-zero\/framework": "^7.0"`.

Thank you.

**Comment by caendesilva** [comment]
Want to chime in here with what I ended up doing. Was having unreliable results with the Git based versioning when installing through Composer so I ended up binding the Composer release in my service provider.

```php
$this->app->bind(
    'framework.version',
    function () {
        return InstalledVersions::getPrettyVersion('hyde/framework') ?: 'unreleased';
    }
);
```` 

![image](https://user-images.githubusercontent.com/95144705/162616305-14c10493-136e-432c-a460-1534abb8a92e.png)
