### ISSUE TITLE
logo not support php 8.1.2

### ISSUE THREAD

**Issue by kaga-rin** [laravel-zero/laravel-zero#384]
php application app:install logo      ✔  7160  03:20:26
Installing logo component...
Require package via composer: loading...
./composer.json has been updated
Running composer update laminas/laminas-text
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - laminas/laminas-servicemanager[3.4.0, ..., 3.5.x-dev] require php ^5.6 || ^7.0 -> your php version (8.1.2) does not satisfy that requirement.
    - laminas/laminas-servicemanager[3.6.0, ..., 3.7.x-dev] require php ^7.3 || ~8.0.0 -> your php version (8.1.2) does not satisfy that requirement.
    - laminas/laminas-servicemanager[3.8.0, ..., 3.11.x-dev] require psr/container ^1.0 -> found psr/container[1.0.0, ..., 1.x-dev] but the package is fixed to 2.0.2 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - laminas/laminas-text[2.9.0, ..., 2.10.x-dev] require laminas/laminas-servicemanager ^3.4 -> satisfiable by laminas/laminas-servicemanager[3.4.0, ..., 3.11.x-dev].
    - Root composer.json requires laminas/laminas-text ^2.9 -> satisfiable by laminas/laminas-text[2.9.0, 2.9.x-dev, 2.10.x-dev].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
Require package via composer: failed
Creating default logo configuration: failed

**Comment by owenvoke** [comment]
It should work fine, however it looks like a package in your application has updated to `psr/container:^2.0`

Could you try removing your `composer.lock` and running the install command again? Or, alternatively, run the command manually with the `-W` flag which should hopefully downgrade `psr/container` back to version 1.x

You can see which package is stopping the install with `composer why-not psr/container 1.x`

**Comment by kaga-rin** [comment]
php application app:install logo      ✔  7180  15:58:02
Installing logo component...
Require package via composer: loading...
./composer.json has been updated
Running composer update laminas/laminas-text
Loading composer repositories with package information
Updating dependencies
Lock file operations: 97 installs, 0 updates, 0 removals
  - Locking brick/math (0.9.3)
  - Locking container-interop/container-interop (1.2.0)
  - Locking doctrine/inflector (2.0.4)
  - Locking doctrine/instantiator (1.4.0)
  - Locking dragonmantank/cron-expression (v3.3.1)
  - Locking facade/ignition-contracts (1.0.2)
  - Locking filp/whoops (2.14.5)
  - Locking graham-campbell/result-type (v1.0.4)
  - Locking hamcrest/hamcrest-php (v2.0.1)
  - Locking illuminate/bus (v9.0.2)
  - Locking illuminate/cache (v9.0.2)
  - Locking illuminate/collections (v9.0.2)
  - Locking illuminate/conditionable (v9.0.2)
  - Locking illuminate/config (v9.0.2)
  - Locking illuminate/console (v9.0.2)
  - Locking illuminate/container (v9.0.2)
  - Locking illuminate/contracts (v9.0.2)
  - Locking illuminate/events (v9.0.2)
  - Locking illuminate/filesystem (v9.0.2)
  - Locking illuminate/macroable (v9.0.2)
  - Locking illuminate/pipeline (v9.0.2)
  - Locking illuminate/support (v9.0.2)
  - Locking illuminate/testing (v9.0.2)
  - Locking illuminate/view (v9.0.2)
  - Locking jolicode/jolinotif (v2.4.0)
  - Locking laminas/laminas-servicemanager (3.10.0)
  - Locking laminas/laminas-stdlib (3.7.1)
  - Locking laminas/laminas-text (2.9.0)
  - Locking laravel-zero/foundation (v9.0.0)
  - Locking laravel-zero/framework (v9.0.0)
  - Locking league/flysystem (3.0.5)
  - Locking league/mime-type-detection (1.9.0)
  - Locking mockery/mockery (1.5.0)
  - Locking myclabs/deep-copy (1.10.2)
  - Locking nesbot/carbon (2.56.0)
  - Locking nikic/php-parser (v4.13.2)
  - Locking nunomaduro/collision (v6.1.0)
  - Locking nunomaduro/laravel-console-summary (v1.8.0)
  - Locking nunomaduro/laravel-console-task (v1.7.0)
  - Locking nunomaduro/laravel-desktop-notifier (v2.6.0)
  - Locking nunomaduro/termwind (v1.4.3)
  - Locking pestphp/pest (v1.21.1)
  - Locking pestphp/pest-plugin (v1.0.0)
  - Locking phar-io/manifest (2.0.3)
  - Locking phar-io/version (3.1.1)
  - Locking phpdocumentor/reflection-common (2.2.0)
  - Locking phpdocumentor/reflection-docblock (5.3.0)
  - Locking phpdocumentor/type-resolver (1.6.0)
  - Locking phpoption/phpoption (1.8.1)
  - Locking phpspec/prophecy (v1.15.0)
  - Locking phpunit/php-code-coverage (9.2.10)
  - Locking phpunit/php-file-iterator (3.0.6)
  - Locking phpunit/php-invoker (3.1.1)
  - Locking phpunit/php-text-template (2.0.4)
  - Locking phpunit/php-timer (5.0.3)
  - Locking phpunit/phpunit (9.5.13)
  - Locking psr/container (1.1.2)
  - Locking psr/log (3.0.0)
  - Locking psr/simple-cache (3.0.0)
  - Locking ramsey/collection (1.2.2)
  - Locking ramsey/uuid (4.2.3)
  - Locking sebastian/cli-parser (1.0.1)
  - Locking sebastian/code-unit (1.0.8)
  - Locking sebastian/code-unit-reverse-lookup (2.0.3)
  - Locking sebastian/comparator (4.0.6)
  - Locking sebastian/complexity (2.0.2)
  - Locking sebastian/diff (4.0.4)
  - Locking sebastian/environment (5.1.3)
  - Locking sebastian/exporter (4.0.4)
  - Locking sebastian/global-state (5.0.4)
  - Locking sebastian/lines-of-code (1.0.3)
  - Locking sebastian/object-enumerator (4.0.4)
  - Locking sebastian/object-reflector (2.0.4)
  - Locking sebastian/recursion-context (4.0.4)
  - Locking sebastian/resource-operations (3.0.3)
  - Locking sebastian/type (2.3.4)
  - Locking sebastian/version (3.0.2)
  - Locking symfony/console (v6.0.3)
  - Locking symfony/deprecation-contracts (v2.5.0)
  - Locking symfony/error-handler (v6.0.3)
  - Locking symfony/finder (v6.0.3)
  - Locking symfony/polyfill-ctype (v1.24.0)
  - Locking symfony/polyfill-intl-grapheme (v1.24.0)
  - Locking symfony/polyfill-intl-normalizer (v1.24.0)
  - Locking symfony/polyfill-mbstring (v1.24.0)
  - Locking symfony/polyfill-php80 (v1.24.0)
  - Locking symfony/polyfill-php81 (v1.24.0)
  - Locking symfony/process (v6.0.3)
  - Locking symfony/service-contracts (v2.5.0)
  - Locking symfony/string (v6.0.3)
  - Locking symfony/translation (v6.0.3)
  - Locking symfony/translation-contracts (v3.0.0)
  - Locking symfony/var-dumper (v6.0.3)
  - Locking theseer/tokenizer (1.2.1)
  - Locking vlucas/phpdotenv (v5.4.1)
  - Locking voku/portable-ascii (2.0.0)
  - Locking webmozart/assert (1.10.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
32 package suggestions were added by new dependencies, use `composer suggest` to see details.
Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead.
Generating optimized autoload files
62 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
Require package via composer: ✔
Creating default logo configuration: failed



still failed

**Comment by kaga-rin** [comment]
its work thx
