### ISSUE TITLE
Class from required packages not found in compiled phar

### ISSUE THREAD

**Issue by bilogic** [laravel-zero/laravel-zero#386]
Hi,

1. I use `composer require owner/package` to add a package into my project
2. It runs well on the CLI
3. However, the built phar file throws an exception `Class 'Owner\Package\<class>' does not exist`

How can I get access to the class?
I can't find any extra builds steps for such a scenario, any idea? 

Thank you.

**Comment by bilogic** [comment]
I'm still stuck on this, appreciate some help. Thank you!

**Comment by owenvoke** [comment]
Hi, sorry for the (very) delayed reply, looks like I never received a notification. What is the contents of your `box.json`? And, if possible, do you have a minimal example of your repository so I can investigate (no worries if not)? 🤔

**Comment by bilogic** [comment]
@owenvoke thanks, I managed to identify the issue shortly after the 2nd message. I was using symlinks for my `vendor` packages.

**Comment by owenvoke** [comment]
Glad you managed to sort it. 👍🏻
