### ISSUE TITLE
Scheduled tasks: Am I doing it wrong?

### ISSUE THREAD

**Issue by opicodes** [laravel-zero/laravel-zero#393]
### Discussed in https://github.com/laravel-zero/laravel-zero/discussions/392

<div type='discussions-op-text'>

<sup>Originally posted by **opicodes** February 24, 2022</sup>
Hi,
I created a command and want to schedule it. I added the required method 

```
    public function schedule(Schedule $schedule): void
    {
        $schedule->command(static::class)->everyMinute();
    }
```

to the command itself.

I then installed the schedule-list component, but running the `schedule:list` command always returns `No tasks scheduled`.

I suppose there is some magic that somehow check which commands exist and schedule them when they have that method? </div>

**Comment by owenvoke** [comment]
Closing as resolved in https://github.com/laravel-zero/laravel-zero/discussions/392 👍🏻

**Comment by opicodes** [comment]
Solved!

It was my fault as I was extending `Illuminate\Console\Command` rather than the`LaravelZero\Framework\Commands\Command`.
