### ISSUE TITLE
Logo addon wont install under php 8.0.12

### ISSUE THREAD

**Issue by vanaf1979** [laravel-zero/laravel-zero#398]
I tried to add the logo addon using the command: php appname app:install logo

But all i get is the following composser error:

----------------
- laminas/laminas-text[2.9.0, ..., 2.10.x-dev] require laminas/laminas-servicemanager ^3.4 -> satisfiable by laminas/laminas-servicemanager[3.4.0, ..., 3.11.x-dev].
    - laminas/laminas-servicemanager[3.4.0, ..., 3.5.2] require php ^5.6 || ^7.0 -> your php version (8.0.12) does not satisfy that requirement.
    - laminas/laminas-servicemanager[3.5.x-dev, ..., 3.11.x-dev] require psr/container ^1.0 -> found psr/container[1.0.0, ..., 1.x-dev] but the package is fixed to 2.0.2 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires laminas/laminas-text ^2.9 -> satisfiable by laminas/laminas-text[2.9.0, 2.9.x-dev, 2.10.x-dev].
----------------

Maybe my setup is bad, or there is a version issue somewhere.

Is there anything i can do to fix this?

Thanks

**Comment by owenvoke** [comment]
I think this is similar to https://github.com/laravel-zero/laravel-zero/issues/384#issuecomment-1037919706

**Comment by vanaf1979** [comment]
Thank you but unfortunately no luck.

I removed the vendor dir and the composer.lock file and ran a fresh composer install, but that didn't help.
(I have no additional packages installed.)

I also tried to install laminas/laminas-text manually using: composer require laminas/laminas-text -W
But that didn't work either

--------------------
  Problem 1
    - Conclusion: don't install laminas/laminas-text 2.10.x-dev (conflict analysis result)
    - Conclusion: don't install laminas/laminas-text 2.9.0 (conflict analysis result)
    - laminas/laminas-servicemanager[3.4.0, ..., 3.5.x-dev] require php ^5.6 || ^7.0 -> your php version (8.0.12) does not satisfy that requirement.
    - Root composer.json requires laminas/laminas-text ^2.9 -> satisfiable by laminas/laminas-text[2.9.0, 2.9.x-dev, 2.10.x-dev].
    - laravel-zero/framework is locked to version v9.1.1 and an update of this package was not requested.
    - laminas/laminas-text 2.9.x-dev requires laminas/laminas-servicemanager ^3.4 -> satisfiable by laminas/laminas-servicemanager[3.4.0, ..., 3.11.x-dev].
    - laminas/laminas-servicemanager[3.6.0, ..., 3.11.x-dev] require container-interop/container-interop ^1.2 -> satisfiable by container-interop/container-interop[1.2.0].
    - Conclusion: don't install container-interop/container-interop 1.2.0 (conflict analysis result)
-----------------

I tested a laminas/laminas-text installation in a empty project and that works fine. so there must be a collision with zero somewhere!?

Is there anything i can provide to clear this up? Or do you have any other suggestions?

Thanks for your time! :)

**Comment by owenvoke** [comment]
I don't think this is an issue with Laravel Zero (I've just run the following and it works fine):

```shell
laravel-zero new test && cd test
php test app:install logo
```

Could you try running `composer why-not container-interop/container-interop 1.2` to see why it won't install, or do you happen to have a public repository so that I could test? 🤔

**Comment by vanaf1979** [comment]
- Could you try running composer why-not container-interop/container-interop 1.2 to see why it won't install!?

Sure1
----------                     
  [InvalidArgumentException]                                                    
  Could not find package "container-interop/container-interop" in your project  
----------    

I tried requiring it manually and gut this:

----------
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires container-interop/container-interop ^1.2 -> satisfiable by container-interop/container-interop[1.2.0].
    - container-interop/container-interop 1.2.0 requires psr/container ^1.0 -> found psr/container[1.0.0, ..., 1.x-dev] but the package is fixed to 2.0.2 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

----------


- Or do you happen to have a public repository so that I could test?

I do now! ;)
https://github.com/vanaf1979/steph

**Comment by vanaf1979** [comment]
Just to be sure i didnt mess anything up i just ran a complete fresh install of zero and i get the same thing.

**Comment by vanaf1979** [comment]
Yes that did the trick. Thank you. :)

Is this something that needs fixing in zero or other package? Or is it some issue on my side that i should be aware of?

**Comment by owenvoke** [comment]
I think technically `laminas-servicemanager` would need to be updated to work with `2.x` of `psr/container` (however I don't think that's possible at the moment, and I know they are wanting to migrate). Overall, I think maybe it should be a fix to Laravel Zero so that it allows upgrading, however I think it's more Composer that results in the issue.

**Comment by vanaf1979** [comment]
Sounds fair. At least we (Meaning you) found a solution for the meanwhile. :)

Can i just say that i watched the Laravel origin documentary the other day, and in it people seem to agree that the Laravel community is very open and welcoming! Well... You sure showed that today! Thanks you very much for your help! :)

**Comment by owenvoke** [comment]
I'm going to close this for now, and maybe add debugging details to the documentation.

**Comment by chrillep** [comment]
https://github.com/laminas/laminas-servicemanager/issues/92
