### ISSUE TITLE
Generated _ide_helper for Facades doesn't show FQN for @throws

### ISSUE THREAD

**Issue by Healyhatman** [laravel-zero/laravel-zero#399]
When a facade method has @throws docblocks they are included in the _ide_helper.php reference as-is. So if you replace the qualifiers with an import to for example have @throws MyException instead of @throws \App\Exceptions\MyException the 'use' statement isn't imported anywhere and the IDE doesn't understand that it's supposed to watch out for that exception.

**Comment by owenvoke** [comment]
Is this an issue with the IDE Helper or with Laravel Zero? 🤔 Does the same apply for a standard Laravel app?

**Comment by Healyhatman** [comment]
Sorry I don't know how I ended up here this was supposed to be posted on the ide helper repo
