### ISSUE TITLE
php [application] app:install logo - composer dependency issue with PHP8

### ISSUE THREAD

**Issue by chrisvasey** [laravel-zero/laravel-zero#402]
Hello!

Just ran into the following on a fresh Zero app running PHP 8.0,17.
When running `php [application] app:install logo`, the CLI attempts to install `laminas/laminas-text "^2.9"` and gets the following error:
```
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - laminas/laminas-text[2.9.0, ..., 2.10.x-dev] require laminas/laminas-servicemanager ^3.4 -> satisfiable by laminas/laminas-servicemanager[3.4.0, ..., 3.11.x-dev].
    - laminas/laminas-servicemanager[3.4.0, ..., 3.5.2] require php ^5.6 || ^7.0 -> your php version (8.0.17) does not satisfy that requirement.
    - laminas/laminas-servicemanager[3.5.x-dev, ..., 3.11.x-dev] require psr/container ^1.0 -> found psr/container[1.0.0, ..., 1.x-dev] but the package is fixed to 2.0.2 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires laminas/laminas-text ^2.9 -> satisfiable by laminas/laminas-text[2.9.0, 2.9.x-dev, 2.10.x-dev].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
Require package via composer: failed
Creating default logo configuration: failed
```

I had a look on the [laminas-text repo](https://github.com/laminas/laminas-text) and found the recently updated to support PHP 8.12 [here](https://github.com/laminas/laminas-text/issues/9).

Are there plans to update this?
I am happy to have a crack at writing a PR if this is needed.

**Comment by owenvoke** [comment]
`I think this is the same sort of issue as https://github.com/laravel-zero/laravel-zero/issues/398#issuecomment-1059133615, do you mind trying those steps (i.e. removing the lock file, and then requiring `laminas/laminas-text` manually)?`

**Comment by chrisreedio** [comment]
> I think this is the same sort of issue as [#398 (comment)](https://github.com/laravel-zero/laravel-zero/issues/398#issuecomment-1059133615), do you mind trying those steps (i.e. removing the lock file, and then requiring `laminas/laminas-text` manually)?

Bit late to the party but just stumbled across this problem and this solution solved it for me!
