### ISSUE TITLE
Undefined property $unexpectedOutputSubstrings

### ISSUE THREAD

**Issue by ghost** [laravel-zero/laravel-zero#410]
Hi

laravel-zero/framework: v9.1.1
php: v8.1
using docker image: php:8.1-cli

My tests are failing when running my tests through pest on laravel zero.

I believe this breaks any test using the expectsOutputToContain function.

I think the solution is just that InteractsWithConsole trait is missing:

/**
   * All of the text that is not expected to be present in the output.
   *
   * @var array
   */
public $unexpectedOutputSubstrings = [];

I just thought I would create a quick issue here and when I have time issue a PR this evening.

**Comment by owenvoke** [comment]
Can you check what version of the Foundation you are using with the following command?

```shell
composer info laravel-zero/foundation
```

It should show the installed version at the top under `versions`. The `InteractsWithConsole` trait was added in Laravel Zero Foundation 9.2.0 🙂

**Comment by oreillysean** [comment]
Hi

name     : laravel-zero/foundation
descrip. : This is a mirror from illuminate/foundation.
keywords : framework, laravel
versions : * v9.9.0
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
homepage : 
source   : [git] https://github.com/laravel-zero/foundation.git 0294c6885b8a6e4073a374e928a35dbf0f0f0ab8
dist     : [zip] https://api.github.com/repos/laravel-zero/foundation/zipball/0294c6885b8a6e4073a374e928a35dbf0f0f0ab8 0294c6885b8a6e4073a374e928a35dbf0f0f0ab8
path     : /Users/sean/Documents/Sites/composer-license-checker/vendor/laravel-zero/foundation
names    : laravel-zero/foundation

support
source : https://github.com/laravel-zero/foundation/tree/v9.9.0


I can see that it's this commit that it missing from laravel-zero/foundation https://github.com/laravel/framework/commit/bce3cf824d39d615fc49fc63640c36f8fbf0d419

**Comment by owenvoke** [comment]
Damn, I hadn't seen there was another release (9.10.0). I only just released 9.9.0 earlier. 😬  Will get that released in a sec!

**Comment by oreillysean** [comment]
Yes it is just mismatched with illuminate testing

name     : illuminate/testing
descrip. : The Illuminate Testing package.
keywords : 
versions : * v9.10.0
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
homepage : https://laravel.com
source   : [git] https://github.com/illuminate/testing.git 0fec8cb1f13383fb29b6e85171cbbc7c00119c7c
dist     : [zip] https://api.github.com/repos/illuminate/testing/zipball/0fec8cb1f13383fb29b6e85171cbbc7c00119c7c 0fec8cb1f13383fb29b6e85171cbbc7c00119c7c
path     : /Users/sean/Documents/Sites/composer-license-checker/vendor/illuminate/testing
names    : illuminate/testing

**Comment by oreillysean** [comment]
@owenvoke major thanks. Sorry for not making a PR to fix.
