### ISSUE TITLE
logo addon is not ready for php8.*

### ISSUE THREAD

**Issue by EsoCoding** [laravel-zero/laravel-zero#412]
![image](https://user-images.githubusercontent.com/2956337/169057363-402baf60-72b1-404e-89ee-b0695cfd9952.png)

It seems logo addon fails when using ^php8.0. It only works if laravel-zero is installed with php7.4.

**Comment by owenvoke** [comment]
I think this is the same sort of issue as https://github.com/laravel-zero/laravel-zero/issues/398#issuecomment-1059133615, do you mind trying those steps (i.e. removing the lock file, and then requiring `laminas/laminas-text` manually)?

**Comment by EsoCoding** [comment]
Weird, yesterday i did try the same without having success. Even did a fresh install with php7.4 and 8.0, even tweaked the composer file, but whatever i did, it failed. But now doing the same thing again, it suddenly installed with success. Still had a error from laravel-zero on installing, but think that was because there already was a logo configuration file... After deleting it and reinstalling the logo addon again, it installed successfully.

**Comment by owenvoke** [comment]
Yeah, it's an issue with the Laminas Text component only supporting `psr/container:^1.x`, I can't see any way to really resolve this. But I guess it'd probably be worth me adding it to the docs as a note / troubleshooting step. 👍🏻

**Comment by EsoCoding** [comment]
Been playing around. After adding "psr/container": "^1.1.1" to the root composer.json and after updating composer. I could install logo module without problem.

I think the problem can be found here:

![image](https://user-images.githubusercontent.com/2956337/169275776-df84f23e-6383-4bff-9782-c0b66cddba84.png)

When trying to remove psr/container i get this error:

![image](https://user-images.githubusercontent.com/2956337/169277125-2204b219-12a2-423d-b8a9-286a0169340b.png)

**Comment by EsoCoding** [comment]
When cloned from github and `psr/container` added to composer.json, that same command gives me this:

![image](https://user-images.githubusercontent.com/2956337/169280638-57c57c05-7be4-4eef-a95b-2b0217570e34.png)

**Comment by owenvoke** [comment]
I don't think this an issue anymore, but please feel free to reopen if this is not the case. 🙂

**Comment by HelgeSverre** [comment]
Run the following command to install the `laminas-text` manually, which is what it is trying to do (along with copying the [logo.php](https://github.com/laravel-zero/framework/blob/master/src/Components/Logo/stubs/logo.php) file into your `/config` folder) [under the hood](https://github.com/laravel-zero/framework/blob/master/src/Components/Logo/Installer.php#L44-L55) anyways.

```shell
composer require laminas/laminas-text:^2.11
```

I could not get it to work with the `install:logo` comand, but manually requiring it seems to work for some reason...
