### ISSUE TITLE
Building standalone phar file fails

### ISSUE THREAD

**Issue by EsoCoding** [laravel-zero/laravel-zero#414]
Hey, i was trying to build the standalone phar file and when using -v, it says:
![image](https://user-images.githubusercontent.com/2956337/170895233-c473b551-32d8-4c59-bfc4-7601a10d9489.png)
and:
![image](https://user-images.githubusercontent.com/2956337/170895302-0b3d1bef-5774-48a4-881e-5200135b3dd8.png)

Also created a new project, but returns same error. Probably something to do with permissions... But which?

**Comment by EsoCoding** [comment]
Never mind, solved it by giving execute permission on the box file: `chmod +x ./vendor/laravel-zero/framework/bin/box compile`

**Comment by owenvoke** [comment]
Glad you resolved it, that should be executable by default when it's installed though. 🤔
