### ISSUE TITLE
[Support] Cannot Hide db:wipe command

### ISSUE THREAD

**Issue by robertmarney** [laravel-zero/laravel-zero#416]
Apologies if this has been asked before, I am trying to build a phar for dsitribution that will ship with a migrated db.

I am trying to hide db:wipe from the command list when the application is called, I have added `Illuminate\Database\Console\WipeCommand::class` to either and then both of the `hidden` and `remove` arrays in `commands.php` with no luck

**Comment by chrisbradleydev** [comment]
I ran into the same issue today.

**Comment by etyson17** [comment]
I am running into the same issue.

**Comment by nunomaduro** [comment]
@robertmarney @chrisbradleydev @etyson17 Can one of you work on pull request please?

**Comment by chrisbradleydev** [comment]
@nunomaduro would you please point us in the right direction?

Is this functionality in the framework repository?

**Comment by etyson17** [comment]
@nunomaduro I have been able to hide the db:wipe command by removing the `protected static $defaultName = 'db:wipe';` and `#[AsCommand(name: 'db:wipe')]`.

Is there a test I can run to ensure this is not going to break anything?

https://github.com/illuminate/database/blob/9.x/Console/WipeCommand.php#L10-L31

**Comment by etyson17** [comment]
It appears that lines 7 & 10 were added back in April but I am unsure why. Any clarification would be extremely helpful.

Here is where they were added:
https://github.com/laravel/framework/pull/41982

**Comment by mugennsou** [comment]
Hello @nunomaduro , I just fix this issue and make a [pull request](https://github.com/laravel-zero/framework/pull/465), could you have a look? Thank you.

**Comment by owenvoke** [comment]
Hi @robertmarney, this should now be resolved in the latest version of the framework. 👍🏻 (At least, using `hidden`). Let me know if you have any further issues.
