### ISSUE TITLE
Syntax error in laravel-zero/foundation

### ISSUE THREAD

**Issue by joaquimds** [laravel-zero/laravel-zero#418]
There is an error in  `laravel-zero/foundation/src/Illuminate/Foundation/Console/RouteListCommand.php`.

The error is at line 269:

    ($this->option('except-vendor') && $route['vendor'])) ||

It should have one less bracket:

    ($this->option('except-vendor') && $route['vendor']) ||

I would make a PR but I don't have access to the foundation repo. Thanks!

**Comment by owenvoke** [comment]
Hi @joaquimds, thank you for pointing this out. 😬 My mistake, I really need to automate the mirroring with patch files or something... And add some testing over on the Foundation repository.
