### ISSUE TITLE
Access level to LaravelZero\Framework\Commands\InstallCommand::$components must be protected (as in class Illuminate\Console\Command) or weaker

### ISSUE THREAD

**Issue by ryangjchandler** [laravel-zero/laravel-zero#422]
Had this on a brand new project. Seems like the visibility is conflicting with the `$components` property defined in the `InteractsWithIO` trait.

**Comment by avfigueredo** [comment]
I'm getting the same error.

**Comment by owenvoke** [comment]
Can you try updating to [v9.1.2](https://github.com/laravel-zero/framework/commit/bfb3b8adc23fbb92d4c7fddde79ce4da6989ad54), if you have any issues, feel free to let me know. 👍🏻

**Comment by ryangjchandler** [comment]
Thanks @owenvoke :)
