### ISSUE TITLE
Hashing class not found

### ISSUE THREAD

**Issue by anggerari** [laravel-zero/laravel-zero#432]
![image](https://user-images.githubusercontent.com/21980273/202171731-a19c0479-5318-49a8-a521-89390a7d13d1.png)
I want to run the seeder with Hash::make() function but it is not found.

I have already imported this:
`use Illuminate\Support\Facades\Hash;`

but it still does not work. any ideas?

**Comment by anggerari** [comment]
hi , can someone help me for this issue?

**Comment by owenvoke** [comment]
Hi 👋🏻 Sorry for not seeing your issue, just to check, have you required the `illuminate/hashing` package? 🙂

**Comment by anggerari** [comment]
> Hi 👋🏻 Sorry for not seeing your issue, just to check, have you required the `illuminate/hashing` package? 🙂

yea i already required that package before

**Comment by owenvoke** [comment]
Thanks for confirming, going to look into this shortly. 👍🏻

**Comment by owenvoke** [comment]
As this isn't a core component of Laravel Zero, the `Illuminate\Hashing\HashServiceProvider::class` will need to be manually added to your `config/app.php` under the `providers` array.

Could you confirm whether it works after adding this? 🙂

**Comment by anggerari** [comment]
Okay i will try to add the `Illuminate\Hashing\HashServiceProvider::class` , i will get back to you if is work

**Comment by owenvoke** [comment]
Closing as I'm assuming this was resolved. Please reopen the issue if this is not the case.
