### ISSUE TITLE
Installing Logo Add-on is throwing an error with PHP 8.2

### ISSUE THREAD

**Issue by WendellAdriel** [laravel-zero/laravel-zero#441]
I'm trying to install the Logo Add-on, but when I run the command to install I get this error
![image](https://user-images.githubusercontent.com/11641518/217543039-ac370d32-73e1-4766-bb37-27f827da0bd1.png)

**Comment by chrillep** [comment]
ref:
* https://github.com/laminas/laminas-servicemanager/issues/92
* https://github.com/laminas/laminas-servicemanager/pull/151
