### ISSUE TITLE
Process Support

### ISSUE THREAD

**Issue by billriess** [laravel-zero/laravel-zero#446]
Is it possible to add [Process](https://laravel.com/docs/10.x/processes) support?

**Comment by nunomaduro** [comment]
Sure - you make pull request it.

**Comment by billriess** [comment]
Yes, but wouldn't this make more sense as a plugin/addon than directly in the main project? How do you handle addon support?

**Comment by owenvoke** [comment]
It already supports the Process facade by default. 🤔

**Comment by billriess** [comment]
Oh strange I didn't see this. Thanks then I'll update my project.
