### ISSUE TITLE
Consider using Laravel Prompts

### ISSUE THREAD

**Issue by mve** [laravel-zero/laravel-zero#456]
An official Laravel package, Laravel Prompts, was released a few days ago:
GitHub: https://github.com/laravel/prompts
Documentation: https://laravel.com/docs/10.x/prompts

Might be nice for Laravel Zero to use these?

**Comment by owenvoke** [comment]
Yes, that is a planned thing to update! 🥳

**Comment by lbattaglioli2000** [comment]
Is there any way for the community to contribute to this @owenvoke? Super eager to see support for this.

**Comment by owenvoke** [comment]
Technically you can install this already (just use `composer require laravel/prompts`, and [use as the docs mention](https://laravel.com/docs/prompts)). It's just not included with Laravel Zero by default.

I'll make an update tomorrow with support out of the box for it (or you can PR the change, basically just adding it to the Laravel Zero Framework repository). 👍🏻 Sorry, been busy with other bits.
