### ISSUE TITLE
Cannot find sqlite database when upgrading

### ISSUE THREAD

**Issue by JonPurvis** [laravel-zero/laravel-zero#460]
Hey 👋 

I have a dependabot PR to update Laravel Zero from 10.1.1 to 10.1.2. When my pipeline goes to run the application tests though, it fails with the following error:

> Database file at path [/app/database/database.sqlite] does not exist. Ensure this is an absolute path to the database. (Connection: sqlite, SQL: PRAGMA foreign_keys = ON;)

I'm not sure why this would suddenly start failing, unless something has changed in Laravel Zero itself?

Any help would be much appreciated!

Thanks

**Comment by owenvoke** [comment]
Hi, do you have an example repository where this is happening? Or is this a private repo? 🙂

As far as I know, nothing has changed in terms of paths. There have only been a few minor dependency updates, a Pint update, and some small fixes.

**Comment by JonPurvis** [comment]
Sorry for the delay in getting back to this @owenvoke 

It's still an issue and it's on a private repo. However, I'll create a new project later today and see if I can replicate and if I can, I'll push it to a public repo. 

Thanks!

**Comment by JonPurvis** [comment]
Hey @owenvoke 👋 

Just thought I'd jump back in here to let you know I've resolved the issue. Turns out I was missing some values that needed specifying in the phpunit.xml file. Still unsure why it was an update to this package that needed me to add them as it worked fine before 😆 

At least it's one less thing for me to worry about now!
