### ISSUE TITLE
app:build gives the error: The system cannot find the file specified (code: 2)

### ISSUE THREAD

**Issue by 0proboy0** [laravel-zero/laravel-zero#466]
OS: Windows
Laravel-Zero version: 10.2.0
PHP version: 8.1.10

I installed Laravel-Zero:
1. `composer create-project --prefer-dist laravel-zero/laravel-zero cli`
2. `cd cli`
3. `php application app:rename cli`

I then directly run ` php cli app:build cli` and got that error:
![image](https://github.com/laravel-zero/laravel-zero/assets/14108109/03cf756a-c536-4665-bbf7-7b4da9049b1d)

Looks like the PHAR file is not getting created and there is no exception raised.

@owenvoke @nunomaduro

**Comment by owenvoke** [comment]
Hi @0proboy0, please could you try running the command again with debug mode?
```pwsh
php cli app:build cli -vvv
```

**Comment by 0proboy0** [comment]
Hey @owenvoke, thanks for replying,
The error was about not enabling the Sodium PHP extension:

![image](https://github.com/laravel-zero/laravel-zero/assets/11405387/4cd53b17-2ba0-4663-931e-bd60685ff7cf)

I enabled it and it works, thanks a lot.
It's a good idea to mention this requirement in the docs.

I have two more questions please, I plan to distribute the CLI app and to be used by non-PHP developers, does the PHAR file contain only the files of the app or does it contain PHP too? what I mean is if the PHAR file is enough to let the app work or we do need to install PHP first.

I also want to make the app work without the `php` command, I mean like `cli inspire` instead of `php cli inspire`, how can I do that on Mac, Windows, and Linux, please?

**Comment by owenvoke** [comment]
As far as I know, `sodium` isn't a default required extension by Laravel Zero, looks like it's a requirement for Box. 🤔 I'll add a note to the docs, or you're welcome to open a PR for that. 👍🏻

---

Regarding the Phar file, it only contains the files related to the app. You would have to install PHP first before using it. I do have some examples of how to package your Laravel Zero app for [macOS via Brew](https://voke.dev/blog/distributing-laravel-zero-apps-with-brew), [Windows via Scoop](https://voke.dev/blog/distributing-laravel-zero-apps-with-windows-package-managers), and [any OS via Docker](https://voke.dev/blog/distributing-laravel-zero-apps-with-docker). Those may help to ease the process.

The alternative is to use something to bundle PHP with the Phar file as an executable.

---

For your 2nd question, regarding executing without the `php` prefix, this will be possible with any of the solutions I've mentioned. Or through distribution with Composer.

**Comment by 0proboy0** [comment]
thnkx
