### ISSUE TITLE
Why is package auto-discovery is off ?

### ISSUE THREAD

**Issue by woodspire** [laravel-zero/laravel-zero#468]
https://github.com/laravel-zero/framework/commit/707315b53fb2eb1c2d96246ddb9fa93dc81370f7

It's been 5 years.

If it slows down the app, at least allow it through a config/app variable.

**Comment by owenvoke** [comment]
Feel free to PR support for this. 🤷🏻 I'm not entirely sure why this was originally disabled.

**Comment by nunomaduro** [comment]
I can't remember either.

**Comment by woodspire** [comment]
Done.

https://github.com/laravel-zero/framework/pull/488

**Comment by woodspire** [comment]
https://github.com/laravel-zero/laravel-zero/pull/470
