### ISSUE TITLE
Website is down - domain expired?

### ISSUE THREAD

**Issue by jaminion** [laravel-zero/laravel-zero#473]
Seems like #359, currently getting connection resets from https://laravel-zero.com, but without the https get a domain parked by godaddy message.

Does there happen to be another location where the more extended documentation resides, by chance? Just happen to be looking for the upgrade guide to review and suggest to someone. I'm guessing it's right in front of my face and I'm just missing it.

Thank you!

**Comment by owenvoke** [comment]
The docs are available in Markdown format in the docs repository:
https://github.com/laravel-zero/docs

**Comment by nunomaduro** [comment]
I am moving the domain from DNS provider, may take a while.

**Comment by jaminion** [comment]
Hey you two - I super appreciate this! The upgrade docs had exactly what I was looking for (had a dependency issue and confused on the composer messages).

@nunomaduro I will close this issue up as it's external and @owenvoke provided everything necessary - thank you very much!
