### ISSUE TITLE
laravel-zero.com is down

### ISSUE THREAD

**Issue by igorsgm** [laravel-zero/laravel-zero#474]
Hello @nunomaduro 👋 

https://laravel-zero.com website has been down for a few days:

![Screenshot 2023-11-14 at 2 56 57 PM](https://github.com/laravel-zero/laravel-zero/assets/14129843/c9075470-6eed-4e2f-997f-fa046043dc6e)

**Comment by owenvoke** [comment]
Yes, check the other issues that were opened for this issue. The site is temporarily down as Nuno is changing DNS provider. 👍🏻 Hopefully it will be back soon.
