### ISSUE TITLE
Website is not working anymore http://laravel-zero.com/

### ISSUE THREAD

**Issue by rikvdh** [laravel-zero/laravel-zero#475]

**Comment by owenvoke** [comment]
I'm not entirely sure what's going on here, @nunomaduro was migrating to a new DNS provider, but this seems a little long for that to be taking. 🤷🏻

This has been brought up multiple times already over the last week or so:

- https://github.com/laravel-zero/laravel-zero/issues/471
- https://github.com/laravel-zero/laravel-zero/issues/472
- https://github.com/laravel-zero/laravel-zero/issues/473
- https://github.com/laravel-zero/laravel-zero/issues/474

Please check out [the documentation repository](https://github.com/laravel-zero/docs) in the mean time.

**Comment by rikvdh** [comment]
Hm yes, it seems that the nameservers are not resolving for laravel-zero.com.

   Name Server: NS59.DOMAINCONTROL.COM
   Name Server: NS60.DOMAINCONTROL.COM
   
   ```
   $ dig @97.74.100.31 laravel-zero.com

; <<>> DiG 9.16.44-Debian <<>> @97.74.100.31 laravel-zero.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: REFUSED, id: 64339
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1472
; EDE: 20 (Not Authoritative): (Not Authoritative)
;; QUESTION SECTION:
;laravel-zero.com.              IN      A

;; Query time: 0 msec
;; SERVER: 97.74.100.31#53(97.74.100.31)
;; WHEN: Mon Nov 20 14:02:44 CET 2023
;; MSG SIZE  rcvd: 68
```

**Comment by owenvoke** [comment]
Looks like this is resolved. 👍🏻
