### ISSUE TITLE
On Windows, when running app:build "impossible find specified file"

### ISSUE THREAD

**Issue by Giuliano1993** [laravel-zero/laravel-zero#479]
When running the command `app:build` , in the compile step I receive this error:

```bash
 ErrorException 
  rename(C:\Users\giuli\Desktop\projects\laravel-zero-test\application.phar,C:\Users\giuli\Desktop\projects\laravel-zero-test\builds\application): Impossibile trovare il file specificato (code: 2)
```
That is because the application file in root is called only `application` and not `application.phar`

I fixed this going to `laravel-zero\framework\src\Commands\BuildCommand.php` on line 165 and changing this:

```php
File::move($this->app->basePath($this->getBinary()).'.phar', $this->app->buildsPath($name));
```

to this:

```php
File::move($this->app->basePath($this->getBinary()), $this->app->buildsPath($name));
```

Since this is probably an OS related issue I'd first like to hear if on linux or mac there's the same issue; otherwise we could add an OS based control to change the file call based on OS.

I'd love to make a PR for this once is verified

**Comment by Giuliano1993** [comment]
Okay so thank you for specifying! I dug more in the documentation and found the right command for building using box, I didn't realize a double step was needed for build, fist the `box` command and then the `app:build`, so thank you for pointing that out to me and sorry for not noticing it before.

I can confirm that box is still supporting windows, it just worked for me! 😄 

Still I feel that docs could be clearer about the building process, so I'll try more things out a bit and try to propose something!
Thanks again!

**Comment by owenvoke** [comment]
The `app:build` command should be running Box behind the scenes, which is why I'm confused. 🤔 You shouldn't need to run `box` first.

Do you mind running `app:build -vvv`, and posting the verbose output here?

**Comment by Giuliano1993** [comment]
In fact, that sounded strange to me, too, having to do that! 
I actually was willing to give you the output, but it started giving me a different issue. 
So I created a project from zero and worked all fine first shot, it built the application just by running the command and it does everything it needs to.

I'm a bit confused, but I probably got something wrong in the first run and messed a bit things up ( even If I had just the default files on while testing things so it is still strange ).
Anyhow if I run again into the same issue  I'll paste the output here!

**Comment by owenvoke** [comment]
That's great, going to close this issue. But feel free to reopen it, or post here if you hit the issue again. 👍🏻
