### ISSUE TITLE
DB related command appears when installing larastan

### ISSUE THREAD

**Issue by SRWieZ** [laravel-zero/laravel-zero#489]
### Context
https://x.com/SRWieZ/status/1783222040050249988

### Summary

When installing `larastan/larastan` with `laravel-zero/laravel-zero`.
A unwanted set of db related commands appears in the app.

### Currently in: Laravel Zero 11.0 + larastan/larastan
```bash
composer create-project --prefer-dist laravel-zero/laravel-zero laravel-zero-11
cd laravel-zero-11
composer require larastan/larastan --dev
chmod +x application && ./application
```
<img width="878" alt="Capture d’écran 2024-04-24 à 23 09 47" src="https://github.com/laravel-zero/laravel-zero/assets/1408020/f0c4c780-46da-4b16-a353-e23b80956a87">

### Before in: Laravel Zero 10.0 + larastan/larastan
```bash
composer create-project --prefer-dist laravel-zero/laravel-zero laravel-zero-10 "10.0"
cd laravel-zero-10
composer require larastan/larastan --dev
chmod +x application && ./application
```
<img width="843" alt="Capture d’écran 2024-04-24 à 23 08 11" src="https://github.com/laravel-zero/laravel-zero/assets/1408020/6044d26d-5704-4506-8a96-e7b81bf64074">

**Comment by nunomaduro** [comment]
Fixed.
