### ISSUE TITLE
"bootstrap/app.php" is not a file in phar

### ISSUE THREAD

**Issue by happytodev** [laravel-zero/laravel-zero#490]
Hello, 

I can build my app with `app:build` but when I run it, I have this error message :

> Warning: require_once(phar:///Users/happytodev/courses/larafil/builds/larafil/bootstrap/app.php): Failed to open stream: phar error: "bootstrap/app.php" is not a file in phar "/Users/happytodev/courses/larafil/builds/larafil" in phar:///Users/happytodev/courses/larafil/builds/larafil/larafil on line 19

> Fatal error: Uncaught Error: Failed opening required 'phar:///Users/happytodev/courses/larafil/builds/larafil/bootstrap/app.php' (include_path='.:') in phar:///Users/happytodev/courses/larafil/builds/larafil/larafil:19
Stack trace:
#0 /Users/happytodev/courses/larafil/builds/larafil(15): require()
#1 {main}
  thrown in phar:///Users/happytodev/courses/larafil/builds/larafil/larafil on line 19
  
Have you any idea how to resolve this please ?

**Comment by owenvoke** [comment]
What is the contents of your `box.json`? 🙂

**Comment by happytodev** [comment]
> What is the contents of your `box.json`? 🙂 Ah, just seen it. Should be fine, I'll give this a test.
> 
> I just cloned your repo and built a Phar locally and it all seems to be working as expected.

What is your config ?
For me, Mac M1 + Herd

**Comment by owenvoke** [comment]
Using Mac M1 + PHP 8.3 through Brew.

**Comment by happytodev** [comment]
> Using Mac M1 + PHP 8.3 through Brew.

Thanks Owen. I don't understand why I have this error. We have almost the same environment...

For the build you use :

```
php larafil app:build
``` 

and to launch, just 

```
./builds/larafil
```  

??

**Comment by owenvoke** [comment]
Yeah 👍🏻

[![asciicast](https://asciinema.org/a/WgiJCU2FUQ2f1WTmTd4jqJW8U.svg)](https://asciinema.org/a/WgiJCU2FUQ2f1WTmTd4jqJW8U)

**Comment by happytodev** [comment]
Thanks for your feedback.
Do you have any idea about what could be wrong on my side ?

**Comment by happytodev** [comment]
Ok, I just git clone my project in a new folder and it works.
I don't understand, something that will still weird for eternity probably 😉

**Comment by owenvoke** [comment]
Very strange. 🤔 Could try deleting the `vendor` directory, in case it's something weird with the dependencies. But if it works in the new directory, I guess that's ok?

**Comment by happytodev** [comment]
Yes, it's ok. I will close this issue.
But very very strange, I follow step by step documentation.

**Comment by ap1969** [comment]
Just adding a comment in case someone else finds this: I had this same error. The cause was that my box.json was emptied. This could have been during the installation of the database addon, but I can't be sure.
