### ISSUE TITLE
Has the Logo addon been dropped?

### ISSUE THREAD

**Issue by eleftrik** [laravel-zero/laravel-zero#491]
I just upgraded a Laravel Zero application from 10.x to 11.x.
Has the Logo addon been dropped?

In `config/logo.php` I have

`'font' => \LaravelZero\Framework\Components\Logo\FigletString::DEFAULT_FONT,`

but this class no longer exists and logo documentation (https://laravel-zero.com/docs/create-a-logo) returns 404.

Let me know if I can do anything to help.
Thanks.

**Comment by owenvoke** [comment]
Yeah, looks like Nuno removed it as part of v11. 👀 That should probably have been mentioned on the upgrade guide...
https://github.com/laravel-zero/framework/commit/37dcecbcf76cd5e16fd3e64629242f0acbaae842

**Comment by eleftrik** [comment]
> Yeah, looks like Nuno removed it as part of v11. 👀 That should probably have been mentioned on the upgrade guide... [laravel-zero/framework@37dcecb](https://github.com/laravel-zero/framework/commit/37dcecbcf76cd5e16fd3e64629242f0acbaae842)

Yes, I think it's worth mentioning in the upgrade guide, along with any other removed addons. Thanks!

**Comment by nunomaduro** [comment]
Can you do a PR on the upgrade guide? Thanks!

**Comment by eleftrik** [comment]
> Can you do a PR on the upgrade guide? Thanks!

https://github.com/laravel-zero/docs/pull/40

Thanks @nunomaduro
