### ISSUE TITLE
[3.5 - Proposal] Scheduled Tasks

### ISSUE THREAD

**Issue by vyuldashev** [laravel-zero/laravel-zero#53]
Hello,

A very missing thing in this awesome framework is Scheduler. The only thing which stops me from using Laravel Zero for my console applications is that it misses scheduler.

Any plans for this feature?

**Comment by nunomaduro** [comment]
@vyuldashev Yes. Is in our Roadmap for release 3.5. I will leave this issue open was proposal.

**Comment by nunomaduro** [comment]
The feature development is on progress. Concerning the API anyone have suggestions? I was thinking about two options.

1. On the command class:

```
    /**
     * Execute the console command. Here goes the command
     * code.
     *
     * @return void
     */
    public function handle(): void
    {
        $this->info('Love beautiful code? We do too.');
        $this->notify('Hey Artisan', 'Enjoy the fresh air!');
    }

    /**
     * Define the application's command schedule.
     *
     * @param  \Illuminate\Console\Scheduling\Schedule  $schedule
     * @return void
     */
    protected function schedule(Schedule $schedule)
    {
        // Just like Laravel, but on the command.
    }
```

2. On the config.php:


```
        /*
         * Here goes the application default command.
         *
         * You may want to remove this line in order to ask the user what command he
         * wants to execute.
         */
        'default-command' => App\Commands\DefaultCommand::class,

        /**
         * Define the application's command schedule.
         */
        'schedule' => function (Schedule $schedule) {
            $schedule->command(App\Commands\DefaultCommand::class)->daily();
        },
```

What do you guys think? 😏

**Comment by vyuldashev** [comment]
The first approach looks great. Big configuration files will look dirty.

**Comment by introwit** [comment]
As @vyuldashev said, the first option looks neat :+1:

**Comment by nunomaduro** [comment]
For those that are interested on testing this feature: 

`composer create-project --prefer-dist laravel-zero/laravel-zero:dev-release-3.6.0`

**Comment by nunomaduro** [comment]
This feature is now merged on stable! Enjoy! 👍
