### ISSUE TITLE
[4.0 Proposal] Auto Detecting commands

### ISSUE THREAD

**Issue by jkniest** [laravel-zero/laravel-zero#55]
Hello everyone,

I would like to implement the "auto registering commands" feature that is also in laravel 5.5. (See [Docs](https://laravel.com/docs/5.5/artisan#registering-commands)).

That means, all commands in the `app/Commands` directory (the file path would be configurable) would be registered automatically without the need to register them manually in the config file.

This just increases workflow and reduces time needed to register all commands.

Of course I don't want to remove the old way of registering commands (for example if you have a command in another directory).

I can make a PR for this but I just wanted to know if this is a wanted feature. 

Have a nice day,
Jordan

**Comment by rookie0** [comment]
WANTED :smile:

**Comment by introwit** [comment]
Makes sense for me. 👍 @nunomaduro your thoughts?

**Comment by nunomaduro** [comment]
@jkniest I am definitely interested in that.

> That means, all commands in the app/Commands directory (the file path would be configurable) would be registered automatically without the need to register them manually in the config file.

This should be an array of directories on the config. Any none, the framework will automatically assign `app/Commands`.

I will leave this issue open while we wait for the development. Thanks for the help!

**Comment by jkniest** [comment]
Ok, cool.. I will start this evening with the development :)

**Comment by GrahamCampbell** [comment]
Auto detecting commands is easy. Here's some code lifted from from kernel of an app I have:

```php
    /**
     * Get the artisan application instance.
     *
     * @return \Illuminate\Console\Application
     */
    protected function getArtisan()
    {
        if (!$this->artisan) {
            $this->artisan = new Application($this->app, $this->events, $this->app->version());

            // put any other commands in this array
            // in this case, the deploy command here is Bugsnag\BugsnagLaravel\Commands\DeployCommand
            $commands = [DeployCommand::class];

            foreach (glob(app_path('Console//Commands').'/*.php') as $file) {
                $commands[] = 'App\\Console\\Commands\\'.basename($file, '.php');
            }

            $this->artisan->resolveCommands($commands);
        }

        return $this->artisan;
    }
```

**Comment by GrahamCampbell** [comment]
Note that this is not exactly high performance, but fast enough if you don't have many commands, and if you don't care about bootstrapping time, compared to with http where you might.

The performant way to do this would be to have a command that cached the classes to register, similar to how route caching works in the core framework.

**Comment by jkniest** [comment]
I agree with the performance part but the caching commands would add new documentation and explanation, because many users will be confused (at first) why there old commands are still running, even if their not in the $command array anymore (because their cached).

As an alternative, we could make the auto detection optional. For example a bool value in the config file, wether they want to use it.. 

I think in most console application's it doesn't matter much, because they don't have that much commands and if they do have so many, they could simply remove the folder from the detection-array and register all commands manually. 

What are your thoughts?

**Comment by ashleyhood** [comment]
I would of thought this would be similar to Laravel 5.5 package autoload that parses the composer/installed.php so when you add a new package through composer the post update script will trigger a command to rebuild the cache.

This would be additional to the  current way of adding commands.

**Comment by jkniest** [comment]
@ashleyhood Yeah.. but in the current state laravel loads all commands when the application starts, not when composer is updating / dumping the autoload.

I think you are mixing here two different features: Package autoloading & Command autoloading :)

**Comment by ashleyhood** [comment]
@jkniest your right, I did mix the two up 😄 

Should really read and understand before posting 😆

**Comment by nunomaduro** [comment]
@jkniest Do you have news on this? Otherwise I don't mind of implementing this. 😊

**Comment by jkniest** [comment]
Oh sorry.. I haven't much time in the last days.. Feel free to implement this feature.. :-)

**Comment by nunomaduro** [comment]
@jkniest I will see! Thanks for the feedback!

**Comment by nunomaduro** [comment]
Just feature just got implemented in: https://github.com/laravel-zero/framework/commit/dec0346e086d48a2bcf343ad2541a86eb8616edc 👍
