### ISSUE TITLE
Cache example

### ISSUE THREAD

**Issue by antfig** [laravel-zero/laravel-zero#63]
I'm with problems to use cache component. I already installed the component but can't configure and use properly. Can you give some example :)

Thanks for this great tool :)

**Comment by nunomaduro** [comment]
First you should include the facade:

`use Illuminate\Support\Facades\Cache`

Usage:

```
    /**
     * Execute the command. Here goes the code.
     *
     * @return void
     */
    public function handle(): void
    {
        Cache::put('key', 'value', 5); // Stays in cache for 5 mins.

        $value = Cache::get('key');

        $this->info("This is the value: $value");
    }

```

**Comment by nunomaduro** [comment]
@antfig Please don't forget to use the version 3.6. 👍

**Comment by antfig** [comment]
with update to 3.6 I have this error:

```
PHP Fatal error:  Uncaught InvalidArgumentException: Cache store [] is not defined.
```

I created the configuration file for cache like this:
`config/cache.php`
```
<?php

return [
    'default' => 'file',

    'stores' => [

        'file' => [
            'driver' => 'file',
            'path'   => __DIR__ . '/../storage',
        ],
    ]
];

``

**Comment by antfig** [comment]
It's working now :D 
I need to update and add this settings to config.php file.

thanks

**Comment by antfig** [comment]
Now i'm with problems to use filesystem cache :p

```

```

**Comment by nunomaduro** [comment]
Please perform an `composer update` and then:

`php your-app-name component:install illuminate/filesystem`

**Comment by nunomaduro** [comment]
@antfig Do you have news? Otherwise I will close this issue.

**Comment by antfig** [comment]
@nunomaduro sory for the delay, works like a charm ;)
Thanks :D
