### ISSUE TITLE
[4.0] Disable scheduler

### ISSUE THREAD

**Issue by clarkeash** [laravel-zero/laravel-zero#77]
Hi, Is it possible to disable the schedule commands as my application has no use for them?

**Comment by nunomaduro** [comment]
Hummm. I may add that feature this week. 👍

**Comment by nunomaduro** [comment]
@clarkeash For info this feature will be available on the major release 4.0.

**Comment by clarkeash** [comment]
Thats great 😄

**Comment by nunomaduro** [comment]
@clarkeash Laravel Zero 4 released. The feature that you requested is on it!

Checkout the documentation: http://laravel-zero.com/#/?id=scheduler
