### ISSUE TITLE
 Class 'NunoMaduro\Collision\Provider' not found

### ISSUE THREAD

**Issue by edbizarro** [laravel-zero/laravel-zero#78]
Hi Nuno!,

I'm working again on my project after a while and after I update my dependencies I start getting this error

![screenshot2017-11-0502 14 12](https://user-images.githubusercontent.com/84926/32411915-0e28b6ca-c1cf-11e7-8405-72825ccd8058.png)

All versions after `3.6.12` throw this error, the `3.6.12` seems fine.

Tks!

**Comment by nunomaduro** [comment]
Looks like you are using an old Laravel Zero version.

Anyway, I have submitted a PR to fix that issue: https://github.com/edbizarro/changelogger/pull/1 👍

**Comment by edbizarro** [comment]
Tks man!, It's weird because collision already is a zero dependency, right?

**Comment by nunomaduro** [comment]
@edbizarro You are right. Anyway we will not have that problem on the version 4.0. I am preparing a new major version 😊

**Comment by edbizarro** [comment]
Nice!
