### ISSUE TITLE
Build fails when `app.production` => true

### ISSUE THREAD

**Issue by MelonSmasher** [laravel-zero/laravel-zero#79]
When I attempt to build my cli app with the `production` property set to `true` the build is not able to run and I get an error saying that the `app` namespace has no commands registered.

```
[Symfony\Component\Console\Exception\CommandNotFoundException]  
There are no commands defined in the "app" namespace.    
```

Am I doing something wrong?

**Comment by nunomaduro** [comment]
Apparently the build feature is broken since last release. I will try to check this issue as soon as possible. Thanks for reporting!

**Comment by MelonSmasher** [comment]
I looked at `config/app.php` in the compiled phar and `production` is set to true. So this does seem to get set automatically, so it's probably not a huge deal if the build fails when this is set manually. However the compiled version does not behave in the same way as the uncompiled version. The app command set shows up on a compiled phar. See #81.

**Comment by nunomaduro** [comment]
Hey @MelonSmasher! I miss understood the issue. That is a normal behaviour of Laravel Zero. You can't perform a build if you are in production mode.

One feature of the command `app:build` is that it will put your application on production. You don't have to worry about that. 🙂

**Comment by MelonSmasher** [comment]
Makes sense now that I think about it lol, anyway thanks!
