### ISSUE TITLE
Remove `app`, `make`, & `install` commands from compiled phar

### ISSUE THREAD

**Issue by MelonSmasher** [laravel-zero/laravel-zero#81]
The `app`, `make`, and `install` command sets seem unneeded for a production ready bin. Is it possible to have them removed or hidden when the app is compiled?

**Comment by nunomaduro** [comment]
That was a regression introduction recently. The issue should be fixed on the v4.0.6.

Please perform a composer update laravel-zero/framework and tell me the results.

**Comment by MelonSmasher** [comment]
Looks good!
