### ISSUE TITLE
app.name and app.version not displaying with compiled phar

### ISSUE THREAD

**Issue by MelonSmasher** [laravel-zero/laravel-zero#82]
The application name and version seem to revert to the default when the application is compiled. From the outside it looks like the compiled version is ignoring `config/app.php`. Not sure if this is related to #81?

**Comment by nunomaduro** [comment]
That was a regression introduction recently. The issue should be fixed on the v4.0.6.

Please perform a composer update laravel-zero/framework and tell me the results.

Thanks for reporting that issue! ❤️

**Comment by MelonSmasher** [comment]
Looks good! Thanks for the quick support!
