### ISSUE TITLE
Standalone build succeeded but no command

### ISSUE THREAD

**Issue by jaredchu** [laravel-zero/laravel-zero#83]
As the title, the output of command `app:build` has no command that I put in `App\Commands` .

**Comment by nunomaduro** [comment]
@jaredchu what version of Laravel Zer are you using? 👍

**Comment by jaredchu** [comment]
I'm using version v4.0.2, it's the latest version of yesterday.

**Comment by jaredchu** [comment]
It's also doesn't autoload my commands that I put in `App\Commands`, so I need to declare them manually in `config/app.php`, example:
```PHP
'commands' => [
        App\Commands\NewTrellis::class,
        App\Commands\UpdateGitkraken::class,
        App\Commands\DownloadWordpress::class,
    ],
```

**Comment by nunomaduro** [comment]
@jaredchu Please perform a “composer update laravel-zero/framework” and tell me the results.

**Comment by nunomaduro** [comment]
The issue should be fixed after the update 😊

**Comment by jaredchu** [comment]
It's fixed. Thanks a lot.
