### ISSUE TITLE
.env not working?

### ISSUE THREAD

**Issue by mprandot** [laravel-zero/laravel-zero#85]
Hello!

I set a APP_ENV in my .env created in project root, and this always returns null.

`dd(env('APP_ENV'));`

Someone can reproduce this?

**Comment by nunomaduro** [comment]
@mprandot The DotEnv PHP library is not included on Laravel Zero. Give me some minutes to think about this.

**Comment by mprandot** [comment]
Ah, no problem! I've found in a illuminate Helper class that has a `env` method, then i thinked "i can use it" :smile:

**Comment by TNovalis** [comment]
I don't think we should be using a `.env` for Laravel-Zero. I would recommend just doing something like the following:
`config/filesystems.php`
```php 
return [
    'default' => env('FILESYSTEM_DRIVER', 'local'),
    'disks' => [
        'local' => [
            'driver' => 'local',
            'root' => $_SERVER['HOME'].'/.your-project',
        ],
    ],
];
```
This way you can just use the `Storage` facade to put files where you need them. This is similar to how composer handles user configuration (albeit without the fancy facade of course.)
