### ISSUE TITLE
Using database and storage in build not working

### ISSUE THREAD

**Issue by dimitricappelle** [laravel-zero/laravel-zero#86]
I wrote a small local console app that uses a database and storage (downloads). 
The app runs perfect except as a standalone build, then the database and storage are not found.

```
Illuminate\Database\QueryException : Database (phar:///Users/dimitri/ConsoleApp/builds/application/config/../../database/database.sqlite) does not exist.
```
Is it possible to create a standalone build with database and storage?

**Comment by TNovalis** [comment]
You are actually able to override where the sqlite database is.
For a build (or any for that matter), I would recommend putting it into the user's directory like this:
`config/database.php`
```php
<?php
return [
    /*
     * If true, migrations commands will be available.
     */
    'with-migrations' => true,
    /*
     * Here goes the application database connection configuration. By
     * default, we use `sqlite` as a driver. Feel free to use another
     * driver, be sure to check the database component documentation.
     */
    'connections' => [
        'default' => [
            'driver' => 'sqlite',
            'database' => $_SERVER['HOME'].'/.your-project/database.sqlite',
        ],
    ],
];
```
This will set it so your database is in the user's home directory, Ex: `/home/novalis/.your-project/database.sqlite`

You will need to create this file or instruct the user to create it. The reason I recommend the user's directory is whether in Linux, Mac or Windows the user's home directory will be set correctly and you won't need to worry about permissions of writing to it.

**Comment by nunomaduro** [comment]
@dimitricappelle try the @TNovalis solution and give us feedback 👍

**Comment by TNovalis** [comment]
@dimitricappelle Also noticed that you said storage as well, I have recently provided an example for this as well in #85 so you can check that out as well.

**Comment by dimitricappelle** [comment]
Referring to $_SERVER['HOME'] works for both issues.
Thanks!

**Comment by nunomaduro** [comment]
I may need to specify this on the docs...
