### ISSUE TITLE
Distributing built project via composer

### ISSUE THREAD

**Issue by svenluijten** [laravel-zero/laravel-zero#90]
Hi 🙂 I'm intrigued by this project, but I have a question. Can I distribute my built project via composer/packagist? So people could do `composer global require vendor/my-zero-project`? 

I couldn't find anything about this in the docs, and AFAIK the `bin` option in a `composer.json` doesn't support `.phar` files, so I won't be able to use that. 

Thanks in advance!

**Comment by nunomaduro** [comment]
@svenluijten Good question! Give me some minutes to perform some tests.

**Comment by nunomaduro** [comment]
@svenluijten It's working ❤️

You can distribute your project like the following example: https://github.com/laravel-zero/installer/tree/composer-with-build

**Comment by svenluijten** [comment]
Oh sweet! Thanks for the quick response, and I'm glad this (admittedly inadvertently) solved another issue you were having 🎉
