### ISSUE TITLE
How can i use Laravel Log Facade.

### ISSUE THREAD

**Issue by lesstif** [laravel-zero/laravel-zero#94]
when i used laravel log facade, i got the BindingResolutionException.

```php
\Illuminate\Support\Facades\Log::debug('debug msg');
```

```sh
 Illuminate\Contracts\Container\BindingResolutionException : Target [Psr\Log\LoggerInterface] is not instantiable.
```

how can i instantiation Log facade.?

**Comment by nunomaduro** [comment]
The `illuminate/log` component is not included on the Laravel Framework. If you want, I can develop during this week a feature like: `php <your-application-name> install:log`.

**Comment by glopez620** [comment]
yes that would be great, I am also trying to use illuminate/log with my app

**Comment by nunomaduro** [comment]
@lesstif @glopez620 The illuminate/log component of Laravel is now available. Please perform `php <your-application-name> install:log`.

Usage:

```
use Illuminate\Support\Facades\Log;

Log::debug("Your debug message");
```

**Comment by lesstif** [comment]
it works fine. thanks!

**Comment by johnellmore** [comment]
When I tried to run `php <application-name> install:log` on a Laravel Zero 5.6.17 app, I got the following error:

```
There are no commands defined in the "install" namespace.
```

That's because the install command has changed to `app:install` instead. So you actually need to run this:

```
php <application-name> app:install log
```

Hope this helps someone!

**Comment by nunomaduro** [comment]
@johnellmore This issue was from an old version of Laravel Zero. The new version is documented at: [https://laravel-zero.com](https://laravel-zero.com)

**Comment by kniteshsri** [comment]
while i tried to perform the above task i was getting this error.
>> php sampleIMS install:log
>> **Could not open input file: sampleIMS**

**Comment by ashleyhood** [comment]
@kniteshsri read the docs [https://laravel-zero.com/#/usage?id=log](url)

**Comment by ashleyhood** [comment]
@kniteshsri my previous comment may have sounded harsher then I intended.

The reason the command `php sampleIMS install:log` fails is because the install command would now be `php sampleIMS app:install log`

**Comment by kniteshsri** [comment]
while i tried to perform the above task i was getting this error.
>> php sampleIMS install:log
>> **Could not open input file: sampleIMS**

>> php sampleIMS app:install log
>> **Could not open input file: sampleIMS**

**Comment by nroussis** [comment]
Can you do something similar for laravel notifications as well? :)

**Comment by abkrim** [comment]
> @lesstif @glopez620 The illuminate/log component of Laravel is now available. Please perform `php <your-application-name> install:log`.
> 
> Usage:
> 
> ```
> use Illuminate\Support\Facades\Log;
> 
> Log::debug("Your debug message");
> ```

On [Laravel-Zero Docs](https://laravel-zero.com/docs/logging) indicates to use `Use Log;`
This doesn't seem to work, and instead if it works `use Illuminate \ Support \ Facades \ Log;`

Is it for something in particular or would it be worth editing the coumentation?

**Comment by owenvoke** [comment]
@abkrim, I think this is because the docs assume you've set up the facade alias. I've updated this now, however if you were to add the alias to your `config/app.php`, then the singular `Log` class would work. 👍🏻
