### ISSUE TITLE
[Proposal] Add tool to launch a browser

### ISSUE THREAD

**Issue by philip** [laravel-zero/laravel-zero#95]
RFC: tool to launch a browser window. It might look like one of:

    $browser->open($url);
    $lz->openBrowser($url);

In its simplest form it'd call the likes of:

    // Linux
    xdg-open "$url"

    // macOS
    open "$url"

    // Windows
    start "$url"

A few potential features:

* Allow defining full paths to browsers on the system (e.g., `'firefox' => '/usr/bin/firefox'`)
* Implement browser discovery on the system (e.g., find path to firefox, safari, chrome, ...)
* If browser discovery works then allow either:
  * require a specific browser (e.g., only use firefox)
  * prefer a specific browser (e.g., use firefox if you find it, else use the default)

I'm not sure if this belongs in Laravel Zero or as its own package but am posting this desire here as Laravel Zero is the future of CLI programming :) All feedback is welcome.

**Comment by nunomaduro** [comment]
@Philip That is definitely a good idea. I will investigate this during the week. Probably a good idea is making a side package with an adapter for Laravel and Laravel Zero.

**Comment by nunomaduro** [comment]
Thanks! But I think this should be a side package!
