### ISSUE TITLE
[Proposal] Helper for platform detection

### ISSUE THREAD

**Issue by philip** [laravel-zero/laravel-zero#96]
An action's definition may depend on the platform. For example, issue #95 launches a browser window and must know the platform / operating system.

Laravel Zero might require a package for this or offer something simpler as, in theory, this is not overly complicated.

Native Laravel has a `windows_os()` helper but nothing for Darwin or Linux detection. Some actions must differentiate macOS and Linux such as the aforementioned browser launching tool.

Possible packages include:
  * [Tivie\OS\Detector](https://github.com/tivie/php-os-detector)

Know of others? Have general thoughts on the matter?

**Comment by philip** [comment]
A similar implementation is this patch:
  https://github.com/sebastianbergmann/environment/commit/eb6dd721cfaca04c27ac61c7201493a8f62f7f1d

It shows one way to implement PHP 7.2's new `PHP_OS_FAMILY` constant. In this sense, it might make sense to only use that class (or one like it) or add the following as a dependency:

https://github.com/sebastianbergmann/environment

**Comment by nunomaduro** [comment]
Hum, interesting. We could make a package called `laravel-environment` that is only a service provider of `https://github.com/sebastianbergmann/environment`.

**Comment by nunomaduro** [comment]
This should be a side package. I am not interested in putting this on the core. Thanks tho!
