### ISSUE TITLE
Task Scheduling not working for built application

### ISSUE THREAD

**Issue by ashleyhood** [laravel-zero/laravel-zero#98]
**Laravel-zero:** 4.0.12

When running `myapp schedule:run` it works as expected but when the project is built into an app, it fails.

The scheduled task is using the full phar url which doesn't work.

    '/usr/bin/php7.1' 'phar:///path/to/builds/myapp/myapp' test:scheduler > '/dev/null' 2>&1

When I run the above command manually I get the following output;

    Could not open input file: phar:///path/to/builds/myapp/myapp

I think there needs to be some kind of detection for when some commands are run from inside a phar and then use the appropriate path.  Something like this:

    if (!empty($pharPath = Phar::running(false))) {
        return dirname($pharPath);
    } else {
        return app()->basePath();
    }

Or I've totally missed something simple 😕

**Comment by ashleyhood** [comment]
I solved this by modifying `laravel-zero/framework/src/Bootstappers/Constants.php` as follows:

    public function bootstrap(): void
    {
        if (!empty($pharPath = \Phar::running(false))) {
            $basePath = dirname($pharPath);
        } else {
            $basePath = defined('BASE_PATH') ? BASE_PATH : '';
        }

        if (! defined('ARTISAN_BINARY')) {
            define('ARTISAN_BINARY', $basePath.'/'.basename($_SERVER['SCRIPT_FILENAME']));
        }
    }

I don't know if this will break anything else, but it works for my application.

**Comment by nunomaduro** [comment]
@ashleyhood Thanks! I will check that tonight!

**Comment by nunomaduro** [comment]
@ashleyhood Can you do a PR please ? :)

**Comment by nunomaduro** [comment]
@ashleyhood Your issue should be fixed on the version v4.0.14. Can you perform `composer update laravel-zero/framework` and test it please?

**Comment by ashleyhood** [comment]
@nunomaduro version v4.0.14 fixed this.
