### ISSUE TITLE
Replacing IOC bindings in tests doesn't work

### ISSUE THREAD

**Issue by svenluijten** [laravel-zero/laravel-zero#99]
I'm having some issues while trying to replace IOC bindings with my own (mocked) versions in tests. This is my situation:

I have a `TestService.php` with one method in it (`someMethod`) that just returns a string to signify it's coming from the actual (non-mocked) version of the class: https://github.com/svenluijten/laravel-zero-ioc-test/blob/master/app/TestService.php.

This service is injected in the container in [the `AppServiceProvider`](https://github.com/svenluijten/laravel-zero-ioc-test/blob/master/app/Providers/AppServiceProvider.php) without anything special. 

In [the `HelloCommand` class](https://github.com/svenluijten/laravel-zero-ioc-test/blob/master/app/Commands/HelloCommand.php) I'm injecting that service into the container and dumping the result of `->someMethod()` in the handle method. Pretty straight forward, right?

In [my test](https://github.com/svenluijten/laravel-zero-ioc-test/blob/master/tests/Integration/HelloCommandTest.php), all I'm doing is creating a mock of that service and configuring it so that `->someMethod()` returns `from tests` to indicate that it's the mocked version that we're using. 

That mock is then injected into the service container using `app()->instance(...);`, after which the command that has the service injected into it is called. 

I would expect the dumped result to be `from tests`, because it would have grabbed the mock from the service container instead of the "standard" implementation (registered via the `AppServiceProvider`).

Instead, I get the result `from the actual class!`! I honestly have no idea where to even begin looking with this issue 😖

**Comment by svenluijten** [comment]
After a bit of debugging by @rickbolton and myself, we found [this line](https://github.com/laravel-zero/framework/blob/c4d9fb74c370d14f4e00cadbb8530325a346f011/src/Application.php#L58), which we thought was the perpetrator. We thought changing that to `Container::getInstance()` instead of manually newing up the container (like it is now) would fix the issue, but it didn't. 

Will do some more digging!

**Comment by svenluijten** [comment]
After our discussion in Slack, Nuno found the issue:

The command is instantiated while bootstrapping everything (eg. building the application, etc.), so adding a mock into the container will not register with the command. To temporarily fix this, I've added the following method to my `TestCase` class to resolve the command out of the container again (with the right dependencies), and add it back to the application:

```php
/**
 * @param string $command
 * @param array  $arguments
 */
protected function call($command, array $arguments = [])
{
    $command = $this->app->getContainer()->make($command);

    $this->app->add($command);

    $this->app->call($command->getName(), $arguments);
}
```

This way, we can do the following in the tests:

```php
/** @test */
function it_tests_a_mocked_dependency()
{
    $mock = $this->createMock(TestService::class);

    $this->app->getContainer()->instance(TestService::class, $mock);

    $mock->expects($this->once())->method('someMethod')->willReturn('from the tests');

    $this->call(HelloCommand::class);
}
```

Thanks, @nunomaduro for the help!

**Comment by jhoff** [comment]
Thanks for this. I just spent a day fighting with this issue.

**Comment by sandervanhooft** [comment]
Is there a way to only bind and not call the mocked command? I am trying to test that executing command A (non-mocked) after completion calls command B (mocked).

**Comment by nunomaduro** [comment]
@sandervanhooft You want to make sure a command is called right?

**Comment by sandervanhooft** [comment]
Hi @nunomaduro , yes that's right.

**Comment by sandervanhooft** [comment]
Meanwhile, I'm testing the solution offered by @svenluijten:

1. I receive an error that the `call()` method should be made `public` instead of `protected`. So I did.
2. Then I receive another error:
```
Call to undefined method LaravelZero\Framework\Application::getContainer()
```
This is triggered for this line from Sven's example:

```
$this->app->getContainer()->instance(PaymentListCommand::class, $mock);
```

**Comment by sandervanhooft** [comment]
The only non-basic thing is that I have Console Dusk installed.

**Comment by sandervanhooft** [comment]
> @sandervanhooft You want to make sure a command is called right?

Yes, but the command I want to make sure is called is called _indirectly_ from another command.

**Comment by nunomaduro** [comment]
@sandervanhooft A solution may be have a class `service` that does the real job from the secondary command. And then, mock that `service` class using the container.

**Comment by sandervanhooft** [comment]
Ok, so I have a

**Comment by sandervanhooft** [comment]
I'm going to dive a bit deeper into this in the next few days (hopefully), will let you know how it goes!

So far absolutely 💗💗  Laravel Zero by the way!

And however briefly - nice to meet you at Laracon.eu!

**Comment by sandervanhooft** [comment]
> @sandervanhooft A solution may be have a class `service` that does the real job from the secondary command. And then, mock that `service` class using the container.

May be an interesting approach, but I think the `assertCommandCalled` will be a recurring theme in my app and probably in other devs' as well.

**Comment by nunomaduro** [comment]
Hummmm. Could you think about an implementation for that? Would be good to add it to Laravel Zero or even to Laravel itself.

**Comment by sandervanhooft** [comment]
Absolutely no idea yet. May need to implement a spy on the Kernel?

**Comment by nunomaduro** [comment]
I let you think about this, just make sure you prototype something quick and let's think about the real implementation later 👍

**Comment by sandervanhooft** [comment]
Did a quick scan, I can think of three directions currently:

1. Inspired by `Event::fake()`, wrap `Illuminate\Command` in a spy when using `Command:spy` helper. Then use a `assertCommandCalled($command, ?$callback)` test helper for asserting. It seems impossible to me to go a level deeper because then we get into Symphony territory.

2. Add lifecycle Events to the Command calls ([like Eloquent model has](https://laravel.com/docs/5.7/eloquent#events)) and track these using `Event::fake()` and `Event::assertDispatched(...)`

3. Do both. But that's a bit much atm.

What do you think?

**Comment by sandervanhooft** [comment]
(1. "feels" possible, but will be a stretch for me so may take some time)

**Comment by nunomaduro** [comment]
@sandervanhooft Can you create a new issue with the content of that proposal? Sorry, but I would like to really follow this.
